package com.guangyingruoshui.imagetools;

import android.content.Context;
import android.graphics.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.zip.*;

final class AndroidTests {
    static void require(boolean condition,String message)throws Exception{if(!condition)throw new IOException("TEST FAILED: "+message);}
    static void run(Context c,File unused,Files.Job j)throws Exception{File external=c.getExternalFilesDir(null);File dir=new File(external==null?c.getFilesDir():external,"verification");if(!dir.isDirectory()&&!dir.mkdirs())throw new IOException("Cannot create test directory");File report=new File(dir,"report.txt");StringBuilder log=new StringBuilder();Bitmap real=null,cover=null;try{
        real=Bitmap.createBitmap(37,29,Bitmap.Config.ARGB_8888);int[] pixels=new int[37*29];for(int k=0;k<pixels.length;k++)pixels[k]=0xff000000|((k*76379)^0x43547a)&0xffffff;real.setPixels(pixels,0,37,0,0,37,29);cover=Images.defaultCover(37);File original=new File(dir,"原图.png");Images.encode(real,original,0,j);String originalHash=Files.hash(original,j);
        Bitmap transformed=Images.load(original,0,true);Images.transform(transformed,false,j);Images.transform(transformed,true,j);int[] restoredPixels=new int[pixels.length];transformed.getPixels(restoredPixels,0,37,0,0,37,29);transformed.recycle();require(Arrays.equals(pixels,restoredPixels),"Gilbert pixel inverse");log.append("PASS: exact Gilbert pixel scrambling inverse\n");
        File dual=new File(dir,"双图.png");Bitmap fitted=Images.fit(cover,37,29,Color.WHITE);Images.dual(fitted,real,dual,j);fitted.recycle();File restored=Files.dualRestore(dual,dir,j);Bitmap hidden=Images.load(restored,0,true);hidden.getPixels(restoredPixels,0,37,0,0,37,29);hidden.recycle();require(Arrays.equals(pixels,restoredPixels),"APNG hidden pixels");log.append("PASS: dual APNG restores all hidden pixels\n");
        File scrambled=Images.scramble(original,dir,false,-1,j),back=Images.restoreOriginal(scrambled,dir,j);require(Files.hash(back,j).equals(originalHash),"original bytes SHA256");log.append("PASS: scramble original-file restoration SHA-256 matches\n");
        try(RandomAccessFile corrupt=new RandomAccessFile(scrambled,"rw")){corrupt.seek(50);int v=corrupt.read();corrupt.seek(50);corrupt.write(v^1);}boolean rejected=false;try{Images.restoreOriginal(scrambled,dir,j);}catch(IOException e){rejected=true;}require(rejected,"tampered scramble accepted");log.append("PASS: tampered original-file container rejected\n");
        File tagged=new File(dir,"tagged.png");JSONObject graph=new JSONObject("{\"1\":{\"class_type\":\"CLIPTextEncode\",\"inputs\":{\"text\":\"beautiful landscape\"}},\"2\":{\"class_type\":\"CLIPTextEncode\",\"inputs\":{\"text\":\"bad quality\"}},\"3\":{\"class_type\":\"KSampler\",\"inputs\":{\"positive\":[\"1\",0],\"negative\":[\"2\",0],\"seed\":1234567890123456789,\"cfg\":7,\"steps\":20}}}");
        try(InputStream in=new FileInputStream(original);OutputStream out=new FileOutputStream(tagged)){out.write(Files.PNG);Files.read(in,8);byte[] header=Files.read(in,8);int n=(int)Files.be(header,0,4);byte[] data=Files.read(in,n),crc=Files.read(in,4);out.write(header);out.write(data);out.write(crc);Files.chunk(out,"tEXt",Files.concat("parameters\u0000".getBytes(Files.LATIN),"beautiful landscape\nNegative prompt: bad quality\nSteps: 20, Sampler: Euler, CFG scale: 7, Seed: 1234567890123456789, Size: 37x29".getBytes(Files.LATIN)));Files.chunk(out,"iTXt",Files.concat("prompt\u0000".getBytes(Files.LATIN),new byte[4],graph.toString().getBytes(Files.UTF8)));Files.copy(in,out,j);}
        Metadata.Result info=Metadata.inspect(tagged,j);require(info.web.get("正面 tag / Positive tag").equals("beautiful landscape"),"WebUI positive tag");require(info.web.get("Seed").equals("1234567890123456789"),"WebUI seed precision");require(info.comfy.get(0).get("正面 tag / Positive tag").equals("beautiful landscape"),"ComfyUI positive tag");require(info.comfy.get(0).get("负面 tag / Negative tag").equals("bad quality"),"ComfyUI negative tag");require(info.comfy.get(0).get("seed").equals("1234567890123456789"),"ComfyUI seed precision");log.append("PASS: WebUI/ComfyUI positive, negative, CFG, steps and 64-bit seed\n");
        File cleaned=Metadata.clean(tagged,dir,j);Metadata.Result absent=Metadata.inspect(cleaned,j);require(absent.web.isEmpty()&&absent.comfy.isEmpty(),"metadata remains");require(Files.hash(cleaned,j).equals(originalHash),"clean changed PNG image bytes");log.append("PASS: metadata removal leaves original PNG bytes exactly intact\n");
        JSONObject custom=new JSONObject("{\"1\":{\"class_type\":\"MyCustomString\",\"inputs\":{\"text\":\"custom positive\"}},\"2\":{\"class_type\":\"EasyLoader\",\"inputs\":{\"positive\":[\"1\",0],\"negative\":\"custom negative\"}},\"3\":{\"class_type\":\"KSampler\",\"inputs\":{\"positive\":[\"2\",4],\"negative\":[\"2\",5],\"steps\":25}}}");Metadata.Result customInfo=new Metadata.Result();Metadata.comfy(custom,null,customInfo);require(customInfo.comfy.get(0).get("正面 tag / Positive tag").equals("custom positive"),"custom node positive");require(customInfo.comfy.get(0).get("负面 tag / Negative tag").equals("custom negative"),"custom node negative");log.append("PASS: linked custom text nodes and loader positive/negative outputs\n");
        File zip=new File(dir,"中文压缩包.zip");try(ZipOutputStream out=new ZipOutputStream(new FileOutputStream(zip))){out.putNextEntry(new ZipEntry("中文说明.txt"));out.write("无损还原测试".getBytes(Files.UTF8));out.closeEntry();}byte[] jpg=Archive.cover(cover,dir,j);File packed=Archive.pack(jpg,zip,zip.getName(),dir,j),zipBack=Archive.restore(packed,dir,j);require(Files.hash(zip,j).equals(Files.hash(zipBack,j)),"ZIP hash mismatch");require(packed.getName().contains("_a2i"),"archive naming");try(ZipFile originalZip=new ZipFile(zipBack)){require(originalZip.size()==1,"restored ZIP parser");}log.append("PASS: compatible JPG-ZIP directory and exact original SHA-256; prefixed ZIP checked externally because Android 5 Java ZipFile rejects any prefix\n");
        File mp4=new File(dir,"视频.mp4");try(OutputStream out=new FileOutputStream(mp4)){out.write(Files.concat(Files.be(16),"ftypisom".getBytes(Files.LATIN),new byte[4]));out.write(Files.concat(Files.be(8),"moov".getBytes(Files.LATIN)));out.write(Files.concat(Files.be(12),"mdat".getBytes(Files.LATIN),new byte[]{1,2,3,4}));}File vjpg=Archive.pack(jpg,mp4,mp4.getName(),dir,j),vback=Archive.restore(vjpg,dir,j);require(Files.hash(mp4,j).equals(Files.hash(vback,j)),"MP4 hash mismatch");require(vjpg.getName().contains("_v2i"),"video naming");log.append("PASS: MP4 container and exact original SHA-256 (structural fixture, not playable video)\n");
        for(String asset:new String[]{"fixture.rar","fixture.7z","playable.mp4"}){try(InputStream in=c.getAssets().open(asset)){File archive=new File(dir,asset);try(OutputStream out=new FileOutputStream(archive)){Files.copy(in,out,j);}File encoded=Archive.pack(jpg,archive,archive.getName(),dir,j),decoded=Archive.restore(encoded,dir,j);require(Files.hash(archive,j).equals(Files.hash(decoded,j)),asset+" SHA256");log.append("PASS: ").append(asset).append(" original-file SHA-256\n");}}
        Files.Job cancel=new Files.Job();cancel.cancelled=true;rejected=false;try{Images.scramble(original,dir,false,0,cancel);}catch(InterruptedIOException e){rejected=true;}require(rejected,"cancel not respected");log.append("PASS: cancelled operation creates no final file\n");
        Gif.encode(Arrays.asList(original,cleaned),dir,100,100,true,Color.WHITE,j);log.append("PASS: two-frame GIF generated for external decode validation\n");
        require(!Files.unique(dir,"safe.png").equals(Files.unique(dir,"原图.png")),"unique naming");rejected=false;try{Files.name("../escape.zip");}catch(IOException e){rejected=true;}require(rejected,"path traversal");log.append("PASS: filename traversal rejected; Unicode paths and duplicate names\n");
        try(InputStream in=c.getAssets().open("pc-double.png")){File pc=new File(dir,"pc-double.png");try(OutputStream out=new FileOutputStream(pc)){Files.copy(in,out,j);}Files.dualRestore(pc,dir,j);log.append("PASS: desktop-generated dual PNG restored on Android\n");}
        try(InputStream input=c.getAssets().open("inspection-fixtures/index.json")){ByteArrayOutputStream bytes=new ByteArrayOutputStream();Files.copy(input,bytes,j);JSONArray cases=new JSONArray(new String(bytes.toByteArray(),Files.UTF8));for(int index=0;index<cases.length();index++){JSONObject test=cases.getJSONObject(index);String name=test.getString("name");File file=new File(dir,name);try(InputStream source=c.getAssets().open("inspection-fixtures/"+name);OutputStream target=new FileOutputStream(file)){Files.copy(source,target,j);}Metadata.Result actual=Metadata.inspect(file,j);JSONArray web=test.getJSONArray("web"),nodes=test.getJSONArray("comfy");if(web.length()>0){require(web.getString(0).equals(actual.web.get("正面 tag / Positive tag")),name+" WebUI positive");require(web.getString(1).equals(actual.web.get("负面 tag / Negative tag")),name+" WebUI negative");}for(int k=0;k<nodes.length();k++){JSONObject expected=nodes.getJSONObject(k);Map<String,String> found=null;for(Map<String,String> fields:actual.comfy)if(expected.getString("node").equals(fields.get("采样节点 / Sampler node")))found=fields;require(found!=null,name+" sampler "+expected.getString("node"));require(expected.getString("positive").equals(found.get("正面 tag / Positive tag")),name+" ComfyUI positive expected="+expected.getString("positive")+" actual="+found.get("正面 tag / Positive tag"));require(expected.getString("negative").equals(found.get("负面 tag / Negative tag")),name+" ComfyUI negative expected="+expected.getString("negative")+" actual="+found.get("负面 tag / Negative tag"));if(!expected.getString("seed").isEmpty())require(found.containsValue(expected.getString("seed")),name+" exact seed");}log.append("PASS: desktop metadata fixture ").append(name).append('\n');}}
        File blank=new File(dir,"blank.png");try(InputStream in=new FileInputStream(original);OutputStream out=new FileOutputStream(blank)){out.write(Files.PNG);Files.read(in,8);byte[] h=Files.read(in,8);int n=(int)Files.be(h,0,4);out.write(h);out.write(Files.read(in,n+4));Files.chunk(out,"tEXt","parameters\u0000".getBytes(Files.LATIN));Files.copy(in,out,j);}require(Metadata.inspect(blank,j).web.isEmpty(),"empty WebUI must be skipped");log.append("PASS: empty WebUI metadata is not exported\n");
        File orientationJpg=new File(dir,"oriented.jpg"),plainJpg=new File(dir,"plain.jpg");Bitmap ob=Bitmap.createBitmap(31,19,Bitmap.Config.ARGB_8888);ob.eraseColor(Color.RED);Images.encode(ob,plainJpg,95,j);ob.recycle();try(InputStream in=new FileInputStream(plainJpg);OutputStream out=new FileOutputStream(orientationJpg)){Files.read(in,2);out.write(new byte[]{(byte)255,(byte)216,(byte)255,(byte)225,0,34});out.write("Exif\u0000\u0000".getBytes(Files.LATIN));out.write(Metadata.orientationExif(6));Files.copy(in,out,j);}Bitmap oriented=Images.load(orientationJpg,0,true);require(oriented.getWidth()==19&&oriented.getHeight()==31,"EXIF orientation");oriented.recycle();File orientationClean=Metadata.clean(orientationJpg,dir,j);require(Metadata.imageOrientation(orientationClean)==6,"clean lost orientation");log.append("PASS: JPEG orientation normalized for editing and preserved during metadata removal\n");
        byte[] longBytes=new byte[8];Files.le(longBytes,0,0x100000007L,8);require(Files.le(longBytes,0,8)==0x100000007L,"64-bit lengths");Files.range(0x80000000L,0x80000000L,0x100000000L);log.append("PASS: 64-bit length/offset arithmetic above 2 GiB (not a full >2 GiB physical file test)\n");
        if(dir.getUsableSpace()>600L*1048576){File large=new File(dir,"large170.zip");byte[] block=new byte[1048576];CRC32 checksum=new CRC32();for(int k=0;k<170;k++)checksum.update(block);try(ZipOutputStream out=new ZipOutputStream(new FileOutputStream(large))){ZipEntry entry=new ZipEntry("large.bin");entry.setMethod(ZipEntry.STORED);entry.setSize(170L*1048576);entry.setCrc(checksum.getValue());out.putNextEntry(entry);for(int k=0;k<170;k++)out.write(block);out.closeEntry();}long start=android.os.SystemClock.uptimeMillis();File largeJpg=null,largeBack=null;try{largeJpg=Archive.pack(jpg,large,large.getName(),dir,j);largeBack=Archive.restore(largeJpg,dir,j);require(Files.hash(large,j).equals(Files.hash(largeBack,j)),"large ZIP original hash");Files.Job interrupted=new Files.Job();interrupted.progress=(done,total)->{if(done>=1048576)interrupted.cancelled=true;};boolean stopped=false;try{Archive.pack(jpg,large,large.getName(),dir,interrupted);}catch(InterruptedIOException expected){stopped=true;}require(stopped,"in-flight cancel");log.append("PASS: actual 170 MiB stored ZIP streaming pack/restore SHA-256; in-flight cancellation; ").append(android.os.SystemClock.uptimeMillis()-start).append(" ms\n");}finally{large.delete();if(largeJpg!=null)largeJpg.delete();if(largeBack!=null)largeBack.delete();}}
        log.append("ALL CORE TESTS PASS\n");
        }catch(Throwable e){log.append("FAIL: ").append(e.toString()).append('\n');try(StringWriter sw=new StringWriter();PrintWriter p=new PrintWriter(sw)){e.printStackTrace(p);log.append(sw.toString());}throw e;}finally{if(real!=null)real.recycle();if(cover!=null)cover.recycle();try(OutputStream out=new FileOutputStream(report)){out.write(log.toString().getBytes(Files.UTF8));}}
    }
}
