package com.guangyingruoshui.imagetools;

import android.graphics.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

final class UiTests {
    static void ui(MainActivity m,Runnable action)throws Exception{CountDownLatch done=new CountDownLatch(1);Throwable[] failure={null};m.ui.post(()->{try{action.run();}catch(Throwable e){failure[0]=e;}finally{done.countDown();}});if(!done.await(10,TimeUnit.SECONDS))throw new IOException("UI timed out");if(failure[0]!=null)throw new IOException("UI test failed",failure[0]);}
    static void frames(MainActivity m)throws Exception{CountDownLatch done=new CountDownLatch(1);m.ui.post(()->m.root.postOnAnimation(()->m.root.postOnAnimation(done::countDown)));if(!done.await(10,TimeUnit.SECONDS))throw new IOException("Frame wait timed out");}
    static void drag(MainActivity m,View list,boolean up)throws Exception{int[] location=new int[2];float[] xy=new float[3];ui(m,()->{list.getLocationInWindow(location);xy[0]=location[0]+list.getWidth()/2f;xy[1]=location[1]+list.getHeight()*(up?.8f:.2f);xy[2]=location[1]+list.getHeight()*(up?.2f:.8f);});long down=SystemClock.uptimeMillis();ui(m,()->{MotionEvent e=MotionEvent.obtain(down,down,MotionEvent.ACTION_DOWN,xy[0],xy[1],0);m.dispatchTouchEvent(e);e.recycle();});for(int i=1;i<=12;i++){final float y=xy[1]+(xy[2]-xy[1])*i/12;Thread.sleep(16);ui(m,()->{MotionEvent e=MotionEvent.obtain(down,SystemClock.uptimeMillis(),MotionEvent.ACTION_MOVE,xy[0],y,0);m.dispatchTouchEvent(e);e.recycle();});}Thread.sleep(180);ui(m,()->{MotionEvent e=MotionEvent.obtain(down,SystemClock.uptimeMillis(),MotionEvent.ACTION_MOVE,xy[0],xy[2],0);m.dispatchTouchEvent(e);e.recycle();});Thread.sleep(25);ui(m,()->{MotionEvent e=MotionEvent.obtain(down,SystemClock.uptimeMillis(),MotionEvent.ACTION_UP,xy[0],xy[2],0);m.dispatchTouchEvent(e);e.recycle();});frames(m);}
    static void queueTests(MainActivity m,File dir,StringBuilder report)throws Exception{File fixture=new File(dir,"Screenshot_20261003_test_really_long_filename_to_check_middle_ellipsis_012345678901234567890123456789.png");try(InputStream in=new FileInputStream(new File(dir,"原图.png"));OutputStream out=new FileOutputStream(fixture)){Files.copy(in,out,new Files.Job());}
        ui(m,()->{for(Map.Entry<MainActivity.State,ListView> entry:m.queues.entrySet()){MainActivity.State state=entry.getKey();state.entries.clear();for(int i=0;i<20;i++)state.entries.add(new MainActivity.Entry(fixture));state.selected=0;m.refreshQueue(state);}m.showPage(3);});frames(m);Widgets.QueueList[] selected={null};ui(m,()->{for(Map.Entry<MainActivity.State,ListView> entry:m.queues.entrySet()){Widgets.QueueList q=(Widgets.QueueList)entry.getValue();int screen=q.usableHeight();if(q.getMeasuredHeight()<screen/4||q.getMeasuredHeight()>screen/3)throw new IllegalStateException("Queue screen ratio: "+q.getMeasuredHeight()+" / "+screen);}Widgets.QueueList q=(Widgets.QueueList)m.queues.get(m.state[3]);selected[0]=q;Rect rect=new Rect();q.getDrawingRect(rect);m.pages[3].offsetDescendantRectToMyCoords(q,rect);m.pages[3].scrollTo(0,rect.top-m.dp(16));q.setSelectionFromTop(0,0);});frames(m);
        Widgets.QueueList q=selected[0];int[] before={0},anchor={0};ui(m,()->{if(q.getChildCount()!=3)throw new IllegalStateException("Expected 3 complete queue rows, found "+q.getChildCount());TextView name=(TextView)((LinearLayout)q.getChildAt(0)).getChildAt(0);if(name.getLineCount()!=1||(name.getPaint().measureText(name.getText().toString())>name.getWidth()&&name.getLayout().getEllipsisCount(0)<=0))throw new IllegalStateException("Filename must be one line with middle ellipsis");before[0]=m.pages[3].getScrollY();anchor[0]=before[0];});drag(m,q,true);ui(m,()->{if(q.getFirstVisiblePosition()<1)throw new IllegalStateException("Queue did not scroll internally");if(m.pages[3].getScrollY()!=before[0])throw new IllegalStateException("Page stole internal queue gesture");q.setSelectionFromTop(q.getCount()-3,0);});frames(m);ui(m,()->{if(q.canScrollVertically(1))throw new IllegalStateException("Test list not at bottom");before[0]=m.pages[3].getScrollY();});drag(m,q,true);ui(m,()->{if(m.pages[3].getScrollY()<=before[0])throw new IllegalStateException("Bottom edge did not hand off to page");q.setSelectionFromTop(0,0);m.pages[3].scrollTo(0,anchor[0]);});frames(m);ui(m,()->{m.pages[3].scrollTo(0,anchor[0]);});frames(m);ui(m,()->{before[0]=m.pages[3].getScrollY();});drag(m,q,false);ui(m,()->{if(m.pages[3].getScrollY()>=before[0])throw new IllegalStateException("Top edge did not hand off to page: before="+before[0]+" after="+m.pages[3].getScrollY()+" first="+q.getFirstVisiblePosition());});
        ui(m,()->{q.setSelectionFromTop(q.getCount()-4,0);m.pages[3].scrollTo(0,anchor[0]);});frames(m);ui(m,()->{before[0]=m.pages[3].getScrollY();});drag(m,q,true);ui(m,()->{if(q.canScrollVertically(1)||m.pages[3].getScrollY()<=before[0])throw new IllegalStateException("Continuous bottom crossing did not scroll page: before="+before[0]+" after="+m.pages[3].getScrollY()+" first="+q.getFirstVisiblePosition()+" top="+q.getChildAt(0).getTop());q.setSelectionFromTop(1,0);m.pages[3].scrollTo(0,anchor[0]);});frames(m);ui(m,()->before[0]=m.pages[3].getScrollY());drag(m,q,false);ui(m,()->{if(q.canScrollVertically(-1)||m.pages[3].getScrollY()>=before[0])throw new IllegalStateException("Continuous top crossing did not scroll page: before="+before[0]+" after="+m.pages[3].getScrollY()+" first="+q.getFirstVisiblePosition()+" top="+q.getChildAt(0).getTop());});
        report.append("PASS: all queue heights are 1/4 to 1/3 of usable screen; exactly 3 complete rows; single-line middle ellipsis\n");report.append("PASS: real touch gestures scroll inside queue and hand off to page at both edges, including continuous gestures crossing an edge\n");
        ui(m,()->{for(MainActivity.State state:new ArrayList<>(m.queues.keySet())){state.entries.clear();state.selected=0;m.refreshQueue(state);}m.showPage(0);});}
    static void findPositions(View view,List<Widgets.PositionSpinner> out){if(view instanceof Widgets.PositionSpinner)out.add((Widgets.PositionSpinner)view);if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)findPositions(group.getChildAt(i),out);}}
    static void positionTests(MainActivity m,StringBuilder report)throws Exception{ArrayList<Widgets.PositionSpinner> menus=new ArrayList<>();ui(m,()->{for(ScrollView page:m.pages)if(page!=null)findPositions(page,menus);if(menus.size()!=3)throw new IllegalStateException("Missing shared position menus: "+menus.size());m.showPage(0);Widgets.PositionSpinner menu=menus.get(0);Rect rect=new Rect();menu.getDrawingRect(rect);m.pages[0].offsetDescendantRectToMyCoords(menu,rect);m.pages[0].scrollTo(0,rect.top-m.dp(16));menu.performClick();});frames(m);Widgets.PositionSpinner menu=menus.get(0);ui(m,()->{ListView list=menu.popup.getListView();if(list.getChildCount()!=3)throw new IllegalStateException("Position menu must show 3 rows, found "+list.getChildCount());if(list.getChildAt(0).getTop()<0||list.getChildAt(2).getBottom()>list.getHeight())throw new IllegalStateException("Clipped position menu row");list.setSelectionFromTop(7,0);});frames(m);ui(m,()->{ListView list=menu.popup.getListView();if(list.getLastVisiblePosition()!=9)throw new IllegalStateException("Cannot reach final position option");list.performItemClick(list.getChildAt(2),9,9);if(menu.getSelectedItemPosition()!=9||menu.popup.isShowing())throw new IllegalStateException("Position selection failed");menu.setSelection(0);m.pages[0].scrollTo(0,0);});report.append("PASS: all 3 cover-position menus use a scrollable 3-row popup; final option selectable\n");}
    static void editorTap(MainActivity m)throws Exception{ui(m,()->{Widgets.Editor v=m.editor;long now=SystemClock.uptimeMillis();float x=v.left()+60*v.scale(),y=v.top()+48*v.scale();MotionEvent down=MotionEvent.obtain(now,now,MotionEvent.ACTION_DOWN,x,y,0),up=MotionEvent.obtain(now,now+20,MotionEvent.ACTION_UP,x,y,0);v.dispatchTouchEvent(down);v.dispatchTouchEvent(up);down.recycle();up.recycle();});}
    static void paintGateTests(MainActivity m,StringBuilder report)throws Exception{
        int[] start={0};ui(m,()->{m.showPage(5);Bitmap image=Bitmap.createBitmap(120,96,Bitmap.Config.ARGB_8888);image.eraseColor(Color.GREEN);m.editor.set(image);m.editor.rectangle=false;Rect rect=new Rect();m.editor.getDrawingRect(rect);m.pages[5].offsetDescendantRectToMyCoords(m.editor,rect);m.pages[5].scrollTo(0,rect.top-m.dp(8));});frames(m);ui(m,()->{start[0]=m.pages[5].getScrollY();if(m.editor.paintReady())throw new IllegalStateException("Canvas should initially be protected");});drag(m,m.editor,true);ui(m,()->{if(m.pages[5].getScrollY()<=start[0])throw new IllegalStateException("Locked canvas prevented page scrolling");int[] pixels=new int[120*96];m.editor.mask.getPixels(pixels,0,120,0,0,120,96);for(int color:pixels)if(color!=0)throw new IllegalStateException("Page scrolling painted on canvas");});
        Thread.sleep(1200);ui(m,()->{if(m.editor.paintReady())throw new IllegalStateException("Painting unlocked before 2 seconds");m.pages[5].scrollBy(0,-m.dp(3));});frames(m);Thread.sleep(1000);ui(m,()->{if(m.editor.paintReady())throw new IllegalStateException("New scroll did not restart 2-second timer");});editorTap(m);ui(m,()->{if(m.editor.mask.getPixel(60,48)!=0)throw new IllegalStateException("Locked canvas accepted a brush tap");});
        Thread.sleep(1150);frames(m);ui(m,()->{if(!m.editor.paintReady())throw new IllegalStateException("Painting did not resume after 2 seconds idle");});editorTap(m);ui(m,()->{if(m.editor.mask.getPixel(60,48)==0)throw new IllegalStateException("Ready canvas cannot paint");m.pages[5].scrollBy(0,-m.dp(3));if(m.editor.paintReady())throw new IllegalStateException("Page scroll did not lock painting again");m.editor.clear();});report.append("PASS: page scrolling through canvas leaves mask empty; full 2-second idle gate restarts after new movement; paint resumes and locks again after scrolling\n");
    }
    static void redactionTests(MainActivity m,File dir,Files.Job job,StringBuilder report)throws Exception {
        Bitmap fixture=Bitmap.createBitmap(120,96,Bitmap.Config.ARGB_8888);int[] pixels=new int[120*96];for(int i=0;i<pixels.length;i++)pixels[i]=0xff000000|((i*76379)^0x43547a)&0xffffff;fixture.setPixels(pixels,0,120,0,0,120,96);
        File png=new File(dir,"redact-input.png"),jpg=new File(dir,"redact-input.jpg");Images.encode(fixture,png,0,job);Images.encode(fixture,jpg,95,job);fixture.recycle();
        int cases=0;for(int type=0;type<4;type++)for(int effect=0;effect<3;effect++)for(int shape=0;shape<2;shape++) {
            Bitmap source=Images.load(type==1?jpg:png,0,true);if(type==2)source.setHasAlpha(false);if(type==3){source.setHasAlpha(true);for(int y=0;y<96;y++)for(int x=0;x<120;x++)if(x<20)source.setPixel(x,y,0);else if(x>100)source.setPixel(x,y,0x805ca632);}
            final Bitmap input=source;final int mode=effect,selection=shape;int[] original=new int[pixels.length],mask=new int[pixels.length];source.getPixels(original,0,120,0,0,120,96);
            ui(m,()->{m.showPage(5);m.editor.set(input);m.editor.effect=mode;m.editor.strength=12;Paint brush=new Paint(Paint.ANTI_ALIAS_FLAG);brush.setColor(Color.WHITE);if(selection==0)m.editor.maskCanvas.drawCircle(60,48,24,brush);else m.editor.maskCanvas.drawRect(36,24,84,72,brush);m.editor.mask.getPixels(mask,0,120,0,0,120,96);});
            Bitmap result=m.editor.apply(job);try {
                if(result.getWidth()!=120||result.getHeight()!=96)throw new IOException("Redaction cropped canvas");int[] edited=new int[pixels.length];result.getPixels(edited,0,120,0,0,120,96);int changed=0;
                for(int i=0;i<edited.length;i++){if((mask[i]>>>24)==0&&edited[i]!=original[i])throw new IOException("Redaction erased outside selection: type="+type+", effect="+effect+", shape="+shape+", pixel="+i+", original="+Integer.toHexString(original[i])+", result="+Integer.toHexString(edited[i]));if(edited[i]!=original[i])changed++;}
                if(changed==0)throw new IOException("Redaction effect missing");if(effect==2&&result.getPixel(60,48)!=Color.BLACK)throw new IOException("Black cover missing");
                File output=new File(dir,"redact-result-"+type+"-"+effect+"-"+shape+".png");Images.encode(result,output,0,job);Bitmap decoded=Images.load(output,0,true);try{int[] saved=new int[pixels.length];decoded.getPixels(saved,0,120,0,0,120,96);if(!Arrays.equals(edited,saved))throw new IOException("Saved redaction pixels differ from full canvas");}finally{decoded.recycle();}
                ui(m,()->{m.editor.commitEffect(result);m.editor.undo();int[] undone=new int[pixels.length];m.editor.image.getPixels(undone,0,120,0,0,120,96);if(!Arrays.equals(original,undone))throw new IllegalStateException("Redaction undo differs from original");});cases++;
            } finally {if(result!=m.editor.image&&result!=m.editor.undo&&!result.isRecycled())result.recycle();}
        }
        report.append("PASS: ").append(cases).append(" redaction cases (decoded PNG/JPG, opaque bitmap, transparent image; mosaic/blur/cover; brush/rectangle) preserve every outside pixel, full-canvas PNG export, and undo\n");
    }
    static void run(MainActivity m,File dir,Files.Job job)throws Exception{StringBuilder report=new StringBuilder();List<Long> warm=new ArrayList<>();for(int round=0;round<5;round++)for(int page=0;page<8;page++){final int id=page;CountDownLatch drawn=new CountDownLatch(1);long[] start={0},duration={0};m.ui.post(()->{start[0]=SystemClock.uptimeMillis();m.showPage(id);m.root.postOnAnimation(()->m.root.postOnAnimation(()->{duration[0]=SystemClock.uptimeMillis()-start[0];drawn.countDown();}));});if(!drawn.await(10,TimeUnit.SECONDS))throw new IOException("Page switch timed out");if(round==0)report.append("First page ").append(page).append(": ").append(duration[0]).append(" ms\n");else warm.add(duration[0]);}
        Collections.sort(warm);report.append("Warm switches: n=").append(warm.size()).append(", median=").append(warm.get(warm.size()/2)).append(" ms, p95=").append(warm.get((int)(warm.size()*.95))).append(" ms, max=").append(warm.get(warm.size()-1)).append(" ms\n");report.append("Runtime heap limit: ").append(Runtime.getRuntime().maxMemory()/1048576).append(" MiB\n");
        queueTests(m,dir,report);positionTests(m,report);redactionTests(m,dir,job,report);paintGateTests(m,report);
        ui(m,()->{m.showPage(5);Bitmap b=Bitmap.createBitmap(180,180,Bitmap.Config.ARGB_8888);b.eraseColor(0xff27a26c);m.editor.set(b);m.editor.maskCanvas.drawRect(60,60,120,120,new Paint(){ {setColor(Color.WHITE);} });m.editor.effect=2;});Bitmap result=m.editor.apply(job);int outside=result.getPixel(10,10),inside=result.getPixel(90,90);if(outside!=0xff27a26c||inside!=Color.BLACK)throw new IOException("Redaction pixels: outside="+Integer.toHexString(outside)+", inside="+Integer.toHexString(inside)+", mask="+Integer.toHexString(m.editor.mask.getPixel(90,90)));ui(m,()->{m.editor.commitEffect(result);m.editor.undo();if(m.editor.image.getPixel(90,90)!=0xff27a26c)throw new IllegalStateException("Undo mismatch");});report.append("PASS: redaction only affects masked pixels; undo restores original\n");
        ui(m,()->{m.showPage(1);MainActivity.State s=m.state[1];s.entries.clear();s.entries.add(new MainActivity.Entry(new File(dir,"原图.png")));s.selected=0;m.refreshQueue(s);m.busy=false;m.scheduleScramble(false);});long deadline=SystemClock.uptimeMillis()+10000;String[] size={""};while(SystemClock.uptimeMillis()<deadline){ui(m,()->size[0]=m.scrambleSize.getText().toString());if(size[0].contains("KiB")||size[0].contains("MiB"))break;Thread.sleep(50);}if(!size[0].contains("KiB")&&!size[0].contains("MiB"))throw new IOException("First single import did not compute size: "+size[0]);report.append("PASS: first single import automatically computes actual encoded size\n");
        ui(m,()->{m.english=true;m.prefs.edit().putString("language","en").apply();m.rebuild();m.showPage(7);m.drawer();});Thread.sleep(100);ui(m,()->{int width=m.overlay.getChildAt(0).getWidth(),screen=m.root.getWidth()-m.root.getPaddingLeft()-m.root.getPaddingRight();if(width>=screen*.5||width<screen*.3)throw new IllegalStateException("Drawer width invalid");m.closeDrawer();m.english=false;m.prefs.edit().putString("language","zh").apply();m.rebuild();m.showPage(0);});report.append("PASS: English/Chinese switching and adaptive drawer width 30–50 percent\n");
        File original=new File(dir,"原图.png");Files.Job storageJob=new Files.Job();android.net.Uri saved=Storage.save(m,original,"安卓验证",true,"",storageJob);File albumCopy=new File(dir,"album-copy.png");try(InputStream in=m.getContentResolver().openInputStream(saved);OutputStream out=new FileOutputStream(albumCopy)){Files.copy(in,out,storageJob);}if(!Files.hash(original,storageJob).equals(Files.hash(albumCopy,storageJob)))throw new IOException("Album changed image bytes");android.net.Uri saved2=Storage.save(m,original,"安卓验证",true,"",storageJob);if(saved.equals(saved2))throw new IOException("Album duplicate overwrote output");report.append("PASS: gallery save preserves all file bytes and duplicate names do not overwrite\n");
        File shared=Files.unique(m.outputDir,"分享样本.png");try(InputStream in=new FileInputStream(original);OutputStream out=new FileOutputStream(shared)){Files.copy(in,out,storageJob);}File shareCopy=new File(dir,"share-copy.png");try(InputStream in=m.getContentResolver().openInputStream(Storage.shareUri(shared));OutputStream out=new FileOutputStream(shareCopy)){Files.copy(in,out,storageJob);}if(!Files.hash(original,storageJob).equals(Files.hash(shareCopy,storageJob)))throw new IOException("Share provider changed image");report.append("PASS: private content provider returns exact shared file bytes\n");
        ui(m,()->{MainActivity.State s=m.state[0];s.entries.clear();s.entries.add(new MainActivity.Entry(original));s.selected=0;m.featureOutputs.put(MainActivity.FOLDERS[0],Collections.singletonList(shared));m.lastOutputs=Collections.singletonList(shared);m.rebuild();m.showPage(0);});
        report.append("UI TESTS PASS\n");try(OutputStream out=new FileOutputStream(new File(dir,"ui-performance.txt"))){out.write(report.toString().getBytes(Files.UTF8));}}
}
