using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;

namespace QQImageSwitch
{
    static class QrTests
    {
        static void Require(bool value,string message){if(!value)throw new Exception("QR/text/history: "+message);}
        public static void Run(string folder)
        {
            CameraCaptureTests.Run();
            var paperProfile=new BackgroundRevealAuto.Profile{WhiteLow=0,WhiteHigh=255,WhiteFloor=190};
            for(int gray=0;gray<256;gray++){int cover=unchecked((int)0xff000000)|gray<<16|gray<<8|gray;
                int ink=QrService.OptimizePixel(cover,true,paperProfile),space=QrService.OptimizePixel(cover,false,paperProfile);
                foreach(int bg in new[]{245,250,255}){int ai=(int)((uint)ink>>24),aspace=(int)((uint)space>>24);int vi=((ink&255)*ai+bg*(255-ai)+127)/255,vs=((space&255)*aspace+bg*(255-aspace)+127)/255;Require(Math.Abs(vi-vs)<=(bg==250?1:3),"QR leakage on near-white background");}
            }
            string dir=Path.Combine(folder,"qr");Directory.CreateDirectory(dir);string url="https://www.pixiv.net/artworks/123456789";
            var names=new CoverTextOptions{Text="First text"};using(var selector=new TextLayerSelector(()=>names,t=>{},()=>{})){Require(selector.TestCaption(0)=="1 · First text","layer title does not show content");selector.RefreshNames(" Changed\n text ");Require(selector.TestCaption(0)=="1 · Changed text"&&names.Text=="First text","live label changed model or lost whitespace normalization");names.Text=new string('A',80);selector.RefreshNames();Require(selector.TestCaption(0).EndsWith("…")&&selector.TestCaption(0).Length<30,"layer caption did not truncate");names.Text="";selector.RefreshNames();Require(selector.TestCaption(0).Length>4,"empty layer name missing");}
            using(var canvas=new CoverCanvas{Size=new Size(500,400),TextPlacement=true})using(var image=new Bitmap(640,480)){canvas.Image=image;int events=0;TextPositionEventArgs last=null;canvas.PositionChanged+=(s,e)=>{events++;last=e;};canvas.TestBurst(new Point(80,80),new Point(390,270),500);Require(events<=3&&last!=null&&last.Finished,"drag burst was not coalesced or final position lost");var expected=canvas.ToImage(new Point(390,270));Require(last.X==(int)Math.Round(expected.X*100/640)&&last.Y==(int)Math.Round(expected.Y*100/480),"coalesced drag changed final coordinates");canvas.Image=null;}
            foreach(string invalid in new[]{"javascript:alert(1)","file:///C:/test","https://user:pass@example.com","not a link"}){bool rejected=false;try{QrService.Website(invalid);}catch(ArgumentException){rejected=true;}Require(rejected,"unsafe link accepted");}
            foreach(string link in new[]{url,"https://example.com/?name=%E6%B5%8B%E8%AF%95&n=1"})using(var code=QrService.Code(link,600)){Require(QrService.Scan(code)==link,"URL QR round trip");code.RotateFlip(RotateFlipType.Rotate90FlipNone);Require(QrService.Scan(code)==link,"rotated import");}
            foreach(int margin in new[]{0,1,4,8,12}){QrRegion qr;using(var code=QrService.Compose(null,url,1024,50,50,50,null,out qr,margin)){Require(qr.Margin==margin&&qr.Size==code.Width&&qr.X==0,"standalone has extra padding");Require(QrService.Scan(code)==url,"adjustable border decode");string f=Path.Combine(dir,"border-"+margin+".png");Codec.SaveAtomic(f,QrService.Tag(Codec.StaticPng(code),qr));Require(QrService.Read(f).Margin==margin,"border metadata lost");}}
            var isolation=new BackgroundRevealAuto.Profile{WhiteLow=0,WhiteHigh=255,BlackLow=0,BlackHigh=255,WhiteFloor=190,BlackCeiling=165,Strength=0};var rng=new Random(7183);for(int i=0;i<6000;i++){int cover=rng.Next(256),hidden=unchecked((int)0xff000000)|rng.Next(0xffffff);int v=BackgroundRevealAuto.Pixel(unchecked((int)0xff000000)|(cover<<16)|(cover<<8)|cover,hidden,isolation),a=(int)((uint)v>>24);int expected=(int)Math.Round(190+60*cover/255.0);foreach(int shift in new[]{16,8,0}){int visible=(((v>>shift)&255)*a+255*(255-a)+127)/255;Require(Math.Abs(visible-expected)<=1,"grayscale cover leaks source");}}
            using(var original=SelfTest.Art(240,180,true))using(var cover=SelfTest.Art(240,180,false)){BackgroundRevealAuto.Profile profile;using(var generated=BackgroundRevealAuto.Compose(cover,original,0,false,85,CancellationToken.None,out profile))using(var decoded=Codec.Decode(BackgroundRevealAuto.Encode(generated,false,profile,CancellationToken.None)))using(var white=DualBlend.Render(decoded,true,CancellationToken.None)){for(int py=0;py<white.Height;py++)for(int px=0;px<white.Width;px++){Color c=cover.GetPixel(px,py);double luma=(299*c.R+587*c.G+114*c.B)/1000.0;int lo=profile.WhiteLow,hi=profile.WhiteHigh;if(hi-lo<16){lo=0;hi=255;}int expected=(int)Math.Round(profile.WhiteFloor+(250-profile.WhiteFloor)*Math.Max(0,Math.Min(1,(luma-lo)/(hi-lo))));Color actual=white.GetPixel(px,py);Require(Math.Abs(actual.R-expected)<=1&&actual.R==actual.G&&actual.R==actual.B,"actual PNG cover isolation");}}}
            var text=new CoverTextOptions{Text="One",Position=3,X=20,Y=15,Color=Color.Red};text.Extra.Add(new CoverTextOptions{Text="Two",Position=3,X=80,Y=85,Color=Color.Blue});var copied=text.Copy();copied.Extra[0].Text="Changed";Require(text.Extra[0].Text=="Two","snapshot aliases layers");var restored=new CoverTextOptions();restored.LoadLayers(text.SaveLayers());Require(restored.Extra.Count==1&&restored.Extra[0].Text=="Two"&&restored.Extra[0].Color.ToArgb()==Color.Blue.ToArgb(),"layer storage");
            string prefPath=Path.Combine(dir,"preferences");var prefs=new ToolPreferences(prefPath);prefs.CoverText=text;prefs.Save();var loaded=new ToolPreferences(prefPath);Require(loaded.CoverText.Text=="One"&&loaded.CoverText.Extra[0].Text=="Two","preferences layers");
            QrRegion r;using(var source=SelfTest.Art(900,700,true))using(var overlay=QrService.Compose(source,url,1024,52,70,70,text,out r))
            {
                Require(QrService.Scan(overlay)==url,"overlay with texts");string file=Path.Combine(dir,"overlay.png");Codec.SaveAtomic(file,QrService.Tag(Codec.StaticPng(overlay),r));var region=QrService.Read(file);Require(region!=null&&region.Url==url&&region.Size==r.Size,"QR metadata");
                foreach(bool custom in new[]{false,true})using(var cover=custom?SelfTest.Art(400,400,false):BackgroundRevealAuto.CreateCover(overlay,640,-1,CancellationToken.None)){BackgroundRevealAuto.Profile profile;using(var combined=BackgroundRevealAuto.Compose(cover,overlay,640,false,85,CancellationToken.None,out profile))using(var before=DualBlend.Render(combined,true,CancellationToken.None)){var optimizedRegion=QrService.Optimize(combined,region,cover,profile,CancellationToken.None);using(var white=DualBlend.Render(combined,true,CancellationToken.None))using(var black=DualBlend.Render(combined,false,CancellationToken.None)){for(int py=0;py<white.Height;py++)for(int px=0;px<white.Width;px++)Require(Math.Abs(white.GetPixel(px,py).R-before.GetPixel(px,py).R)<=6,"QR changed white cover");Require(QrService.Scan(white)==null,"QR visible on white cover");Require(QrService.Scan(black)==url&&QrService.Scan(combined)==url,"automatic black-background decode failed");}string output=Path.Combine(dir,"hidden-"+custom+".png");Codec.SaveAtomic(output,QrService.Tag(BackgroundRevealAuto.Encode(combined,false,profile,CancellationToken.None),optimizedRegion));Require(QrService.Read(output)!=null,"metadata after optimization");using(var encoded=Codec.Load(output))Require(QrService.Scan(encoded)==url,"encoded transparent QR decode failed");}}
                bool refused=false;using(var small=Codec.Fit(overlay,100,78,Color.Black))using(var cover=BackgroundRevealAuto.CreateCover(small,0,-1,CancellationToken.None)){BackgroundRevealAuto.Profile p;using(var b=BackgroundRevealAuto.Compose(cover,small,0,false,85,CancellationToken.None,out p))try{QrService.Optimize(b,region,cover,p,CancellationToken.None);}catch(ArgumentException){refused=true;}}Require(refused,"tiny output accepted");
                byte[] data=File.ReadAllBytes(file);var meta=Codec.Parse(data).First(c=>c.Type=="qrLK");int offset=Find(data,System.Text.Encoding.ASCII.GetBytes("qrLK"));data[offset+8]^=1;File.WriteAllBytes(Path.Combine(dir,"corrupted.png"),data);Require(QrService.Read(Path.Combine(dir,"corrupted.png"))==null,"corrupt metadata accepted");
            }
            using(var b=new Bitmap(48,48))using(var history=new BitmapHistory()){
                using(var g=Graphics.FromImage(b))g.Clear(Color.Red);byte[] first=Codec.StaticPng(b);for(int i=0;i<45;i++){history.Push(b);b.SetPixel(0,0,Color.FromArgb(255,i,20,40));}Require(history.Count==45,"history beyond five steps");byte[] last=Codec.StaticPng(b);Bitmap current=(Bitmap)b.Clone();try{for(int i=0;i<45;i++){var next=history.Move(current,false);current.Dispose();current=next;}Require(Codec.StaticPng(current).SequenceEqual(first),"undo lossless");for(int i=0;i<45;i++){var next=history.Move(current,true);current.Dispose();current=next;}Require(Codec.StaticPng(current).SequenceEqual(last),"redo lossless");var previous=history.Move(current,false);current.Dispose();current=previous;history.Push(current);Require(history.RedoCount==0,"new edit did not invalidate redo");for(int i=0;i<60;i++)history.Push(current);Require(history.Count==50,"history cap");history.Clear();Require(history.Count==0&&history.RedoCount==0,"history cleanup");}finally{current.Dispose();}}
            File.WriteAllText(Path.Combine(dir,"PASS.md"),"QR encode/decode, rotation, URL validation, overlay, hidden-on-white/revealed-on-black appearances, metadata CRC, multilayer snapshots/settings, and 45-step lossless undo/redo passed.");
        }
        static int Find(byte[] data,byte[] value){for(int i=0;i<=data.Length-value.Length;i++){bool match=true;for(int j=0;j<value.Length;j++)if(data[i+j]!=value[j]){match=false;break;}if(match)return i;}throw new Exception("Marker missing");}
    }
}
