package com.guangyingruoshui.imagetools;

import java.io.*;
import java.util.*;
import java.util.zip.CRC32;

final class Archive {
    static final byte[] MAGIC="AIPTFILE".getBytes(Files.LATIN);
    static final String[] EXT={"",".mp4",".zip",".rar",".7z"};
    static class Info {String name,hash,stored;int kind;long length,offset;boolean zip;}
    static int kind(String name)throws IOException{for(int i=1;i<EXT.length;i++)if(Files.ext(name).equals(EXT[i]))return i;throw new IOException("仅支持 MP4、ZIP、RAR、7Z / MP4, ZIP, RAR, 7Z only");}
    static int jpeg(byte[] b,byte[][] record)throws IOException{if(b.length<4||(b[0]&255)!=255||(b[1]&255)!=216)throw new IOException("不是 JPG / Not a JPEG");int p=2;boolean scan=false,frame=false;while(p<b.length){if(scan){while(p<b.length&&(b[p]&255)!=255)p++;p++;while(p<b.length&&(b[p]&255)==255)p++;if(p>=b.length)break;int c=b[p++]&255;if(c==0||(c>=208&&c<=215))continue;p-=2;scan=false;}if(p+2>b.length||(b[p++]&255)!=255)throw new IOException("JPG 标记损坏 / Invalid JPEG marker");while(p<b.length&&(b[p]&255)==255)p++;if(p>=b.length)break;int marker=b[p++]&255;if(marker==217){if(!frame)throw new IOException("没有 JPEG 图像 / Missing JPEG frame");return p;}if(marker==0||marker==216)throw new IOException("JPG 标记无效 / Invalid JPEG marker");if(marker==1||(marker>=208&&marker<=215))continue;if(p+2>b.length)break;int size=(int)Files.be(b,p,2);if(size<2||size>b.length-p)throw new IOException("JPG 封面损坏 / Invalid JPEG cover");if(marker==239&&size>=10&&Files.starts(Arrays.copyOfRange(b,p+2,p+size),MAGIC)){if(record[0]!=null)throw new IOException("重复文件记录 / Duplicate record");record[0]=Arrays.copyOfRange(b,p+2,p+size);}if(marker>=192&&marker<=207&&marker!=196&&marker!=200&&marker!=204)frame=true;p+=size;if(marker==218)scan=true;}throw new IOException("JPG 封面不完整 / Incomplete JPEG cover");}
    static byte[] cover(android.graphics.Bitmap bitmap,File dir,Files.Job job)throws Exception{android.graphics.Bitmap image=bitmap;boolean own=false;try{for(int i=0;i<30;i++){job.check();ByteArrayOutputStream s=new ByteArrayOutputStream();android.graphics.Bitmap white=Images.fit(image,image.getWidth(),image.getHeight(),android.graphics.Color.WHITE);try{white.compress(android.graphics.Bitmap.CompressFormat.JPEG,95,s);}finally{white.recycle();}if(s.size()<=512*1024)return s.toByteArray();android.graphics.Bitmap next=android.graphics.Bitmap.createScaledBitmap(image,Math.max(1,(int)(image.getWidth()*.8)),Math.max(1,(int)(image.getHeight()*.8)),true);if(own&&next!=image)image.recycle();own=next!=bitmap;image=next;}throw new IOException("封面过大 / Cover too large");}finally{if(own)image.recycle();}}
    static byte[] record(Info info)throws Exception{byte[] name=Files.name(info.name).getBytes(Files.UTF8),b=new byte[60+name.length+(info.zip?33:0)];System.arraycopy(MAGIC,0,b,0,8);b[8]=(byte)(info.zip?2:1);b[9]=(byte)info.kind;Files.le(b,10,name.length,2);Files.le(b,12,info.length,8);Files.le(b,20,info.offset,8);System.arraycopy(Files.unhex(info.hash),0,b,28,32);System.arraycopy(name,0,b,60,name.length);if(info.zip){b[60+name.length]=1;System.arraycopy(Files.unhex(info.stored),0,b,61+name.length,32);}return b;}
    static Info header(RandomAccessFile s)throws Exception{s.seek(0);byte[] b=Files.read(s,(int)Math.min(s.length(),512*1024+2048));byte[][] m={null};int end=jpeg(b,m);b=m[0];if(b==null)throw new IOException("无文件记录，请保存原图 / No record; save original image");if(b.length<60||(b[8]!=1&&b[8]!=2)||b[9]<1||b[9]>4)throw new IOException("文件记录无效 / Invalid file record");int n=(int)Files.le(b,10,2);if(n<1||n>1024||b.length!=60+n+(b[8]==2?33:0))throw new IOException("文件记录长度无效 / Invalid record length");Info i=new Info();i.kind=b[9];i.name=Files.name(new String(b,60,n,Files.UTF8));i.length=Files.le(b,12,8);i.offset=Files.le(b,20,8);i.hash=Files.hex(Arrays.copyOfRange(b,28,60));i.zip=b[8]==2;i.stored=i.zip?Files.hex(Arrays.copyOfRange(b,61+n,93+n)):i.hash;if(i.zip&&(i.kind!=2||b[60+n]!=1))throw new IOException("ZIP 记录无效 / Invalid ZIP record");if(!Files.ext(i.name).equals(EXT[i.kind])||i.length<=0||i.offset!=end||i.length!=s.length()-i.offset)throw new IOException("封装长度或类型不匹配 / Invalid packaged length or type");return i;}
    static File pack(byte[] cover,File source,String originalName,File dir,Files.Job job)throws Exception{int k=kind(originalName);if(originalName.toLowerCase(Locale.ROOT).matches(".*\\.part\\d+\\.rar"))throw new IOException("不支持分卷 / Split archives unsupported");byte[][] old={null};if(cover.length>512*1024||jpeg(cover,old)!=cover.length||old[0]!=null)throw new IOException("封面必须是完整 JPG / Invalid cover");Info i=new Info();i.kind=k;i.name=Files.name(originalName);i.length=source.length();i.zip=k==2;i.hash=i.stored=String.format(Locale.ROOT,"%064d",0);byte[] m=record(i);i.offset=cover.length+m.length+4;m=record(i);Files.space(dir,i.offset+i.length);File out=Files.unique(dir,Files.stem(originalName)+(k==1?"_v2i":"_a2i")+".jpg"),tmp=Files.temp(dir);try(RandomAccessFile in=new RandomAccessFile(source,"r");RandomAccessFile o=new RandomAccessFile(tmp,"rw")){validate(in,k,job);o.write(cover,0,2);o.writeByte(255);o.writeByte(239);o.writeShort(m.length+2);o.write(m);o.write(cover,2,cover.length-2);in.seek(0);try(OutputStream stream=new OutputStream(){public void write(int b)throws IOException{o.write(b);}public void write(byte[] b,int p,int n)throws IOException{o.write(b,p,n);}}){i.hash=Files.hash(in,i.length,stream,job);}o.seek(34);o.write(Files.unhex(i.hash));if(i.zip){zipOffsets(o,i.offset,i.length,i.offset,job);o.seek(i.offset);i.stored=Files.hash(o,i.length,null,job);o.seek(67+i.name.getBytes(Files.UTF8).length);o.write(Files.unhex(i.stored));}o.getFD().sync();}catch(Exception e){tmp.delete();throw e;}try{try(RandomAccessFile check=new RandomAccessFile(tmp,"r")){Info r=header(check);check.seek(r.offset);if(!Files.hash(check,r.length,null,job).equals(r.stored))throw new IOException("写入校验失败 / Write verification failed");}Files.commit(tmp,out,job);return out;}finally{tmp.delete();}}
    static File restore(File input,File dir,Files.Job job)throws Exception{File tmp=Files.temp(dir);try(RandomAccessFile s=new RandomAccessFile(input,"r")){Info i=header(s);Files.space(dir,i.length);File out=Files.unique(dir,i.name);s.seek(i.offset);try(OutputStream o=new FileOutputStream(tmp)){if(!Files.hash(s,i.length,o,job).equals(i.stored))throw new IOException("文件损坏，SHA-256 不一致 / Checksum mismatch");}if(i.zip)try(RandomAccessFile o=new RandomAccessFile(tmp,"rw")){zipOffsets(o,0,i.length,-i.offset,job);}if(!Files.hash(tmp,job).equals(i.hash))throw new IOException("原文件校验失败 / Original checksum mismatch");try(RandomAccessFile o=new RandomAccessFile(tmp,"r")){validate(o,i.kind,job);}Files.commit(tmp,out,job);return out;}finally{tmp.delete();}}
    static void patch(RandomAccessFile f,long at,long value,long delta,int bytes)throws Exception{if(delta==0)return;if((delta<0&&value< -delta)||(delta>0&&value>Long.MAX_VALUE-delta))throw new IOException("ZIP 偏移溢出 / ZIP offset overflow");value+=delta;if(bytes==4&&value>=0xffffffffL)throw new IOException("ZIP32 超出范围，请使用 ZIP64 / ZIP32 overflow");byte[] b=new byte[bytes];Files.le(b,0,value,bytes);f.seek(at);f.write(b);}
    static void zipOffsets(RandomAccessFile s,long start,long length,long delta,Files.Job job)throws Exception{long shift=delta<0?-delta:0;int tail=(int)Math.min(65557,length);s.seek(start+length-tail);byte[] b=Files.read(s,tail);int end=-1;for(int p=b.length-22;p>=0;p--)if(Files.le(b,p,4)==0x06054b50L&&p+22+Files.le(b,p+20,2)==b.length){end=p;break;}if(end<0)throw new IOException("ZIP 结尾无效 / Invalid ZIP footer");long e=start+length-tail+end,entries=Files.le(b,end+10,2),cd=Files.le(b,end+16,4),size=Files.le(b,end+12,4);if(Files.le(b,end+4,2)!=0||Files.le(b,end+6,2)!=0||Files.le(b,end+8,2)!=entries)throw new IOException("不支持分卷 ZIP / Split ZIP unsupported");if(entries==65535||cd==0xffffffffL||size==0xffffffffL){Files.range(e-20,20,s.length());s.seek(e-20);byte[] loc=Files.read(s,20);if(Files.le(loc,0,4)!=0x07064b50L||Files.le(loc,4,4)!=0||Files.le(loc,16,4)!=1)throw new IOException("ZIP64 记录无效 / Invalid ZIP64 locator");long z=Files.le(loc,8,8)-shift;Files.range(z,56,length);s.seek(start+z);byte[] h=Files.read(s,56);if(Files.le(h,0,4)!=0x06064b50L||Files.le(h,16,4)!=0||Files.le(h,20,4)!=0)throw new IOException("ZIP64 无效 / Invalid ZIP64 header");entries=Files.le(h,32,8);cd=Files.le(h,48,8);size=Files.le(h,40,8);patch(s,e-12,Files.le(loc,8,8),delta,8);patch(s,start+z+48,cd,delta,8);}if(Files.le(b,end+16,4)!=0xffffffffL)patch(s,e+16,Files.le(b,end+16,4),delta,4);cd-=shift;Files.range(cd,size,length);if(entries>1000000)throw new IOException("ZIP 条目过多 / Too many ZIP entries");long at=start+cd,stop=at+size;for(long i=0;i<entries;i++){job.check();Files.range(at-start,46,length);s.seek(at);byte[] h=Files.read(s,46);if(Files.le(h,0,4)!=0x02014b50L||Files.le(h,34,2)!=0)throw new IOException("ZIP 目录无效 / Invalid ZIP directory");int name=(int)Files.le(h,28,2),extra=(int)Files.le(h,30,2),comment=(int)Files.le(h,32,2);long local=Files.le(h,42,4);if(local!=0xffffffffL)patch(s,at+42,local,delta,4);else{s.seek(at+46+name);byte[] x=Files.read(s,extra);boolean found=false;for(int p=0;p+4<=x.length;){int tag=(int)Files.le(x,p,2),n=(int)Files.le(x,p+2,2);p+=4;if(n>x.length-p)throw new IOException("ZIP64 扩展损坏 / Invalid ZIP64 extra");if(tag==1){int q=p;if(Files.le(h,24,4)==0xffffffffL)q+=8;if(Files.le(h,20,4)==0xffffffffL)q+=8;if(q+8>p+n)throw new IOException("ZIP64 偏移缺失 / Missing ZIP64 offset");patch(s,at+46+name+q,Files.le(x,q,8),delta,8);found=true;break;}p+=n;}if(!found)throw new IOException("ZIP64 扩展缺失 / Missing ZIP64 extra");}at+=46L+name+extra+comment;if(at>stop)throw new IOException("ZIP 目录越界 / ZIP directory overflow");}if(at!=stop)throw new IOException("ZIP 目录长度无效 / ZIP directory length mismatch");}
    static long vint(byte[] b,int[] p)throws IOException{long v=0;for(int i=0;i<9;i++){if(p[0]>=b.length)throw new EOFException();int c=b[p[0]++]&255;v|=(long)(c&127)<<(i*7);if((c&128)==0)return v;}throw new IOException("RAR 整数溢出 / RAR integer overflow");}
    static long crc(byte[] b,int p,int n){CRC32 c=new CRC32();c.update(b,p,n);return c.getValue();}
    static void validate(RandomAccessFile s,int kind,Files.Job job)throws Exception{s.seek(0);if(s.length()<8)throw new IOException("文件过短 / File too short");if(kind==1){boolean ftyp=false,moov=false,mdat=false;int count=0;while(s.getFilePointer()<s.length()){job.check();if(++count>100000)throw new IOException("MP4 数据块过多 / Too many MP4 atoms");long at=s.getFilePointer();byte[] h=Files.read(s,8);long n=Files.be(h,0,4);int head=8;String type=new String(h,4,4,Files.LATIN);if(n==1){n=Files.be(Files.read(s,8),0,8);head=16;}if(n==0)n=s.length()-at;if(n<head)throw new IOException("MP4 长度无效 / Invalid MP4 atom");Files.range(at,n,s.length());if(type.equals("ftyp")&&n>=head+8)ftyp=true;if(type.equals("moov"))moov=true;if(type.equals("mdat"))mdat=true;s.seek(at+n);}if(!ftyp||!moov||!mdat)throw new IOException("MP4 不完整 / Incomplete MP4");}
        else if(kind==2){s.seek(0);long sig=Files.le(Files.read(s,4),0,4);if(sig!=0x04034b50L&&sig!=0x06054b50L)throw new IOException("ZIP 文件头无效 / Invalid ZIP signature");zipOffsets(s,0,s.length(),0,job);}
        else if(kind==4){s.seek(0);byte[] h=Files.read(s,32);if(!Files.starts(h,new byte[]{55,122,(byte)188,(byte)175,39,28})||crc(h,12,20)!=Files.le(h,8,4))throw new IOException("7Z 文件头无效 / Invalid 7Z header");long at=Files.le(h,12,8),n=Files.le(h,20,8);if(at>Long.MAX_VALUE-32)throw new IOException("7Z 偏移溢出 / 7Z offset overflow");at+=32;Files.range(at,n,s.length());s.seek(at);CRC32 c=new CRC32();byte[] b=new byte[65536];while(n>0){job.check();int size=(int)Math.min(n,b.length);s.readFully(b,0,size);c.update(b,0,size);n-=size;}if(c.getValue()!=Files.le(h,28,4))throw new IOException("7Z 校验失败 / 7Z checksum mismatch");}
        else {s.seek(0);byte[] sig=Files.read(s,7);if(!Files.starts(sig,new byte[]{82,97,114,33,26,7})||(sig[6]!=0&&sig[6]!=1))throw new IOException("RAR 文件头无效 / Invalid RAR header");boolean five=sig[6]==1,main=false,ended=false;if(five&&s.read()!=0)throw new IOException("RAR5 文件头无效 / Invalid RAR5 header");int blocks=0;while(s.getFilePointer()<s.length()){job.check();if(++blocks>1000000)throw new IOException("RAR 数据块过多 / Too many RAR blocks");long n=0;if(!five){byte[] first=Files.read(s,7);int size=(int)Files.le(first,5,2),flags=(int)Files.le(first,3,2),type=first[2]&255;if(size<7)throw new IOException("RAR4 头损坏 / Invalid RAR4 header");byte[] h=Files.concat(first,Files.read(s,size-7));if((crc(h,2,h.length-2)&65535)!=Files.le(h,0,2))throw new IOException("RAR4 校验失败 / RAR4 CRC mismatch");if(type==0x73){if((flags&1)!=0)throw new IOException("不支持分卷 RAR / Split RAR unsupported");main=true;if((flags&128)!=0)return;}if((flags&0x8000)!=0)n=Files.le(h,7,4);if(type==0x74){if((flags&3)!=0)throw new IOException("不支持分卷 RAR / Split RAR unsupported");if((flags&0x100)!=0)n=Files.le(h,32,4)<<32|Files.le(h,7,4);}if(type==0x7b){if((flags&1)!=0)throw new IOException("不支持分卷 RAR / Split RAR unsupported");ended=true;}}
            else{byte[] checksum=Files.read(s,4);ByteArrayOutputStream len=new ByteArrayOutputStream();int v;do{v=s.read();if(v<0||len.size()>=3)throw new IOException("RAR5 长度无效 / Invalid RAR5 length");len.write(v);}while((v&128)!=0);int[] p={0};long size=vint(len.toByteArray(),p);if(size<2||size>2*1024*1024)throw new IOException("RAR5 头过大 / RAR5 header too large");byte[] b=Files.read(s,(int)size),all=Files.concat(len.toByteArray(),b);if(crc(all,0,all.length)!=Files.le(checksum,0,4))throw new IOException("RAR5 校验失败 / RAR5 CRC mismatch");p[0]=0;long type=vint(b,p),flags=vint(b,p);if((flags&1)!=0)vint(b,p);if((flags&2)!=0)n=vint(b,p);if((flags&24)!=0)throw new IOException("不支持分卷 RAR / Split RAR unsupported");if(type==1){if((vint(b,p)&1)!=0)throw new IOException("不支持分卷 RAR / Split RAR unsupported");main=true;}if(type==4)return;if(type==5){if((vint(b,p)&1)!=0)throw new IOException("不支持分卷 RAR / Split RAR unsupported");ended=true;}}
            Files.range(s.getFilePointer(),n,s.length());s.seek(s.getFilePointer()+n);if(ended)break;}if(!main||(!ended&&five))throw new IOException("RAR 不完整 / Incomplete RAR");}s.seek(0);}
}
