package com.guangyingruoshui.imagetools;

import org.json.*;
import java.util.*;
import java.util.regex.*;
import java.io.*;

final class Comfy {
    final JSONObject graph;int visited;HashSet<String> path=new HashSet<>();
    Comfy(JSONObject g){graph=g;}
    static String key(String s){return s.toLowerCase(Locale.ROOT).replaceAll("[\\s_\\-]+","");}
    static int polarity(String s){String k=key(s);if(k.equals("conditioning")&&s.trim().endsWith("-"))return -1;if(k.contains("negative")||k.contains("negprompt")||k.equals("neg")||k.startsWith("negcond")||k.contains("负面")||k.contains("负向"))return -1;if(k.contains("positive")||k.contains("posprompt")||k.equals("pos")||k.startsWith("poscond")||k.contains("正面")||k.contains("正向")||k.equals("conditioning+"))return 1;return 0;}
    static boolean role(String s,boolean negative){return polarity(s)==(negative?-1:1)&&!key(s).matches(".*(strength|weight|normalization|interpretation|score|balance|style).*");}
    static Object roleInput(JSONObject inputs,boolean negative){Object v=inputs.opt(negative?"negative":"positive");if(v!=null&&v!=JSONObject.NULL)return v;Iterator<String> keys=inputs.keys();while(keys.hasNext()){String k=keys.next();if(role(k,negative)&&inputs.opt(k)!=JSONObject.NULL)return inputs.opt(k);}return null;}
    static boolean pipeline(String s){String k=key(s);return k.matches(".*(pipe|context|bundle).*|sdxltuple");}
    static boolean textKey(String s){String k=key(s);return k.matches("clipl|clipg|t5xxl|.*text.*|.*prompt.*|string.*|content|caption|.*提示词.*|.*文本.*");}
    static boolean excluded(String s){String k=key(s);return k.matches("model|clip|vae|.*image.*|pixels|.*latent.*|.*mask.*|.*controlnet.*|.*filename.*|.*path.*|.*ckpt.*|.*loraname.*|.*modelname.*|seed|noiseseed|mode|action|operation|.*sampler.*|.*scheduler.*|.*weight.*|.*strength.*|.*normalization.*|.*interpretation.*|.*style.*|separator|delimiter|deliminator|joinwith|format|outputprefix");}
    String link(Object value){if(!(value instanceof JSONArray))return null;JSONArray a=(JSONArray)value;return a.length()==2&&graph.has(String.valueOf(a.opt(0)))?String.valueOf(a.opt(0)):null;}
    static boolean parameter(String s){return s.matches("(?i)enable|disable|enabled|disabled|fixed|populate|reproduce|randomize|increment|decrement|normal|default|none|cpu|cuda|auto")||s.matches("(?i).*\\.(safetensors|ckpt|gguf|pth|pt)$");}
    String read(Object value,boolean negative)throws Exception{visited=0;path.clear();return walk(value,negative,false,0);}
    String walk(Object value,boolean negative,boolean textContext,int depth)throws Exception{if(value instanceof String)return (String)value;if(value==null||value==JSONObject.NULL||depth>96||++visited>10000)return "";if(value instanceof JSONObject){Object selected=roleInput((JSONObject)value,negative);return selected==null?"":walk(selected,negative,textContext,depth+1);}String id=link(value);if(id==null)return "";JSONObject node=graph.optJSONObject(id);if(node==null)return "";JSONObject inputs=node.optJSONObject("inputs");if(inputs==null)return "";String type=node.optString("class_type");int port=((JSONArray)value).optInt(1),outRole=0;JSONArray names=node.optJSONArray("_output_names");if(names!=null&&port<names.length())outRole=polarity(names.optString(port));if(outRole==0){if(type.startsWith("ControlNetApply")&&(port==0||port==1))outRole=port==0?1:-1;if(type.startsWith("Efficient Loader")&&(port==1||port==2))outRole=port==1?1:-1;if(type.startsWith("easy ")&&type.toLowerCase(Locale.ROOT).contains("loader")&&(port==4||port==5))outRole=port==4?1:-1;}if(outRole!=0)negative=outRole<0;String token=id+":"+port+":"+negative+":"+textContext;if(!path.add(token))return "";try{if(type.equals("ConditioningZeroOut"))return "[ConditioningZeroOut: branch zeroed]";if(negative&&type.toLowerCase(Locale.ROOT).contains("guider")&&inputs.has("conditioning")&&roleInput(inputs,true)==null)return "";ArrayList<Object> selected=new ArrayList<>();Iterator<String> keys=inputs.keys();while(keys.hasNext()){String k=keys.next();if(role(k,negative))selected.add(inputs.opt(k));}if(!selected.isEmpty())return combine(selected,negative,true,depth,"\n",true);
        for(String k:new String[]{"populated_text","processed_text","resolved_text","output_text","result_text","evaluated_text"})if(inputs.has(k)){String actual=walk(inputs.opt(k),negative,true,depth+1);if(!actual.isEmpty())return actual;}
        ArrayList<String> fields=new ArrayList<>();keys=inputs.keys();while(keys.hasNext()){String k=keys.next();Object v=inputs.opt(k);if(!excluded(k)&&!pipeline(k)&&polarity(k)==0&&textKey(k)&&(v instanceof String||link(v)!=null))fields.add(k);}
        if(fields.isEmpty()){ArrayList<String> literals=new ArrayList<>();keys=inputs.keys();while(keys.hasNext()){String k=keys.next();Object v=inputs.opt(k);if(!excluded(k)&&polarity(k)==0&&v instanceof String&&!parameter((String)v))literals.add(k);}boolean textNode=Pattern.compile("text|string|prompt|wildcard|encoder|encode|primitive|文本|提示",Pattern.CASE_INSENSITIVE).matcher(type).find();if(textContext||textNode||literals.size()==1){fields.addAll(literals);keys=inputs.keys();while(keys.hasNext()){String k=keys.next();if(!excluded(k)&&polarity(k)==0&&link(inputs.opt(k))!=null&&!pipeline(k)&&!fields.contains(k))fields.add(k);}}}
        if(!fields.isEmpty()){boolean join=Pattern.compile("concat|join|拼接|连接|append",Pattern.CASE_INSENSITIVE).matcher(type).find();String separator=join?"":"\n";if(join)for(String k:new String[]{"delimiter","separator","deliminator","join_with"})if(inputs.opt(k) instanceof String){separator=inputs.getString(k);break;}ArrayList<Object> values=new ArrayList<>();for(String k:fields)values.add(inputs.opt(k));String text=combine(values,negative,true,depth,separator,!join);if(!text.isEmpty())return text;}
        ArrayList<Object> branches=new ArrayList<>();keys=inputs.keys();while(keys.hasNext()){String k=keys.next();if(!excluded(k)&&polarity(k)==0&&link(inputs.opt(k))!=null)branches.add(inputs.opt(k));}return combine(branches,negative,textContext,depth,"\n",true);
        }finally{path.remove(token);}}
    String combine(List<Object> values,boolean negative,boolean context,int depth,String separator,boolean distinct)throws Exception{ArrayList<String> parts=new ArrayList<>();int length=0;for(Object value:values){String s=walk(value,negative,context,depth+1);if(s.isEmpty()||distinct&&parts.contains(s))continue;length+=s.length()+separator.length();if(length>Metadata.LIMIT)throw new IOException("提示词过大 / Prompt too large");parts.add(s);}StringBuilder text=new StringBuilder();for(String part:parts){if(text.length()>0)text.append(separator);text.append(part);}return text.toString();}
    static String precise(String s){StringBuilder out=new StringBuilder(s.length());boolean quoted=false,escape=false;for(int i=0;i<s.length();){char c=s.charAt(i);if(quoted){out.append(c);i++;if(escape)escape=false;else if(c=='\\')escape=true;else if(c=='"')quoted=false;continue;}if(c=='"'){quoted=true;out.append(c);i++;continue;}if(c=='-'||c>='0'&&c<='9'){int start=i++;while(i<s.length()&&s.charAt(i)>='0'&&s.charAt(i)<='9')i++;if(i-start>=16&&(i==s.length()||s.charAt(i)!='.'&&s.charAt(i)!='e'&&s.charAt(i)!='E'))out.append('"').append(s,start,i).append('"');else out.append(s,start,i);continue;}out.append(c);i++;}return out.toString();}
    static JSONObject workflow(JSONObject wf)throws Exception{JSONObject g=new JSONObject();JSONArray nodes=wf.optJSONArray("nodes"),links=wf.optJSONArray("links");Map<String,JSONArray> connections=new HashMap<>();if(links!=null)for(int i=0;i<links.length();i++){Object v=links.opt(i);JSONArray link=v instanceof JSONArray?(JSONArray)v:null;if(v instanceof JSONObject){JSONObject n=(JSONObject)v;link=new JSONArray().put(n.opt("id")).put(n.opt("origin_id")).put(n.opt("origin_slot"));}if(link!=null&&link.length()>=3)connections.put(String.valueOf(link.opt(0)),new JSONArray().put(String.valueOf(link.opt(1))).put(link.opt(2)));}if(nodes==null)return g;if(nodes.length()>10000)throw new IOException("工作流节点过多 / Too many workflow nodes");for(int i=0;i<nodes.length();i++){JSONObject n=nodes.optJSONObject(i);if(n==null)continue;String type=n.optString("type");JSONObject inputs=new JSONObject();JSONArray pins=n.optJSONArray("inputs"),widgets=n.optJSONArray("widgets_values"),outputs=n.optJSONArray("outputs"),names=new JSONArray();if(pins!=null)for(int p=0;p<pins.length();p++){JSONObject pin=pins.optJSONObject(p);if(pin!=null&&!pin.isNull("link")){JSONArray link=connections.get(String.valueOf(pin.opt("link")));if(link!=null)inputs.put(pin.optString("name"),link);}}if(outputs!=null)for(int p=0;p<outputs.length();p++){JSONObject pin=outputs.optJSONObject(p);names.put(pin==null?"":pin.optString("name"));}JSONObject named=n.optJSONObject("widgets_values");if(named!=null){Iterator<String> keys=named.keys();while(keys.hasNext()){String k=keys.next();if(!inputs.has(k))inputs.put(k,named.opt(k));}}
        String[] known=null;switch(type){case "KSampler":known=widgets!=null&&widgets.opt(1) instanceof String?new String[]{"seed","control_after_generate","steps","cfg","sampler_name","scheduler","denoise"}:new String[]{"seed","steps","cfg","sampler_name","scheduler","denoise"};break;case "KSamplerAdvanced":known=new String[]{"add_noise","noise_seed","control_after_generate","steps","cfg","sampler_name","scheduler","start_at_step","end_at_step","return_with_leftover_noise"};break;case "CLIPTextEncode":known=new String[]{"text"};break;case "CLIPTextEncodeSDXL":known=new String[]{"width","height","crop_w","crop_h","target_width","target_height","text_g","text_l"};break;case "CLIPTextEncodeFlux":known=new String[]{"clip_l","t5xxl","guidance"};break;case "CLIPTextEncodeSD3":known=new String[]{"clip_l","clip_g","t5xxl","empty_padding"};break;case "FluxGuidance":known=new String[]{"guidance"};break;case "CheckpointLoaderSimple":known=new String[]{"ckpt_name"};break;case "VAELoader":known=new String[]{"vae_name"};break;case "UNETLoader":known=new String[]{"unet_name","weight_dtype"};break;case "LoraLoader":known=new String[]{"lora_name","strength_model","strength_clip"};break;case "EmptyLatentImage":known=new String[]{"width","height","batch_size"};break;case "CFGGuider":known=new String[]{"cfg"};break;case "BasicScheduler":known=new String[]{"scheduler","steps","denoise"};break;case "KSamplerSelect":known=new String[]{"sampler_name"};break;case "RandomNoise":known=new String[]{"noise_seed","control_after_generate"};break;}
        if(widgets!=null){if(known!=null){for(int p=0;p<widgets.length()&&p<known.length;p++)if(!inputs.has(known[p]))inputs.put(known[p],widgets.opt(p));}else{if(widgets.length()==1&&widgets.opt(0) instanceof String&&outputs!=null){for(int p=0;p<outputs.length();p++){JSONObject pin=outputs.optJSONObject(p);if(pin!=null&&pin.optString("type").equals("STRING"))inputs.put("text",widgets.opt(0));}}inputs.put("原始 widgets_values",widgets);}}g.put(String.valueOf(n.opt("id")),new JSONObject().put("class_type",type).put("inputs",inputs).put("_output_names",names));}return g;}
    static void parse(JSONObject graph,JSONObject wf,Metadata.Result result)throws Exception{if(graph.optJSONObject("prompt")!=null)graph=graph.optJSONObject("prompt");if(graph.length()>10000)throw new IOException("节点过多 / Too many nodes");if(wf!=null){JSONObject supplemental=workflow(wf);Iterator<String> ids=graph.keys();while(ids.hasNext()){String id=ids.next();JSONObject node=graph.optJSONObject(id),extra=supplemental.optJSONObject(id);if(node!=null&&extra!=null&&node.optString("class_type").equals(extra.optString("class_type"))){node.put("_output_names",extra.optJSONArray("_output_names"));JSONObject inputs=node.optJSONObject("inputs"),fallback=extra.optJSONObject("inputs");if(inputs!=null&&fallback!=null){Iterator<String> keys=fallback.keys();while(keys.hasNext()){String k=keys.next();if(!inputs.has(k)&&!(fallback.opt(k) instanceof JSONArray))inputs.put(k,fallback.opt(k));}}}}}
        Comfy reader=new Comfy(graph);Iterator<String> ids=graph.keys();while(ids.hasNext()){String id=ids.next();JSONObject node=graph.optJSONObject(id);if(node==null)continue;JSONObject inputs=node.optJSONObject("inputs");if(inputs==null)continue;String type=node.optString("class_type");boolean branch=false;Iterator<String> keys=inputs.keys();while(keys.hasNext()){String k=keys.next();if(polarity(k)!=0||pipeline(k)||k.matches("guider|latent_image|conditioning|prompt|text"))branch=true;}if(!branch||!(type.toLowerCase(Locale.ROOT).contains("sampler")||inputs.has("steps")&&inputs.has("cfg")&&(inputs.has("seed")||inputs.has("noise_seed"))))continue;Object positive=roleInput(inputs,false),negative=roleInput(inputs,true);for(String k:new String[]{"conditioning","prompt","text","guider"})if(positive==null)positive=inputs.opt(k);if(negative==null)negative=inputs.opt("guider");keys=inputs.keys();while(keys.hasNext()){String k=keys.next();if(pipeline(k)){if(positive==null)positive=inputs.opt(k);if(negative==null)negative=inputs.opt(k);}}
        LinkedHashMap<String,String> fields=new LinkedHashMap<>();fields.put("采样节点 / Sampler node",id+" · "+type);fields.put("正面 tag / Positive tag",reader.read(positive,false));fields.put("负面 tag / Negative tag",reader.read(negative,true));Set<String> seen=new HashSet<>();ArrayDeque<String> pending=new ArrayDeque<>();pending.add(id);while(!pending.isEmpty()&&seen.size()<2048&&fields.size()<500){String current=pending.remove();if(!seen.add(current))continue;JSONObject ni=Metadata.in(graph,current);keys=ni.keys();while(keys.hasNext()){String k=keys.next();Object v=ni.opt(k);String link=reader.link(v);if(link!=null){pending.add(link);continue;}if(role(k,false)||role(k,true))continue;String label=fields.containsKey(k)?current+" · "+k:k;fields.put(label,v==null||v==JSONObject.NULL?"":String.valueOf(v));if(fields.size()>=500)break;}}result.comfy.add(fields);if(result.comfy.size()>=100)break;}if(!result.prompt.isEmpty()||!result.workflow.isEmpty()){LinkedHashMap<String,String> raw=new LinkedHashMap<>();if(!result.prompt.isEmpty())raw.put("原始 prompt JSON",result.prompt);if(!result.workflow.isEmpty())raw.put("原始 workflow JSON",result.workflow);result.comfy.add(raw);}}
}
