package com.guangyingruoshui.imagetools;

import android.graphics.*;
import org.json.JSONObject;
import java.io.*;
import java.util.*;
import java.util.zip.*;

final class Images {
    static Bitmap load(File f,int bound,boolean exact)throws IOException{
        BitmapFactory.Options b=new BitmapFactory.Options();b.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getPath(),b);if(b.outWidth<=0||b.outHeight<=0)throw new IOException("图片无法解码 / Cannot decode image");
        long pixels=(long)b.outWidth*b.outHeight,budget=Math.min(192L*1024*1024,Runtime.getRuntime().maxMemory()*2/3);if(exact&&pixels>budget/20)throw new IOException("原图超出手机内存预算，请降低尺寸或在电脑处理 / Image exceeds memory budget");
        b.inJustDecodeBounds=false;b.inPreferredConfig=Bitmap.Config.ARGB_8888;b.inMutable=true;b.inSampleSize=1;
        if(!exact)while(Math.max(b.outWidth,b.outHeight)/b.inSampleSize>bound*2||(pixels/(b.inSampleSize*(long)b.inSampleSize))*8>budget)b.inSampleSize*=2;
        Bitmap result=BitmapFactory.decodeFile(f.getPath(),b);if(result==null)throw new IOException("无法读取图片 / Cannot read image");
        if(!exact&&Math.max(result.getWidth(),result.getHeight())>bound){float scale=bound/(float)Math.max(result.getWidth(),result.getHeight());Bitmap resized=Bitmap.createScaledBitmap(result,Math.max(1,Math.round(result.getWidth()*scale)),Math.max(1,Math.round(result.getHeight()*scale)),true);if(resized!=result)result.recycle();result=resized;}int orientation=Metadata.imageOrientation(f);if(orientation>1){Matrix matrix=new Matrix();switch(orientation){case 2:matrix.setScale(-1,1);break;case 3:matrix.setRotate(180);break;case 4:matrix.setScale(1,-1);break;case 5:matrix.setRotate(90);matrix.postScale(-1,1);break;case 6:matrix.setRotate(90);break;case 7:matrix.setRotate(90);matrix.postScale(1,-1);break;case 8:matrix.setRotate(270);break;}Bitmap oriented=Bitmap.createBitmap(result,0,0,result.getWidth(),result.getHeight(),matrix,true);if(oriented!=result)result.recycle();result=oriented;}return result;
    }
    static Bitmap fit(Bitmap src,int w,int h,int background){Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(background);float s=Math.min(w/(float)src.getWidth(),h/(float)src.getHeight());float rw=src.getWidth()*s,rh=src.getHeight()*s;c.drawBitmap(src,null,new RectF((w-rw)/2,(h-rh)/2,(w+rw)/2,(h+rh)/2),new Paint(3));return b;}
    static Bitmap defaultCover(int size){return defaultCover(size,false);}
    static Bitmap defaultCover(int size,boolean english){Bitmap b=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint p=new Paint(3);p.setShader(new LinearGradient(0,0,size,size,new int[]{0xff9078d5,0xffe3a9d0},null,Shader.TileMode.CLAMP));c.drawRect(0,0,size,size,p);p.setShader(null);p.setColor(Color.WHITE);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(size*(english?.054f:.072f));p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText(english?"View original image":"点击查看原图",size/2f,size*.51f,p);return b;}
    static void annotate(Bitmap b,String text,int position,float x,float y,int percent,int color,boolean numbered,int number){Canvas c=new Canvas(b);Paint p=new Paint(3);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(Math.max(12,Math.min(b.getWidth(),b.getHeight())*percent/100f));p.setColor(color);p.setShadowLayer(Math.max(1,p.getTextSize()/15),1,1,0x90000000);
        if(text!=null&&!text.isEmpty()){String[] lines=text.split("\n",-1);float width=0;for(String line:lines)width=Math.max(width,p.measureText(line));float height=lines.length*p.getFontSpacing(),pad=Math.max(8,p.getTextSize()*.6f),tx,ty;
            if(position>0){int row=(position-1)/3,col=(position-1)%3;tx=col==0?pad:col==1?(b.getWidth()-width)/2:b.getWidth()-width-pad;ty=row==0?pad:row==1?(b.getHeight()-height)/2:b.getHeight()-height-pad;}
            else {tx=x/100*(b.getWidth()-width);ty=y/100*(b.getHeight()-height);}
            tx=Math.max(0,Math.min(tx,b.getWidth()-width));ty=Math.max(0,ty);for(int i=0;i<lines.length;i++)c.drawText(lines[i],tx,ty-p.ascent()+i*p.getFontSpacing(),p);
        }
        if(numbered){float radius=Math.max(16,Math.min(b.getWidth(),b.getHeight())*.045f),cx=b.getWidth()-radius*1.3f,cy=b.getHeight()-radius*1.3f;p.clearShadowLayer();p.setColor(0xff806bc4);c.drawCircle(cx,cy,radius,p);p.setColor(Color.WHITE);p.setTextSize(radius*1.2f);p.setTextAlign(Paint.Align.CENTER);c.drawText(String.valueOf(number),cx,cy-(p.ascent()+p.descent())/2,p);}
    }
    static void pngData(Bitmap b,File z,Files.Job j)throws Exception{try(OutputStream raw=new FileOutputStream(z);DeflaterOutputStream out=new DeflaterOutputStream(raw,new Deflater(6),65536)){int w=b.getWidth();int[] row=new int[w];byte[] rgba=new byte[w*4],prev=new byte[w*4],sub=new byte[w*4],up=new byte[w*4];for(int y=0;y<b.getHeight();y++){j.check();b.getPixels(row,0,w,0,y,w,1);for(int x=0;x<w;x++){int v=row[x],p=x*4;rgba[p]=(byte)(v>>>16);rgba[p+1]=(byte)(v>>>8);rgba[p+2]=(byte)v;rgba[p+3]=(byte)(v>>>24);}long ns=0,ss=0,us=0;for(int p=0;p<rgba.length;p++){sub[p]=(byte)((rgba[p]&255)-(p<4?0:rgba[p-4]&255));up[p]=(byte)((rgba[p]&255)-(prev[p]&255));ns+=Math.abs((int)rgba[p]);ss+=Math.abs((int)sub[p]);us+=Math.abs((int)up[p]);}byte[] best=rgba;int filter=0;if(ss<ns){best=sub;filter=1;ns=ss;}if(us<ns){best=up;filter=2;}out.write(filter);out.write(best);System.arraycopy(rgba,0,prev,0,rgba.length);}}}
    static byte[] ihdr(int w,int h){return Files.concat(Files.be(w,h),new byte[]{8,6,0,0,0});}
    static byte[] frame(long seq,int w,int h,int blend){return Files.concat(Files.be(seq,w,h,0,0),new byte[]{0,10,0,100,0,(byte)blend});}
    static long pieces(OutputStream o,String type,File z,long seq,Files.Job j)throws Exception{try(InputStream s=new FileInputStream(z)){byte[] buf=new byte[65536];int n;while((n=s.read(buf))!=-1){j.check();byte[] b=Arrays.copyOf(buf,n);Files.chunk(o,type,type.equals("fdAT")?Files.concat(Files.be(seq++),b):b);}}return seq;}
    static void dual(Bitmap cover,Bitmap real,File out,Files.Job j)throws Exception{File a=Files.temp(out.getParentFile()),b=Files.temp(out.getParentFile());try{pngData(cover,a,j);pngData(real,b,j);try(OutputStream s=new BufferedOutputStream(new FileOutputStream(out))){s.write(Files.PNG);Files.chunk(s,"IHDR",ihdr(real.getWidth(),real.getHeight()));Files.chunk(s,"acTL",Files.be(2,0));Files.chunk(s,"tEXt","ChatBarApngDisguise\u00001;STATIC;1".getBytes(Files.LATIN));pieces(s,"IDAT",a,0,j);Files.chunk(s,"fcTL",frame(0,real.getWidth(),real.getHeight(),0));long seq=pieces(s,"fdAT",b,1,j);Files.chunk(s,"fcTL",frame(seq++,1,1,1));ByteArrayOutputStream dummy=new ByteArrayOutputStream();try(DeflaterOutputStream d=new DeflaterOutputStream(dummy)){d.write(new byte[5]);}Files.chunk(s,"fdAT",Files.concat(Files.be(seq),dummy.toByteArray()));Files.chunk(s,"IEND",new byte[0]);}}finally{a.delete();b.delete();}}
    static void encode(Bitmap b,File f,int quality,Files.Job j)throws Exception{j.check();try(OutputStream s=new BufferedOutputStream(new FileOutputStream(f))){if(quality<=0){File z=Files.temp(f.getParentFile());try{pngData(b,z,j);s.write(Files.PNG);Files.chunk(s,"IHDR",ihdr(b.getWidth(),b.getHeight()));pieces(s,"IDAT",z,0,j);Files.chunk(s,"IEND",new byte[0]);}finally{z.delete();}}else{Bitmap white=fit(b,b.getWidth(),b.getHeight(),Color.WHITE);try{if(!white.compress(Bitmap.CompressFormat.JPEG,quality,s))throw new IOException("编码失败 / Encoding failed");}finally{white.recycle();}}}j.check();}
    // Gilbert traversal: BSD-2-Clause, Copyright (c) 2018 Jakub Červený.
    static final class Curve {int[] map;int index,width;Files.Job job;Curve(int w,int h,Files.Job j)throws Exception{map=new int[w*h];width=w;job=j;if(w>=h)generate(0,0,w,0,0,h);else generate(0,0,0,h,w,0);if(index!=map.length)throw new IOException("曲线长度无效 / Invalid curve");}
        void generate(int x,int y,int ax,int ay,int bx,int by)throws Exception{job.check();int w=Math.abs(ax+ay),h=Math.abs(bx+by),dx=Integer.signum(ax),dy=Integer.signum(ay),ex=Integer.signum(bx),ey=Integer.signum(by);if(h==1){for(int i=0;i<w;i++){map[index++]=x+y*width;x+=dx;y+=dy;}return;}if(w==1){for(int i=0;i<h;i++){map[index++]=x+y*width;x+=ex;y+=ey;}return;}int a=ax>>1,b=ay>>1,c=bx>>1,d=by>>1;if(2*w>3*h){if((Math.abs(a+b)&1)!=0&&w>2){a+=dx;b+=dy;}generate(x,y,a,b,bx,by);generate(x+a,y+b,ax-a,ay-b,bx,by);}else{if((Math.abs(c+d)&1)!=0&&h>2){c+=ex;d+=ey;}generate(x,y,c,d,a,b);generate(x+c,y+d,ax,ay,bx-c,by-d);generate(x+ax-dx+c-ex,y+ay-dy+d-ey,-c,-d,-(ax-a),-(ay-b));}}}
    static Bitmap transform(Bitmap image,boolean reverse,Files.Job job)throws Exception{int w=image.getWidth(),h=image.getHeight();int[] map=new Curve(w,h,job).map,pixels=new int[w*h];image.getPixels(pixels,0,w,0,0,w,h);int shift=(int)Math.floor((Math.sqrt(5)-1)/2*map.length+.5)%map.length;if(reverse&&shift!=0)shift=map.length-shift;int a=map.length,d=shift;while(d!=0){int v=a%d;a=d;d=v;}int moved=0;for(int start=0;start<a;start++){int at=start,saved=pixels[map[start]];do{if((moved++&65535)==0)job.check();int next=(at+shift)%map.length,idx=map[next],old=pixels[idx];pixels[idx]=saved;saved=old;at=next;}while(at!=start);}image.setPixels(pixels,0,w,0,0,w,h);return image;}
    static File scramble(File input,File dir,boolean reverse,int quality,Files.Job job)throws Exception{return scramble(input,dir,reverse,quality,0,job);}
    static File scramble(File input,File dir,boolean reverse,int quality,int bound,Files.Job job)throws Exception{File out=Files.unique(dir,Files.stem(input.getName())+(reverse?"_解混淆":"_混淆")+(quality>0?".jpg":".png")),tmp=Files.temp(dir);Bitmap image=null;try{image=load(input,reverse?0:bound,reverse||bound==0);transform(image,reverse,job);encode(image,tmp,quality,job);if(quality<0){long imageLength=tmp.length();String imageHash=Files.hash(tmp,job);Files.space(dir,input.length()+8192);try(RandomAccessFile source=new RandomAccessFile(input,"r");FileOutputStream o=new FileOutputStream(tmp,true)){String hash=Files.hash(source,source.length(),o,job);JSONObject r=new JSONObject();r.put("Schema",1);r.put("Name",Files.name(input.getName()));r.put("ImageLength",imageLength);r.put("Length",source.length());r.put("Sha256",hash);r.put("ImageSha256",imageHash);byte[] meta=r.toString().getBytes(Files.UTF8),len=new byte[4];Files.le(len,0,meta.length,4);o.write(meta);o.write(len);o.write("AIPTSCR1".getBytes(Files.LATIN));}}Files.commit(tmp,out,job);return out;}finally{if(image!=null)image.recycle();tmp.delete();}}
    static File restoreOriginal(File input,File dir,Files.Job job)throws Exception{File tmp=Files.temp(dir);try(RandomAccessFile s=new RandomAccessFile(input,"r")){if(s.length()<12)throw new IOException("没有原文件记录 / No original-file record");s.seek(s.length()-12);byte[] tail=Files.read(s,12);if(!Arrays.equals(Arrays.copyOfRange(tail,4,12),"AIPTSCR1".getBytes(Files.LATIN)))throw new IOException("没有原文件记录 / No original-file record");int length=(int)Files.le(tail,0,4);if(length<2||length>8192||length>s.length()-12)throw new IOException("记录损坏 / Invalid record");long start=s.length()-12-length;s.seek(start);JSONObject r=new JSONObject(new String(Files.read(s,length),Files.UTF8));long imageLength=r.getLong("ImageLength"),n=r.getLong("Length");if(r.getInt("Schema")!=1||imageLength<8||n<1||imageLength>start||n!=start-imageLength)throw new IOException("记录长度无效 / Invalid record length");Files.unhex(r.getString("Sha256"));Files.unhex(r.getString("ImageSha256"));File out=Files.unique(dir,r.getString("Name"));Files.space(dir,n);s.seek(0);if(!Files.hash(s,imageLength,null,job).equals(r.getString("ImageSha256")))throw new IOException("图片已被修改 / Image checksum mismatch");try(OutputStream o=new FileOutputStream(tmp)){if(!Files.hash(s,n,o,job).equals(r.getString("Sha256")))throw new IOException("原文件校验失败 / Original checksum mismatch");}Files.commit(tmp,out,job);return out;}finally{tmp.delete();}}
}
