package com.guangyingruoshui.imagetools;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
    static final String[] ZH={"双图切换","图片混淆","文件伪装","合成 GIF","清信息","打码","tag读取","设置"};
    static final String[] EN={"Dual image","Scramble","File disguise","Make GIF","Clean info","Redact","Read tags","Settings"};
    static final String[] FOLDERS={"双图切换","图片混淆","文件伪装","合成GIF","清信息","打码","tag读取",""};
    static class Entry {File file,cover;Entry(File f){file=f;}}
    static class State {ArrayList<Entry> entries=new ArrayList<>();int selected=0;File cover;String text="";boolean numbered=false;int position=0,size=6;float x=50,y=50;int quality=-1,decodeQuality=0,percent=95,decodePercent=95,bound=1200,gifDelay=400,gifSize=480;boolean gifLoop=true;}
    interface Imported {void done(List<File> files);}
    interface Work {List<File> run(Files.Job job)throws Exception;}
    interface Complete {void done(List<File> files);}
    final Handler ui=new Handler(Looper.getMainLooper());final ExecutorService worker=Executors.newSingleThreadExecutor();
    final State[] state={new State(),new State(),new State(),new State(),new State(),new State(),new State(),new State()};
    final State video=new State(),archive=new State(),restoreDual=new State();
    final ArrayList<Spinner> saveModes=new ArrayList<>();final HashMap<String,List<File>> featureOutputs=new HashMap<>();boolean syncingDestinations;SharedPreferences prefs;FrameLayout root,overlay;LinearLayout layout,toolbar,progressBox;TextView title,status;ProgressBar progress;ScrollView[] pages=new ScrollView[8];int page=0;boolean english,busy,destroyed,folderPending,nonMediaPending;volatile Files.Job active,previewJob;int previewVersion;Runnable previewPending;Imported importCallback;List<File> lastOutputs=new ArrayList<>(),waitingOutputs;String lastFeature="";Widgets.Editor editor;File editInput;boolean editorOriginal=true,gifInitialized;int editBound=1200;
    Widgets.Preview scrambleBefore,scrambleAfter;TextView scrambleSize;ListView scrambleQueue;Map<State,ListView> queues=new IdentityHashMap<>();ArrayList<Widgets.Preview> previews=new ArrayList<>();Metadata.Result webInfo,comfyInfo;LinearLayout webFields,comfyFields;File outputDir;
    public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("image-tools",MODE_PRIVATE);english=prefs.getString("language","zh").equals("en");outputDir=new File(getCacheDir(),"share");outputDir.mkdirs();getWindow().setStatusBarColor(0xffeeeaf7);getWindow().setNavigationBarColor(0xfff7f5fb);buildShell();if(b!=null)page=Math.max(0,Math.min(7,b.getInt("page",0)));showPage(page);if(getIntent().getBooleanExtra("selftest",false))runSelfTest();}
    String t(String z,String e){return english?e:z;}int dp(float x){return Widgets.dp(this,x);}TextView label(String text,int size,boolean bold){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(bold?0xff433657:0xff786c8b);v.setPadding(0,dp(4),0,dp(8));if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
    GradientDrawable rounded(int color,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(18));if(stroke!=0)d.setStroke(dp(1),stroke);return d;}
    LinearLayout column(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);return c;}LinearLayout card(LinearLayout body,String title){LinearLayout c=column();c.setPadding(dp(14),dp(12),dp(14),dp(14));c.setBackground(rounded(0xfffdfcff,0xffebe5f5));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));body.addView(c,p);if(!title.isEmpty())c.addView(label(title,18,true));return c;}
    Button button(String name,Runnable action){Button b=new Button(this);b.setText(name);b.setTextSize(14);b.setAllCaps(false);b.setMinHeight(dp(48));b.setMinimumWidth(dp(80));b.setPadding(dp(14),dp(8),dp(14),dp(8));b.setTextColor(0xff614982);b.setBackground(rounded(0xfff0eaf9,0xffe2d9f1));b.setContentDescription(name);b.setOnClickListener(v->{if(!busy)action.run();else toast(t("当前任务运行中，可点击取消","Task running; use Cancel"));});return b;}
    void buttons(LinearLayout c,Button...b){Widgets.Flow flow=new Widgets.Flow(this);for(Button v:b)flow.addView(v,new ViewGroup.LayoutParams(-2,-2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(8));c.addView(flow,p);}
    interface Chosen {void choose(int index);}Spinner spinner(LinearLayout c,String caption,String[] values,int selected,Chosen change){return spinner(c,caption,values,selected,change,false);}Spinner spinner(LinearLayout c,String caption,String[] values,int selected,Chosen change,boolean threeRows){c.addView(label(caption,14,false));Spinner s=threeRows?new Widgets.PositionSpinner(this):new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,values){TextView item(int position,View reuse){TextView v=reuse instanceof TextView?(TextView)reuse:label("",14,false);v.setText(getItem(position));v.setTextSize(14);v.setSingleLine(threeRows);v.setMaxLines(threeRows?1:Integer.MAX_VALUE);v.setEllipsize(threeRows?android.text.TextUtils.TruncateAt.END:null);v.setMinHeight(dp(48));if(threeRows)v.setHeight(dp(48));v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;}public View getView(int p,View reuse,ViewGroup parent){return item(p,reuse);}public View getDropDownView(int p,View reuse,ViewGroup parent){return item(p,reuse);}};s.setAdapter(adapter);s.setSelection(selected);s.setMinimumHeight(dp(52));c.addView(s,new LinearLayout.LayoutParams(-1,-2));s.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){boolean initialized=false;public void onItemSelected(AdapterView<?> p,View v,int i,long id){if(!initialized){initialized=true;if(i==selected)return;}change.choose(i);}public void onNothingSelected(AdapterView<?> p){}});return s;}
    interface Changed {void value(int value);}SeekBar slider(LinearLayout c,String caption,int min,int max,int initial,Changed change){TextView l=label(caption+": "+initial,14,false);c.addView(l);SeekBar s=new SeekBar(this);s.setMax(max-min);s.setProgress(initial-min);c.addView(s,new LinearLayout.LayoutParams(-1,dp(48)));s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int p,boolean user){l.setText(caption+": "+(p+min));if(user)change.value(p+min);}});return s;}
    CheckBox check(LinearLayout c,String caption,boolean checked,java.lang.Runnable action){CheckBox v=new CheckBox(this);v.setText(caption);v.setTextColor(0xff614982);v.setMinHeight(dp(48));v.setChecked(checked);c.addView(v);v.setOnCheckedChangeListener((b,state)->action.run());return v;}
    void buildShell(){root=new FrameLayout(this);root.setBackgroundColor(0xfff5f2fa);layout=column();root.addView(layout,new FrameLayout.LayoutParams(-1,-1));toolbar=new LinearLayout(this);toolbar.setGravity(Gravity.CENTER_VERTICAL);toolbar.setPadding(dp(4),dp(3),dp(12),dp(3));toolbar.setBackgroundColor(0xfffdfcff);View hamburger=new View(this){Paint p=new Paint(3);protected void onDraw(Canvas c){p.setColor(0xff7b62b0);p.setStrokeWidth(dp(2));for(int y=0;y<3;y++)c.drawLine(dp(14),getHeight()/2f-dp(7)+y*dp(7),dp(34),getHeight()/2f-dp(7)+y*dp(7),p);}};hamburger.setTag("navigation");hamburger.setContentDescription(t("打开功能菜单","Open navigation"));hamburger.setOnClickListener(v->drawer());toolbar.addView(hamburger,new LinearLayout.LayoutParams(dp(48),dp(48)));title=label("",17,true);title.setPadding(dp(4),0,0,0);toolbar.addView(title,new LinearLayout.LayoutParams(0,-2,1));layout.addView(toolbar);progressBox=column();progressBox.setPadding(dp(14),0,dp(14),dp(4));status=label(t("全部在本机处理","All processing stays on this device"),12,false);progressBox.addView(status);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setVisibility(View.GONE);progressBox.addView(progress,new LinearLayout.LayoutParams(-1,dp(4)));Button cancel=new Button(this);cancel.setText(t("取消任务","Cancel task"));cancel.setTextSize(12);cancel.setAllCaps(false);cancel.setOnClickListener(v->{Files.Job j=active;if(j!=null)j.cancelled=true;cancelPreview();});cancel.setVisibility(View.GONE);cancel.setTag("cancel");progressBox.addView(cancel,new LinearLayout.LayoutParams(-1,dp(44)));layout.addView(progressBox);setContentView(root);
        root.setOnApplyWindowInsetsListener((v,insets)->{root.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});root.requestApplyInsets();}
    void drawer(){if(overlay!=null){root.removeView(overlay);overlay=null;return;}overlay=new FrameLayout(this);overlay.setBackgroundColor(0x55000000);overlay.setOnClickListener(v->closeDrawer());root.addView(overlay,new FrameLayout.LayoutParams(-1,-1));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(0xfffbf9ff);scroll.setOnClickListener(v->{});int available=Math.max(dp(240),root.getWidth()-root.getPaddingLeft()-root.getPaddingRight()),width=Math.min((int)(available*.48f),Math.max((int)(available*.38f),dp(104)));FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(width,-1);overlay.addView(scroll,p);LinearLayout menu=column();menu.setPadding(dp(8),dp(14),dp(8),dp(14));scroll.addView(menu);menu.addView(label(t("工具集合","Toolbox"),18,true));for(int i=0;i<8;i++){final int id=i;Button b=button(english?EN[i]:ZH[i],()->{showPage(id);closeDrawer();});b.setOnClickListener(v->{showPage(id);closeDrawer();});b.setTextSize(13);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(5),dp(8),dp(5),dp(8));b.setSingleLine(true);b.addOnLayoutChangeListener((v,l,t,r,bt,ol,ot,or,ob)->{int availableText=b.getWidth()-b.getPaddingLeft()-b.getPaddingRight();float chosen=13;while(chosen>9){b.setTextSize(chosen);if(b.getPaint().measureText(b.getText().toString())<=availableText)break;chosen-=.5f;}b.setTextSize(chosen);});if(android.os.Build.VERSION.SDK_INT>=26){b.setAutoSizeTextTypeUniformWithConfiguration(9,13,1,android.util.TypedValue.COMPLEX_UNIT_SP);}if(i==page)b.setBackground(rounded(0xffdfd3f4,0xffcabbeb));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(50));bp.setMargins(0,0,0,dp(8));menu.addView(b,bp);}}
    void closeDrawer(){if(overlay!=null){root.removeView(overlay);overlay=null;}}
    void showPage(int id){cancelPreview();if(editor!=null)editor.drawing=false;page=id;for(ScrollView p:pages)if(p!=null)p.setVisibility(View.GONE);if(pages[id]==null){Widgets.PageScroll sc=new Widgets.PageScroll(this);sc.moving=()->{if(id==5&&editor!=null)editor.pausePainting();};sc.setFillViewport(false);sc.setClipToPadding(false);sc.setPadding(dp(12),dp(12),dp(12),dp(20));sc.setBackgroundColor(0xfff5f2fa);LinearLayout body=column();sc.addView(body,new ScrollView.LayoutParams(-1,-2));pages[id]=sc;layout.addView(sc,new LinearLayout.LayoutParams(-1,0,1));buildPage(id,body);}pages[id].setVisibility(View.VISIBLE);if(id==5&&editor!=null)editor.pausePainting();title.setText(english?EN[id]:ZH[id]);for(Widgets.Preview p:previews)if(isVisible(p)&&p.image==null&&p.reload!=null)p.reload.run();if(id==1&&state[1].entries.size()>0)scheduleScramble(false);}
    void buildPage(int id,LinearLayout body){body.addView(label(english?EN[id]:ZH[id],25,true));switch(id){case 0:dualPage(body);break;case 1:scramblePage(body);break;case 2:filePage(body);break;case 3:gifPage(body);break;case 4:cleanPage(body);break;case 5:editPage(body);break;case 6:tagPage(body);break;case 7:settingsPage(body);break;}footer(body);}
    void footer(LinearLayout body){LinearLayout save=card(body,t("保存与分享","Save and share"));Spinner destination=spinner(save,t("保存位置（自动记住）","Destination (remembered)"),new String[]{t("保存至相册","Save to album"),t("自定义文件夹","Custom folder")},prefs.getBoolean("album",true)?0:1,i->{if(syncingDestinations)return;prefs.edit().putBoolean("album",i==0).apply();syncDestinations();if(i==1&&prefs.getString("tree","").isEmpty())chooseFolder();});saveModes.add(destination);TextView folder=label(prefs.getString("folderLabel",t("尚未选择自定义文件夹","No custom folder selected")),12,false);save.addView(folder);folder.setTag("folderLabel");buttons(save,button(t("选择文件夹","Choose folder"),this::chooseFolder),button(t("分享文件","Share files"),this::share));save.addView(label(t("记住保存选择；按功能建立子文件夹。分享使用系统菜单，可选择 QQ 等应用。","Remembers destination; outputs use feature subfolders. Share through installed apps such as QQ."),12,false));}
    void syncDestinations(){syncingDestinations=true;try{for(Spinner s:saveModes)s.setSelection(prefs.getBoolean("album",true)?0:1);}finally{syncingDestinations=false;}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}void message(String s){if(!destroyed)status.setText(s);}
    void setBusy(boolean b){busy=b;progress.setVisibility(b?View.VISIBLE:View.GONE);progressBox.findViewWithTag("cancel").setVisibility(b?View.VISIBLE:View.GONE);if(editor!=null)editor.setEnabled(!b);}
    void task(Work work,Complete done){if(busy)return;cancelPreview();Files.Job job=new Files.Job();active=job;job.progress=(d,total)->ui.post(()->{if(active!=job||destroyed)return;progress.setIndeterminate(total<=0);if(total>0)progress.setProgress((int)(d*100.0/total));});releaseHiddenPreviews();setBusy(true);message(t("正在后台处理…","Processing in background…"));worker.execute(()->{List<File> result=null;Throwable error=null;try{result=work.run(job);job.check();}catch(Throwable e){error=e;}final List<File> files=result;final Throwable failure=error;ui.post(()->{if(destroyed)return;active=null;setBusy(false);if(failure!=null){if(files!=null&&!files.isEmpty()&&files.get(0).getParentFile().equals(outputDir)){lastOutputs=new ArrayList<>(files);featureOutputs.put(lastFeature,lastOutputs);}message(error(failure));toast(error(failure));}else{message(t("处理完成","Completed"));if(done!=null)done.done(files);}if(page==1&&state[1].entries.size()>0)scheduleScramble(false);});});}
    String error(Throwable e){if(e instanceof OutOfMemoryError)return t("手机内存不足，请降低尺寸后重试","Insufficient memory; reduce image size");if(e instanceof InterruptedIOException)return t("操作已取消，原文件保留","Cancelled; originals preserved");return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
    void pick(String mime,boolean multiple,Imported callback){importCallback=callback;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,multiple);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivityForResult(i,900);}catch(ActivityNotFoundException e){toast(t("此手机没有文件选择器","No document picker installed"));}}
    void chooseFolder(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);try{startActivityForResult(i,901);}catch(ActivityNotFoundException e){toast(t("此手机没有文件夹选择器","No folder picker installed"));}}
    protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null){if(request==901){waitingOutputs=null;folderPending=false;}return;}if(request==901){Uri uri=data.getData();if(uri==null)return;try{getContentResolver().takePersistableUriPermission(uri,data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));prefs.edit().putString("tree",uri.toString()).putString("folderLabel",Uri.decode(uri.getLastPathSegment())).putBoolean("album",false).apply();for(ScrollView p:pages)if(p!=null){TextView label=p.findViewWithTag("folderLabel");if(label!=null)label.setText(prefs.getString("folderLabel",""));}syncDestinations();if(waitingOutputs!=null){List<File> outputs=waitingOutputs;waitingOutputs=null;folderPending=false;saveOutputs(outputs,lastFeature);}else toast(t("文件夹已记住，保存方式设为自定义文件夹","Folder remembered; destination set to custom folder"));}catch(SecurityException e){waitingOutputs=null;toast(t("文件夹授权失败，请重新选择","Folder permission failed; select again"));}}
        else if(request==900){ArrayList<Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount()&&i<200;i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());Imported callback=importCallback;importCallback=null;task(j->{ArrayList<File> files=new ArrayList<>();try{for(Uri uri:uris){j.check();files.add(Storage.importFile(this,uri,j));}return files;}catch(Exception e){for(File f:files){f.delete();f.getParentFile().delete();}throw e;}},files->{if(callback!=null)callback.done(files);});}}
    void saveOutputs(List<File> outputs,String feature){lastOutputs=new ArrayList<>(outputs);featureOutputs.put(feature,lastOutputs);lastFeature=feature;if(outputs.isEmpty()){message(t("没有可保存的结果","No output files"));return;}boolean album=prefs.getBoolean("album",true);boolean media=true;for(File f:outputs)if(!Storage.mime(f.getName()).startsWith("image/")&&!Storage.mime(f.getName()).startsWith("video/"))media=false;if(album&&!media){waitingOutputs=outputs;new AlertDialog.Builder(this).setMessage(t("本次包含 TXT 或压缩包，不能保存到相册。请选择自定义文件夹；也可稍后直接分享。","This batch includes non-media files. Choose a folder, or share the files directly.")).setPositiveButton(t("选择文件夹","Choose folder"),(d,w)->chooseFolder()).setNegativeButton(t("稍后分享","Share later"),(d,w)->waitingOutputs=null).show();return;}if(!album&&prefs.getString("tree","").isEmpty()){waitingOutputs=outputs;chooseFolder();return;}if(album&&Build.VERSION.SDK_INT>=23&&Build.VERSION.SDK_INT<=28&&checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){waitingOutputs=outputs;requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},902);return;}
        String tree=prefs.getString("tree","");task(j->{ArrayList<String> errors=new ArrayList<>();int n=0;for(File f:outputs){j.check();try{Storage.save(this,f,feature,album,tree,j);n++;}catch(InterruptedIOException e){throw e;}catch(Exception e){errors.add(f.getName()+": "+error(e));}}final int saved=n;ui.post(()->{if(destroyed)return;new AlertDialog.Builder(this).setMessage(t("保存成功 ","Saved ")+saved+" / "+outputs.size()+(errors.isEmpty()?"":"\n"+Metadata.join(errors))).setPositiveButton("OK",null).show();});return outputs;},files->message(t("保存完成，可点击分享文件","Saved; use Share files")));}
    public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(request==902){List<File> files=waitingOutputs;waitingOutputs=null;if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED&&files!=null)saveOutputs(files,lastFeature);else toast(t("未允许写入相册，可改用文件夹或分享","Album permission denied; use a folder or Share"));}}
    void share(){List<File> shareFiles=page==7?lastOutputs:featureOutputs.get(FOLDERS[page]);if(shareFiles==null||shareFiles.isEmpty()){toast(t("请先生成文件","Generate files first"));return;}ArrayList<Uri> uris=new ArrayList<>();String type=null;for(File f:shareFiles){if(!f.isFile())continue;uris.add(Storage.shareUri(f));String mime=Storage.mime(f.getName());if(type==null)type=mime;else if(!type.equals(mime))type="*/*";}if(uris.isEmpty()){toast(t("分享文件已被系统清理，请重新生成","Cached files removed; generate again"));return;}Intent send=new Intent(uris.size()==1?Intent.ACTION_SEND:Intent.ACTION_SEND_MULTIPLE);send.setType(type);if(uris.size()==1)send.putExtra(Intent.EXTRA_STREAM,uris.get(0));else send.putParcelableArrayListExtra(Intent.EXTRA_STREAM,uris);ClipData clip=ClipData.newUri(getContentResolver(),"Image Tools",uris.get(0));for(int i=1;i<uris.size();i++)clip.addItem(new ClipData.Item(uris.get(i)));send.setClipData(clip);send.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(Intent.createChooser(send,t("分享文件","Share files")));}catch(ActivityNotFoundException e){toast(t("没有可接收文件的应用","No app accepts these files"));}}
    Entry current(State s){return s.entries.isEmpty()?null:s.entries.get(Math.max(0,Math.min(s.selected,s.entries.size()-1)));}
    List<Entry> snapshot(State s,boolean all){ArrayList<Entry> r=new ArrayList<>();if(all)r.addAll(s.entries);else if(current(s)!=null)r.add(current(s));return r;}
    ListView queue(LinearLayout c,State s,Runnable changed){Widgets.QueueList list=new Widgets.QueueList(this);list.setChoiceMode(ListView.CHOICE_MODE_SINGLE);list.setDividerHeight(dp(1));list.setBackgroundColor(0xfff7f3fc);c.addView(list,new LinearLayout.LayoutParams(-1,-2));queues.put(s,list);list.setOnItemClickListener((p,v,pos,id)->{s.selected=pos;changed.run();});buttons(c,button(t("移除选中","Remove selected"),()->{if(!s.entries.isEmpty()){s.entries.remove(Math.min(s.selected,s.entries.size()-1));s.selected=Math.max(0,Math.min(s.selected,s.entries.size()-1));refreshQueue(s);changed.run();}}),button(t("清空队列","Clear queue"),()->{s.entries.clear();s.selected=0;refreshQueue(s);changed.run();}),button(t("上移","Move up"),()->{if(s.selected>0){Collections.swap(s.entries,s.selected,s.selected-1);s.selected--;refreshQueue(s);changed.run();}}),button(t("下移","Move down"),()->{if(s.selected+1<s.entries.size()){Collections.swap(s.entries,s.selected,s.selected+1);s.selected++;refreshQueue(s);changed.run();}}));refreshQueue(s);return list;}
    void refreshQueue(State s){Widgets.QueueList q=(Widgets.QueueList)queues.get(s);if(q==null)return;int first=q.getFirstVisiblePosition(),top=q.getChildCount()>0?q.getChildAt(0).getTop():0;ArrayList<String> names=new ArrayList<>(),sizes=new ArrayList<>();for(int i=0;i<s.entries.size();i++){File f=s.entries.get(i).file;names.add((i+1)+". "+f.getName());sizes.add(size(f.length()));}
        BaseAdapter adapter=new BaseAdapter(){public int getCount(){return names.size();}public Object getItem(int position){return names.get(position);}public long getItemId(int position){return position;}
            public View getView(int position,View reuse,ViewGroup parent){LinearLayout row;if(reuse instanceof LinearLayout)row=(LinearLayout)reuse;else{row=column();TextView filename=label("",12,false),bytes=label("",10,false);filename.setSingleLine(true);filename.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);filename.setTypeface(null,Typeface.NORMAL);filename.setTextDirection(View.TEXT_DIRECTION_LTR);filename.setIncludeFontPadding(false);bytes.setSingleLine(true);bytes.setIncludeFontPadding(false);filename.setPadding(0,0,0,0);bytes.setPadding(0,0,0,0);row.addView(filename);row.addView(bytes);android.graphics.drawable.StateListDrawable background=new android.graphics.drawable.StateListDrawable();background.addState(new int[]{android.R.attr.state_activated},new android.graphics.drawable.ColorDrawable(0xffe7ddf7));background.addState(new int[]{},new android.graphics.drawable.ColorDrawable(Color.TRANSPARENT));row.setBackground(background);}
                int height=q.rowHeight>0?q.rowHeight:dp(56);boolean compact=height<dp(44);row.setOrientation(compact?LinearLayout.HORIZONTAL:LinearLayout.VERTICAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(2),dp(10),dp(2));row.setLayoutParams(new AbsListView.LayoutParams(-1,height));TextView filename=(TextView)row.getChildAt(0),bytes=(TextView)row.getChildAt(1);filename.setText(names.get(position));filename.setTextSize(compact?11:12);bytes.setText(sizes.get(position));bytes.setTextSize(compact?9:10);filename.setLayoutParams(new LinearLayout.LayoutParams(compact?0:-1,-2,compact?1:0));bytes.setLayoutParams(new LinearLayout.LayoutParams(compact?-2:-1,-2));if(compact)bytes.setPadding(dp(6),0,0,0);else bytes.setPadding(0,dp(3),0,0);return row;}}
        ;q.setAdapter(adapter);if(!names.isEmpty()){s.selected=Math.max(0,Math.min(s.selected,names.size()-1));q.setItemChecked(s.selected,true);q.setSelectionFromTop(Math.max(0,Math.min(first,names.size()-1)),top);}}

    String size(long n){return n>=1048576?String.format(Locale.ROOT,"%.2f MiB",n/1048576.0):n>=1024?String.format(Locale.ROOT,"%.1f KiB",n/1024.0):n+" B";}
    void importImages(State s,Runnable changed){pick("image/*",true,files->{for(File f:files)s.entries.add(new Entry(f));if(s.entries.size()==files.size())s.selected=0;refreshQueue(s);changed.run();});}
    Widgets.Preview preview(LinearLayout c,String empty){Widgets.Preview p=new Widgets.Preview(this,empty);c.addView(p,new LinearLayout.LayoutParams(-1,-2));previews.add(p);return p;}
    void previewFile(Widgets.Preview v,File f){v.reload=()->previewFile(v,f);int version=++v.ticket;if(f==null){v.set(null);return;}thumbnail(v,()->worker.execute(()->{if(destroyed||version!=v.ticket)return;Bitmap b=null;try{b=Images.load(f,640,false);}catch(Throwable ignored){}final Bitmap result=b;ui.post(()->{if(destroyed||version!=v.ticket){if(result!=null)result.recycle();return;}v.set(result);});}));}
    void thumbnail(Widgets.Preview view,Runnable action){if(view.pending!=null)ui.removeCallbacks(view.pending);view.pending=action;ui.postDelayed(action,150);}
    void textControls(LinearLayout c,State s,Runnable refresh){c.addView(label(t("封面文字","Cover text"),14,false));EditText text=new EditText(this);text.setText(s.text);text.setTextSize(15);text.setHint(t("输入文字；留空则不添加","Enter text; leave empty for none"));text.setMinLines(2);text.setMaxLines(5);c.addView(text,new LinearLayout.LayoutParams(-1,-2));text.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence v,int start,int count,int after){}public void onTextChanged(CharSequence v,int start,int before,int count){s.text=v.toString();}public void afterTextChanged(android.text.Editable e){refresh.run();}});buttons(c,button(t("清空文字","Clear text"),()->text.setText("")));spinner(c,t("文字位置","Text position"),new String[]{t("自由拖动（长按封面）","Free drag (hold cover)"),t("上左","Top left"),t("上中","Top center"),t("上右","Top right"),t("中左","Middle left"),t("正中","Center"),t("中右","Middle right"),t("下左","Bottom left"),t("下中","Bottom center"),t("下右","Bottom right")},s.position,i->{s.position=i;refresh.run();},true);slider(c,t("横向位置 %","Horizontal position %"),0,100,(int)s.x,v->{s.x=v;refresh.run();});slider(c,t("纵向位置 %","Vertical position %"),0,100,(int)s.y,v->{s.y=v;refresh.run();});slider(c,t("文字大小 %","Text size %"),2,20,s.size,v->{s.size=v;refresh.run();});CheckBox numbered=new CheckBox(this);numbered.setText(t("右下角自动编号","Automatic bottom-right numbering"));numbered.setTextSize(14);numbered.setMinHeight(dp(48));numbered.setChecked(s.numbered);c.addView(numbered);numbered.setOnCheckedChangeListener((b,v)->{s.numbered=v;refresh.run();});}
    void coverButtons(LinearLayout c,State s,Runnable update){buttons(c,button(t("选择封面","Choose cover"),()->pick("image/*",false,files->{if(files.isEmpty())return;Entry selected=current(s);if(selected!=null)selected.cover=files.get(0);else s.cover=files.get(0);update.run();})),button(t("封面应用全部","Apply cover to all"),()->{Entry e=current(s);File f=e!=null&&e.cover!=null?e.cover:s.cover;s.cover=f;for(Entry item:s.entries)item.cover=f;update.run();}),button(t("默认封面","Default cover"),()->{Entry e=current(s);if(e!=null)e.cover=null;else s.cover=null;update.run();}));}
    Bitmap makeCover(State s,Entry entry,int w,int h,int index)throws Exception{File file=entry!=null&&entry.cover!=null?entry.cover:s.cover;Bitmap original=file==null?Images.defaultCover(512,english):Images.load(file,1600,false);try{Bitmap cover=Images.fit(original,w,h,prefs.getInt("color",Color.WHITE));Images.annotate(cover,s.text,s.position,s.x,s.y,s.size,Color.WHITE,s.numbered,index+1);return cover;}finally{original.recycle();}}
    State copyOptions(State s){State x=new State();x.cover=s.cover;x.text=s.text;x.position=s.position;x.x=s.x;x.y=s.y;x.size=s.size;x.numbered=s.numbered;return x;}
    void dualPage(LinearLayout body){State s=state[0];LinearLayout c=card(body,t("封面与原图","Cover and original"));Widgets.Preview cover=preview(c,t("封面预览","Cover preview")),original=preview(c,t("原图预览","Original preview"));Runnable update=()->{Entry e=current(s);final State options=copyOptions(s);final int idx=s.selected;int version=++cover.ticket;thumbnail(cover,()->worker.execute(()->{if(destroyed||version!=cover.ticket)return;Bitmap a=null,b=null;try{b=e==null?null:Images.load(e.file,640,false);a=makeCover(options,e,b==null?512:b.getWidth(),b==null?512:b.getHeight(),idx);}catch(Throwable ignored){}final Bitmap ca=a,cb=b;ui.post(()->{if(destroyed||page!=0||version!=cover.ticket){if(ca!=null)ca.recycle();if(cb!=null)cb.recycle();return;}cover.set(ca);original.set(cb);cover.freeText=s.position==0&&!s.text.trim().isEmpty();});}));};cover.reload=update;cover.move=(x,y)->{s.x=x;s.y=y;update.run();};buttons(c,button(t("批量导入原图","Import images"),()->importImages(s,update)));coverButtons(c,s,update);LinearLayout q=card(body,t("图片队列","Image queue"));queue(q,s,update);LinearLayout text=card(body,t("封面设置","Cover settings"));textControls(text,s,update);spinner(text,t("导出尺寸","Output size"),new String[]{"1200 px","2048 px","3200 px",t("原尺寸","Original size")},s.bound==0?3:s.bound==3200?2:s.bound==2048?1:0,i->s.bound=new int[]{1200,2048,3200,0}[i]);buttons(text,button(t("批量导出","Export all"),()->exportDual(s,true,s.bound)),button(t("导出选中","Export selected"),()->exportDual(s,false,s.bound)));LinearLayout restore=card(body,t("还原双图 PNG","Restore dual PNG"));Widgets.Preview rv=preview(restore,t("隐藏图预览","Hidden image preview"));Runnable changed=()->previewFile(rv,current(restoreDual)==null?null:current(restoreDual).file);buttons(restore,button(t("导入双图 PNG","Import dual PNG"),()->importImages(restoreDual,changed)));queue(restore,restoreDual,changed);buttons(restore,button(t("批量还原并导出","Restore and export all"),()->batch(snapshot(restoreDual,true),(entry,j)->Files.dualRestore(entry.file,outputDir,j),FOLDERS[0])));body.addView(label(t("QQ 分享后请保留原图；重新压缩、截图可能丢失隐藏数据。","Preserve original files when sharing. Recompression or screenshots may remove hidden data."),12,false));update.run();}
    interface EntryWork {File run(Entry e,Files.Job j)throws Exception;}
    void batch(List<Entry> entries,EntryWork op,String feature){if(entries.isEmpty()){toast(t("请先导入文件","Import files first"));return;}lastFeature=feature;task(j->{ArrayList<File> out=new ArrayList<>();ArrayList<String> failures=new ArrayList<>();for(Entry e:entries){if(j.cancelled)return out;try{j.check();out.add(op.run(e,j));}catch(InterruptedIOException x){return out;}catch(Exception x){failures.add(e.file.getName()+": "+error(x));}}if(!failures.isEmpty())ui.post(()->{if(!destroyed)new AlertDialog.Builder(this).setMessage(Metadata.join(failures)).setPositiveButton("OK",null).show();});return out;},files->saveOutputs(files,feature));}
    void exportDual(State s,boolean all,int bound){State options=copyOptions(s);List<Entry> entries=snapshot(s,all);final int[] index={all?0:s.selected};batch(entries,(e,j)->{Bitmap real=Images.load(e.file,bound,bound==0),cover=null;File out=Files.unique(outputDir,Files.stem(e.file.getName())+"_双图.png"),tmp=Files.temp(outputDir);try{Files.space(outputDir,(long)real.getWidth()*real.getHeight()*9);cover=makeCover(options,e,real.getWidth(),real.getHeight(),index[0]++);Images.dual(cover,real,tmp,j);Files.commit(tmp,out,j);return out;}finally{real.recycle();if(cover!=null)cover.recycle();tmp.delete();}},FOLDERS[0]);}
    void cancelPreview(){previewVersion++;if(previewPending!=null)ui.removeCallbacks(previewPending);previewPending=null;Files.Job j=previewJob;if(j!=null)j.cancelled=true;previewJob=null;}
    void scramblePage(LinearLayout body){State s=state[1];LinearLayout queueCard=card(body,t("图片队列","Image queue"));buttons(queueCard,button(t("批量导入图片","Import images"),()->importImages(s,()->scheduleScramble(false))));scrambleQueue=queue(queueCard,s,()->scheduleScramble(false));LinearLayout p=card(body,t("图片预览","Image preview"));scrambleBefore=preview(p,t("原图","Original"));scrambleAfter=preview(p,t("混淆结果","Scrambled result"));LinearLayout q=card(body,t("画质与文件大小","Quality and file size"));scrambleSize=label(t("导入图片后自动计算实际输出大小","Actual encoded size is calculated after import"),13,false);q.addView(scrambleSize);spinner(q,t("混淆画布尺寸（原文件仍完整保留）","Scramble canvas (original file stays intact)"),new String[]{t("原尺寸","Original size"),"1200 px","2048 px"},s.bound==0?0:s.bound==1200?1:2,i->{s.bound=i==0?0:i==1?1200:2048;scheduleScramble(false);});String[] quality={t("原图质量（可还原原文件）","Original (restorable file)"),t("无损 PNG（仅像素）","Lossless PNG (pixels)"),t("压缩 JPG","Compressed JPG")};spinner(q,t("混淆质量","Scramble quality"),quality,s.quality<0?0:s.quality==0?1:2,i->{s.quality=i==0?-1:i==1?0:s.percent;scheduleScramble(false);});slider(q,t("JPG 质量 %","JPG quality %"),1,100,s.percent,v->{s.percent=v;if(s.quality>0)s.quality=v;scheduleScramble(false);});spinner(q,t("解混淆质量","Descramble quality"),new String[]{t("无损 PNG","Lossless PNG"),"JPG"},s.decodeQuality==0?0:1,i->{s.decodeQuality=i==0?0:s.decodePercent;scheduleScramble(true);});slider(q,t("解混淆 JPG 质量 %","Descramble JPG quality %"),1,100,s.decodePercent,v->{s.decodePercent=v;if(s.decodeQuality>0)s.decodeQuality=v;scheduleScramble(true);});buttons(q,button(t("预览混淆","Preview scramble"),()->scheduleScramble(false)),button(t("预览解混淆","Preview descramble"),()->scheduleScramble(true)));q.addView(label(t("默认 1200 像素画布适配老手机，可选原尺寸。原图模式附带全部原文件字节，仍可完整还原；JPG 为有损。","Default 1200 px canvas suits older phones; original size is optional. Original mode still preserves and restores all source bytes. JPG is lossy."),12,false));LinearLayout ops=card(body,t("批量处理","Batch actions"));buttons(ops,button(t("批量混淆","Scramble all"),()->scrambleExport(false,true)),button(t("混淆选中","Scramble selected"),()->scrambleExport(false,false)),button(t("批量解混淆","Descramble all"),()->scrambleExport(true,true)),button(t("解混淆选中","Descramble selected"),()->scrambleExport(true,false)),button(t("批量还原原文件","Restore originals"),()->batch(snapshot(s,true),(e,j)->Images.restoreOriginal(e.file,outputDir,j),FOLDERS[1])),button(t("还原选中原文件","Restore selected original"),()->batch(snapshot(s,false),(e,j)->Images.restoreOriginal(e.file,outputDir,j),FOLDERS[1])));}
    void scheduleScramble(boolean reverse){cancelPreview();if(page!=1||scrambleSize==null)return;Entry e=current(state[1]);if(e==null){scrambleSize.setText(t("请导入图片","Import an image"));scrambleBefore.set(null);scrambleAfter.set(null);return;}scrambleSize.setText(t("正在后台计算…","Calculating in background…"));if(busy)return;int version=previewVersion;int quality=reverse?state[1].decodeQuality:state[1].quality;int bound=state[1].bound;previewPending=()->{Files.Job j=new Files.Job();previewJob=j;worker.execute(()->{File result=null;Bitmap original=null,encoded=null;Throwable error=null;try{j.check();original=Images.load(e.file,640,false);result=Images.scramble(e.file,outputDir,reverse,quality,bound,j);encoded=Images.load(result,640,false);j.check();}catch(Throwable x){error=x;}long bytes=result==null?0:result.length();if(result!=null)result.delete();final Bitmap a=original,b=encoded;final Throwable failure=error;ui.post(()->{if(destroyed||version!=previewVersion||page!=1||j.cancelled){if(a!=null)a.recycle();if(b!=null)b.recycle();return;}previewJob=null;scrambleBefore.set(a);scrambleAfter.set(b);scrambleSize.setText(failure==null?t("预览文件大小：","Preview size: ")+size(bytes)+"\n"+t("原文件：","Original: ")+size(e.file.length())+" · "+String.format(Locale.ROOT,"%.2f×",bytes/(double)Math.max(1,e.file.length())):error(failure));});});};ui.postDelayed(previewPending,400);}
    void scrambleExport(boolean reverse,boolean all){State s=state[1];int quality=reverse?s.decodeQuality:s.quality;int bound=s.bound;batch(snapshot(s,all),(e,j)->Images.scramble(e.file,outputDir,reverse,quality,bound,j),FOLDERS[1]);}
    void filePage(LinearLayout body){body.addView(label(t("生成 JPG 后保存原图再还原。MP4 使用一键还原；ZIP 可改后缀打开，RAR 依解压软件，7Z 用一键还原。QQ 图片往返仍需真机验证。","Preserve the original JPG. Restore MP4 with this app. ZIP supports extension changes; RAR depends on the extractor, 7Z uses app restore. QQ roundtrips need device testing."),12,false));fileCard(body,video,true);fileCard(body,archive,false);}
    void fileCard(LinearLayout body,State s,boolean movie){LinearLayout c=card(body,movie?t("视频伪装","Video disguise"):t("压缩包伪装","Archive disguise"));Widgets.Preview p=preview(c,t("封面预览","Cover preview"));Runnable refresh=()->{State options=copyOptions(s);Entry e=current(s);int index=s.selected;int version=++p.ticket;thumbnail(p,()->worker.execute(()->{if(destroyed||version!=p.ticket)return;Bitmap b=null;try{b=makeCover(options,e,640,480,index);}catch(Throwable ignored){}final Bitmap image=b;ui.post(()->{if(destroyed||page!=2||version!=p.ticket){if(image!=null)image.recycle();return;}p.set(image);p.freeText=s.position==0&&!s.text.trim().isEmpty();});}));};p.reload=refresh;p.move=(x,y)->{s.x=x;s.y=y;refresh.run();};coverButtons(c,s,refresh);buttons(c,button(t("批量选择文件","Import files"),()->pick("*/*",true,files->{for(File f:files){String ext=Files.ext(f.getName());if(movie?ext.equals(".mp4"):ext.matches("\\.(zip|rar|7z)"))s.entries.add(new Entry(f));else toast(t("已跳过不支持的文件：","Unsupported file skipped: ")+f.getName());}refreshQueue(s);refresh.run();})));queue(c,s,refresh);textControls(c,s,refresh);buttons(c,button(t("批量生成 JPG","Generate all JPGs"),()->fileExport(s,true)),button(t("生成选中 JPG","Generate selected JPG"),()->fileExport(s,false)),button(t("批量还原文件","Restore files"),()->pick("*/*",true,files->{ArrayList<Entry> list=new ArrayList<>();for(File f:files)list.add(new Entry(f));batch(list,(e,j)->Archive.restore(e.file,outputDir,j),FOLDERS[2]);})));refresh.run();}
    void fileExport(State s,boolean all){State options=copyOptions(s);int[] index={all?0:s.selected};batch(snapshot(s,all),(e,j)->{Bitmap cover=makeCover(options,e,1200,900,index[0]++);try{return Archive.pack(Archive.cover(cover,outputDir,j),e.file,e.file.getName(),outputDir,j);}finally{cover.recycle();}},FOLDERS[2]);}
    void gifPage(LinearLayout body){State s=state[3];LinearLayout c=card(body,t("图片顺序","Frame order"));Widgets.Preview pv=preview(c,t("当前帧预览","Current frame"));Runnable update=()->previewFile(pv,current(s)==null?null:current(s).file);buttons(c,button(t("批量导入图片","Import images"),()->importImages(s,update)));queue(c,s,update);LinearLayout opts=card(body,t("动图设置","Animation settings"));if(!gifInitialized){s.gifDelay=prefs.getInt("gifDelay",400);s.gifSize=prefs.getInt("gifSize",480);s.gifLoop=prefs.getBoolean("loop",true);gifInitialized=true;}int[] delay={s.gifDelay},size={s.gifSize};boolean[] loop={s.gifLoop};slider(opts,t("每帧间隔 ms","Frame interval ms"),20,2000,delay[0],v->{delay[0]=v;s.gifDelay=v;});slider(opts,t("最长边 px","Longest edge px"),100,1024,size[0],v->{size[0]=v;s.gifSize=v;});CheckBox l=new CheckBox(this);l.setText(t("循环播放","Loop animation"));l.setMinHeight(dp(48));l.setChecked(loop[0]);opts.addView(l);l.setOnCheckedChangeListener((b,v)->{loop[0]=v;s.gifLoop=v;});buttons(opts,button(t("生成 GIF","Generate GIF"),()->{ArrayList<File> files=new ArrayList<>();for(Entry e:s.entries)files.add(e.file);int edge=size[0],ms=delay[0];boolean repeat=loop[0];int color=prefs.getInt("color",Color.WHITE);task(j->Collections.singletonList(Gif.encode(files,outputDir,edge,ms,repeat,color,j)),outputs->saveOutputs(outputs,FOLDERS[3]));}));opts.addView(label(t("为老手机控制内存，逐帧编码；GIF 为 256 色。","Encodes one frame at a time for low-memory phones. GIF uses 256 colors."),12,false));}
    void cleanPage(LinearLayout body){State s=state[4];LinearLayout c=card(body,t("清理生成信息","Remove generation metadata"));c.addView(label(t("删除 ComfyUI 工作流与 WebUI tag，不重编码 PNG/JPG/WebP/GIF 图像数据；保留颜色配置。","Removes ComfyUI workflows and WebUI tags without re-encoding PNG/JPG/WebP/GIF image data; preserves color profiles."),13,false));Widgets.Preview p=preview(c,t("原图预览","Original preview"));Runnable update=()->previewFile(p,current(s)==null?null:current(s).file);buttons(c,button(t("批量导入图片","Import images"),()->importImages(s,update)));queue(c,s,update);buttons(c,button(t("批量清理并保存","Clean and save all"),()->batch(snapshot(s,true),(e,j)->Metadata.clean(e.file,outputDir,j),FOLDERS[4])),button(t("清理选中","Clean selected"),()->batch(snapshot(s,false),(e,j)->Metadata.clean(e.file,outputDir,j),FOLDERS[4])));}
    void editPage(LinearLayout body){LinearLayout c=card(body,t("打码工作台","Redaction workspace"));spinner(c,t("编辑尺寸","Working size"),new String[]{"1200 px","2048 px",t("原尺寸（视内存）","Original (memory permitting)")},editBound==0?2:editBound==2048?1:0,i->editBound=i==0?1200:i==1?2048:0);buttons(c,button(t("打开图片","Open image"),()->pick("image/*",false,files->{if(files.isEmpty())return;File f=files.get(0);int limit=editBound;task(j->{Bitmap b=Images.load(f,limit,limit==0);ui.post(()->{if(destroyed){b.recycle();return;}editor.set(b);editInput=f;message(b.getWidth()+" × "+b.getHeight()+t(" · 导出按编辑尺寸"," · Export uses working size"));});return Collections.emptyList();},null);})),button(t("撤销一步","Undo"),()->editor.undo()),button(t("恢复原图","Reset image"),()->{if(editInput!=null){File f=editInput;int limit=editBound;task(j->{Bitmap b=Images.load(f,limit,limit==0);ui.post(()->{if(destroyed)b.recycle();else editor.set(b);});return Collections.emptyList();},null);}}));if(editor==null)editor=new Widgets.Editor(this);c.addView(editor,new LinearLayout.LayoutParams(-1,-2));TextView hint=label("",13,false);hint.setMinLines(2);editor.readinessChanged=()->hint.setText(editor.paintReady()?t("可涂抹：单指绘制，双指缩放和平移。","Ready: one finger paints; two fingers zoom/pan."):t("暂停涂抹：页面静止 2 秒后恢复。","Painting paused: wait 2 seconds after scrolling."));editor.readinessChanged.run();c.addView(hint);spinner(c,t("选区方式","Selection mode"),new String[]{t("涂抹画笔","Brush"),t("框选区域","Rectangle")},editor.rectangle?1:0,i->editor.rectangle=i==1);spinner(c,t("效果","Effect"),new String[]{t("马赛克","Mosaic"),t("模糊","Blur"),t("黑色遮盖","Black cover")},editor.effect,i->{editor.effect=i;editor.invalidate();});slider(c,t("画笔宽度 px","Brush width px"),4,240,editor.brush,v->{editor.brush=v;editor.invalidate();});slider(c,t("效果强度","Strength"),2,64,editor.strength,v->{editor.strength=v;editor.invalidate();});buttons(c,button(t("应用到选区","Apply selection"),()->{if(editor.image==null)return;task(j->{Bitmap result=editor.apply(j);ui.post(()->{if(destroyed){if(result!=null)result.recycle();return;}editor.commitEffect(result);});return Collections.emptyList();},null);}),button(t("清除选区","Clear selection"),()->editor.clear()),button(t("适应窗口","Fit to view"),()->editor.resetView()),button(t("保存打码图片","Save redacted image"),()->{if(editor.image==null)return;Bitmap image=editor.image;task(j->{File out=Files.unique(outputDir,Files.stem(editInput.getName())+"_打码.png"),tmp=Files.temp(outputDir);try{Images.encode(image,tmp,0,j);Files.commit(tmp,out,j);return Collections.singletonList(out);}finally{tmp.delete();}},files->saveOutputs(files,FOLDERS[5]));}));}
    void tagPage(LinearLayout body){webFields=tagCard(body,false);comfyFields=tagCard(body,true);if(webInfo!=null)populateTags(webFields,webInfo,false);if(comfyInfo!=null)populateTags(comfyFields,comfyInfo,true);LinearLayout export=card(body,t("导出参数","Export parameters"));buttons(export,button(t("一键导出 TXT","Export TXT"),()->{Metadata.Result web=webInfo,comfy=comfyInfo;task(j->{ArrayList<File> files=new ArrayList<>();if(web!=null&&!web.web.isEmpty())files.add(txt("WebUI.txt",format(web.web)));if(comfy!=null&&!comfy.comfy.isEmpty()){StringBuilder text=new StringBuilder();for(Map<String,String> fields:comfy.comfy)text.append(format(fields)).append('\n');files.add(txt("ComfyUI.txt",text.toString()));}return files;},files->saveOutputs(files,FOLDERS[6]));}));export.addView(label(t("WebUI 与 ComfyUI 分别导出；未载入或没有信息的不导出。","Exports WebUI and ComfyUI separately; empty or unloaded panels are skipped."),12,false));}
    LinearLayout tagCard(LinearLayout body,boolean comfy){LinearLayout c=card(body,comfy?"ComfyUI":"WebUI");LinearLayout fields=column();buttons(c,button(t("选择图片并读取","Open image and read"),()->pick("image/*",false,files->{if(files.isEmpty())return;File f=files.get(0);task(j->{Metadata.Result result=Metadata.inspect(f,j);ui.post(()->{if(destroyed)return;if(comfy)comfyInfo=result;else webInfo=result;populateTags(fields,result,comfy);});return Collections.emptyList();},null);})));c.addView(fields);fields.addView(label(t("尚未读取图片","No image loaded"),13,false));return fields;}
    void populateTags(LinearLayout body,Metadata.Result r,boolean comfy){body.removeAllViews();if(comfy){if(r.comfy.isEmpty()){body.addView(label(t("未发现 ComfyUI 信息","No ComfyUI information"),13,false));}else{LinearLayout fields=column();String[] samplers=new String[r.comfy.size()];for(int i=0;i<samplers.length;i++)samplers[i]=r.comfy.get(i).containsKey("采样节点 / Sampler node")?r.comfy.get(i).get("采样节点 / Sampler node"):t("原始 JSON","Raw JSON");Spinner selected=spinner(body,t("选择采样节点","Select sampler"),samplers,0,i->{fields.removeAllViews();tagFields(fields,new ArrayList<>(r.comfy.get(i).entrySet()),0);});body.addView(fields);tagFields(fields,new ArrayList<>(r.comfy.get(0).entrySet()),0);}if(!r.note.isEmpty())body.addView(label(r.note,12,false));}else{if(r.web.isEmpty())body.addView(label(t("未发现 WebUI 信息","No WebUI information"),13,false));else tagFields(body,new ArrayList<>(r.web.entrySet()),0);}}
    void tagFields(LinearLayout body,List<Map.Entry<String,String>> fields,int start){int end=Math.min(fields.size(),start+40);for(int i=start;i<end;i++){Map.Entry<String,String> f=fields.get(i);tagField(body,f.getKey(),f.getValue());}if(end<fields.size()){Button more=button(t("显示更多参数","Show more parameters"),()->{});more.setOnClickListener(v->{body.removeView(more);tagFields(body,fields,end);});body.addView(more,new LinearLayout.LayoutParams(-1,dp(48)));}}
    void tagField(LinearLayout body,String key,String value){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView caption=label(key,14,true);row.addView(caption,new LinearLayout.LayoutParams(0,-2,1));Button copy=button("⧉",()->{android.content.ClipboardManager cb=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);try{cb.setPrimaryClip(ClipData.newPlainText(key,value));toast(t("已复制","Copied"));}catch(RuntimeException ex){toast(t("文本过大，请导出 TXT","Text too large for clipboard; export TXT"));}});copy.setContentDescription(t("复制 ","Copy ")+key);row.addView(copy,new LinearLayout.LayoutParams(dp(48),dp(48)));body.addView(row);EditText text=new EditText(this);text.setText(value.length()>8192?value.substring(0,8192)+t("\n预览已缩短，复制或 TXT 导出保留完整内容","\nPreview shortened; Copy and TXT preserve the full content"):value);text.setTextSize(13);text.setKeyListener(null);text.setTextIsSelectable(true);text.setMinLines(2);text.setMaxLines(9);text.setHorizontallyScrolling(false);text.setVerticalScrollBarEnabled(true);text.setOnTouchListener((v,e)->{if(e.getActionMasked()==MotionEvent.ACTION_DOWN)v.getParent().requestDisallowInterceptTouchEvent(true);if(e.getActionMasked()==MotionEvent.ACTION_UP||e.getActionMasked()==MotionEvent.ACTION_CANCEL)v.getParent().requestDisallowInterceptTouchEvent(false);return false;});body.addView(text,new LinearLayout.LayoutParams(-1,-2));}
    String format(Map<String,String> fields){StringBuilder b=new StringBuilder();for(Map.Entry<String,String> e:fields.entrySet())b.append(e.getKey()).append(":\n").append(e.getValue()).append("\n\n");return b.toString();}File txt(String name,String content)throws Exception{File out=Files.unique(outputDir,name);try(OutputStream o=new FileOutputStream(out)){o.write(content.getBytes(Files.UTF8));}return out;}
    int colorIndex(){int color=prefs.getInt("color",Color.WHITE);return color==Color.BLACK?1:color==0xffeee9f7?2:color==0xfff8e4ee?3:0;}
    void settingsPage(LinearLayout body){LinearLayout c=card(body,t("语言","Language"));spinner(c,"Language / 语言",new String[]{"简体中文","English"},english?1:0,i->{boolean next=i==1;if(next!=english){english=next;prefs.edit().putString("language",next?"en":"zh").apply();rebuild();}});c.addView(label(t("切换后立即生效，保存选择与参数保留。","Applies immediately; destinations and parameters are retained."),13,false));LinearLayout opts=card(body,t("默认设置","Defaults"));spinner(opts,t("留边颜色","Padding color"),new String[]{t("白色","White"),t("黑色","Black"),t("淡紫","Lilac"),t("淡粉","Pink")},colorIndex(),i->prefs.edit().putInt("color",new int[]{Color.WHITE,Color.BLACK,0xffeee9f7,0xfff8e4ee}[i]).apply());slider(opts,t("GIF 默认间隔 ms","Default GIF interval ms"),20,2000,prefs.getInt("gifDelay",400),v->prefs.edit().putInt("gifDelay",v).apply());slider(opts,t("GIF 默认最长边 px","Default GIF edge px"),100,1024,prefs.getInt("gifSize",480),v->prefs.edit().putInt("gifSize",v).apply());LinearLayout about=card(body,t("关于","About"));about.addView(label(t("所有功能在手机本地运行，无需联网。预览使用缩略图，批量任务逐个处理。原文件保留，重名不覆盖。","Everything runs locally without a network connection. Bounded previews and sequential batches. Originals remain unchanged; duplicate names get suffixes."),13,false));buttons(about,button(t("开源许可","Open-source licenses"),()->new AlertDialog.Builder(this).setTitle(t("开源许可","Open-source licenses")).setMessage("Gilbert traversal\nCopyright (c) 2018 Jakub Červený\nBSD-2-Clause\n\n"+license()).setPositiveButton("OK",null).show()));LinearLayout creator=card(body,t("个人制作信息","Creator"));creator.addView(label(t("制作：光影若水","Created by: 光影若水"),16,true));TextView projectUrl=label("https://github.com/pkh2388235687-star/AI-Image-Toolbox",13,false);projectUrl.setTextIsSelectable(true);creator.addView(projectUrl);buttons(creator,button(t("打开 GitHub 项目","Open GitHub project"),()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/pkh2388235687-star/AI-Image-Toolbox")).addCategory(Intent.CATEGORY_BROWSABLE));}catch(ActivityNotFoundException|SecurityException ex){toast(t("无法打开浏览器，请手动访问：","Unable to open a browser. Please visit: ")+"https://github.com/pkh2388235687-star/AI-Image-Toolbox");}}));}
    String license(){try(InputStream in=getAssets().open("NOTICE.md")){ByteArrayOutputStream out=new ByteArrayOutputStream();Files.copy(in,out,new Files.Job());return new String(out.toByteArray(),Files.UTF8);}catch(Exception e){return "BSD-2-Clause: redistribution permitted with copyright, conditions and disclaimer. Provided AS IS without warranty.";}}
    void rebuild(){toolbar.findViewWithTag("navigation").setContentDescription(t("打开功能菜单","Open navigation"));((Button)progressBox.findViewWithTag("cancel")).setText(t("取消任务","Cancel task"));message(t("全部在本机处理","All processing stays on this device"));cancelPreview();for(Widgets.Preview p:previews){p.ticket++;if(p.pending!=null)ui.removeCallbacks(p.pending);p.set(null);}previews.clear();queues.clear();saveModes.clear();if(editor!=null&&editor.getParent()!=null)((ViewGroup)editor.getParent()).removeView(editor);for(int i=0;i<pages.length;i++){if(pages[i]!=null)layout.removeView(pages[i]);pages[i]=null;}showPage(page);}
    public void onConfigurationChanged(android.content.res.Configuration c){super.onConfigurationChanged(c);closeDrawer();for(ScrollView p:pages)if(p!=null)p.requestLayout();root.requestApplyInsets();}
    public void onBackPressed(){if(overlay!=null)closeDrawer();else if(busy)new AlertDialog.Builder(this).setMessage(t("取消当前任务？","Cancel current task?")).setPositiveButton(t("取消任务","Cancel task"),(d,w)->{if(active!=null)active.cancelled=true;}).setNegativeButton(t("继续处理","Keep processing"),null).show();else super.onBackPressed();}
    protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putInt("page",page);}
    void releaseHiddenPreviews(){for(Widgets.Preview p:previews)if(!isVisible(p)){p.ticket++;if(p.pending!=null)ui.removeCallbacks(p.pending);p.set(null);}}
    public void onTrimMemory(int level){super.onTrimMemory(level);if(level>=TRIM_MEMORY_RUNNING_LOW){cancelPreview();releaseHiddenPreviews();}}
    boolean isVisible(View v){return v.isShown();}
    protected void onDestroy(){destroyed=true;cancelPreview();if(active!=null)active.cancelled=true;worker.execute(()->{if(editor!=null)editor.release();});worker.shutdown();for(Widgets.Preview p:previews)p.set(null);super.onDestroy();}
    void runSelfTest(){task(j->{AndroidTests.run(this,outputDir,j);return Collections.emptyList();},files->{message("Checking UI...");new Thread(()->{File external=getExternalFilesDir(null);File dir=new File(external==null?getFilesDir():external,"verification");try{UiTests.run(this,dir,new Files.Job());ui.post(()->message("SELFTEST PASS"));}catch(Throwable e){try(PrintWriter report=new PrintWriter(new File(dir,"ui-performance.failed.txt"))){e.printStackTrace(report);}catch(Exception ignored){}ui.post(()->message(error(e)));}},"ui-test-driver").start();});}

}
