package com.guangyingruoshui.imagetools;

import org.json.*;
import java.io.*;
import java.util.*;
import java.util.regex.*;
import java.util.zip.CRC32;

final class Metadata {
    static final int LIMIT=8*1024*1024;
    static class Result {LinkedHashMap<String,String> web=new LinkedHashMap<>();ArrayList<LinkedHashMap<String,String>> comfy=new ArrayList<>();String prompt="",workflow="",note="";}
    static void transfer(RandomAccessFile in,OutputStream out,long n,Files.Job job)throws Exception{Files.range(in.getFilePointer(),n,in.length());byte[] buf=new byte[65536];while(n>0){job.check();int count=(int)Math.min(n,buf.length);in.readFully(buf,0,count);out.write(buf,0,count);n-=count;}}
    static Map<String,String> text(File input,Files.Job job)throws Exception{Map<String,String> meta=new LinkedHashMap<>();try(RandomAccessFile s=new RandomAccessFile(input,"r")){byte[] signature=Files.read(s,(int)Math.min(12,s.length()));if(Files.starts(signature,Files.PNG)){s.seek(8);int chunks=0;while(s.getFilePointer()<s.length()){job.check();if(++chunks>1000000)throw new IOException("数据块过多 / Too many chunks");byte[] h=Files.read(s,8);long n=Files.be(h,0,4);String type=new String(h,4,4,Files.LATIN);Files.range(s.getFilePointer(),n+4,s.length());if(type.equals("tEXt")||type.equals("zTXt")||type.equals("iTXt")||type.equals("comf")||type.equals("eXIf")){if(n>LIMIT)throw new IOException("元数据过大 / Metadata too large");byte[] b=Files.read(s,(int)n);CRC32 c=new CRC32();c.update(h,4,4);c.update(b);if(c.getValue()!=Files.be(Files.read(s,4),0,4))throw new IOException("元数据校验失败 / Metadata CRC mismatch");if(type.equals("eXIf"))exif(b,meta);else if(type.equals("comf")){int zero=Files.zero(b,0);meta.put(new String(b,0,zero,Files.LATIN).toLowerCase(Locale.ROOT),new String(b,zero+1,b.length-zero-1,Files.LATIN));}else{int z=Files.zero(b,0);String key=new String(b,0,z,Files.LATIN).toLowerCase(Locale.ROOT),value;if(type.equals("tEXt"))value=new String(b,z+1,b.length-z-1,Files.LATIN);else if(type.equals("zTXt")){if(z+2>b.length||b[z+1]!=0)throw new IOException("压缩文本无效 / Invalid compressed text");value=new String(Files.inflate(b,z+2,b.length-z-2),Files.LATIN);}else{if(z+3>b.length)throw new IOException("国际文本无效 / Invalid international text");int flag=b[z+1],method=b[z+2],lang=Files.zero(b,z+3),translated=Files.zero(b,lang+1),p=translated+1;if(method!=0||flag<0||flag>1)throw new IOException("国际文本压缩无效 / Invalid text compression");value=new String(flag==1?Files.inflate(b,p,b.length-p):Arrays.copyOfRange(b,p,b.length),Files.UTF8);}meta.put(key,value);}}else{CRC32 check=new CRC32();check.update(h,4,4);byte[] buffer=new byte[65536];long remaining=n;while(remaining>0){job.check();int count=(int)Math.min(remaining,buffer.length);s.readFully(buffer,0,count);check.update(buffer,0,count);remaining-=count;}if(check.getValue()!=Files.be(Files.read(s,4),0,4))throw new IOException("PNG 校验失败 / PNG CRC mismatch");}if(type.equals("IEND"))break;}}
        else if(signature.length>=2&&(signature[0]&255)==255&&(signature[1]&255)==216){s.seek(2);while(s.getFilePointer()<s.length()){job.check();if(s.read()!=255)throw new IOException("JPG 标记损坏 / Invalid JPEG");int marker;do{marker=s.read();}while(marker==255);if(marker==217||marker==218)break;if(marker==1||marker>=208&&marker<=215)continue;int n=s.readUnsignedShort()-2;if(n<0)throw new IOException("JPG 长度无效 / Invalid JPEG length");byte[] b=Files.read(s,n);if(marker==225&&Files.starts(b,"Exif\u0000\u0000".getBytes(Files.LATIN)))exif(Arrays.copyOfRange(b,6,b.length),meta);}}
        else if(signature.length==12&&new String(signature,0,4,Files.LATIN).equals("RIFF")&&new String(signature,8,4,Files.LATIN).equals("WEBP")){long end=Files.le(signature,4,4)+8;Files.range(0,end,s.length());s.seek(12);while(s.getFilePointer()<end){job.check();byte[] h=Files.read(s,8);long n=Files.le(h,4,4);Files.range(s.getFilePointer(),n+(n&1),end);if(new String(h,0,4,Files.LATIN).equals("EXIF")){if(n>LIMIT)throw new IOException("EXIF 过大 / EXIF too large");exif(Files.read(s,(int)n),meta);s.seek(s.getFilePointer()+(n&1));}else s.seek(s.getFilePointer()+n+(n&1));}}
        }return meta;}
    static long tiff(byte[] b,int p,int n,boolean little)throws IOException{return little?Files.le(b,p,n):boundsBe(b,p,n);}
    static long boundsBe(byte[] b,int p,int n)throws IOException{if(p<0||p+n>b.length)throw new IOException("EXIF 越界 / EXIF out of bounds");return Files.be(b,p,n);}
    static int imageOrientation(File input){try(RandomAccessFile f=new RandomAccessFile(input,"r")){byte[] sig=Files.read(f,(int)Math.min(12,f.length()));if(sig.length>=2&&(sig[0]&255)==255&&(sig[1]&255)==216){f.seek(2);for(int chunks=0;chunks<10000&&f.getFilePointer()<f.length();chunks++){if(f.read()!=255)return 1;int marker;do{marker=f.read();}while(marker==255);if(marker==217||marker==218)return 1;if(marker==1||marker>=208&&marker<=215)continue;int n=f.readUnsignedShort()-2;Files.range(f.getFilePointer(),n,f.length());if(marker==225){byte[] b=Files.read(f,n);if(Files.starts(b,"Exif\u0000\u0000".getBytes(Files.LATIN)))return orientation(b);}else f.seek(f.getFilePointer()+n);}}
        else if(Files.starts(sig,Files.PNG)){f.seek(8);for(int chunks=0;chunks<100000&&f.getFilePointer()<f.length();chunks++){byte[] h=Files.read(f,8);long n=Files.be(h,0,4);Files.range(f.getFilePointer(),n+4,f.length());String type=new String(h,4,4,Files.LATIN);if(type.equals("eXIf")&&n<=1024*1024)return orientation(Files.read(f,(int)n));if(type.equals("IEND"))break;f.seek(f.getFilePointer()+n+4);}}
        else if(sig.length==12&&new String(sig,0,4,Files.LATIN).equals("RIFF")&&new String(sig,8,4,Files.LATIN).equals("WEBP")){while(f.getFilePointer()<f.length()){byte[] h=Files.read(f,8);long n=Files.le(h,4,4);Files.range(f.getFilePointer(),n+(n&1),f.length());if(new String(h,0,4,Files.LATIN).equals("EXIF")&&n<=1024*1024)return orientation(Files.read(f,(int)n));f.seek(f.getFilePointer()+n+(n&1));}}}catch(Exception ignored){}return 1;}
    static int orientation(byte[] b)throws Exception{if(Files.starts(b,"Exif\u0000\u0000".getBytes(Files.LATIN)))b=Arrays.copyOfRange(b,6,b.length);if(b.length<8)return 1;boolean little=b[0]=='I'&&b[1]=='I';if(!little&&!(b[0]=='M'&&b[1]=='M'))return 1;int at=(int)tiff(b,4,4,little),count=(int)tiff(b,at,2,little);if(count>1024)throw new IOException("EXIF 条目过多 / Too many EXIF entries");for(int i=0;i<count;i++){int p=at+2+i*12;if(tiff(b,p,2,little)==274&&tiff(b,p+2,2,little)==3&&tiff(b,p+4,4,little)==1){int v=(int)tiff(b,p+8,2,little);return v>=1&&v<=8?v:1;}}return 1;}
    static byte[] orientationExif(int value){byte[] b={73,73,42,0,8,0,0,0,1,0,18,1,3,0,1,0,0,0,1,0,0,0,0,0,0,0};b[18]=(byte)value;return b;}
    static void exif(byte[] b,Map<String,String> meta)throws Exception{if(Files.starts(b,"Exif\u0000\u0000".getBytes(Files.LATIN)))b=Arrays.copyOfRange(b,6,b.length);if(b.length<8)return;boolean little=b[0]=='I'&&b[1]=='I';if(!little&&!(b[0]=='M'&&b[1]=='M'))return;if(tiff(b,2,2,little)!=42)return;ArrayDeque<Integer> queue=new ArrayDeque<>();Set<Integer> visited=new HashSet<>();queue.add((int)tiff(b,4,4,little));while(!queue.isEmpty()){int at=queue.remove();if(at==0||!visited.add(at))continue;if(visited.size()>16)throw new IOException("EXIF 层级过多 / Too many EXIF directories");int count=(int)tiff(b,at,2,little);if(count>2048)throw new IOException("EXIF 条目过多 / Too many EXIF fields");for(int i=0;i<count;i++){int p=at+2+i*12,tag=(int)tiff(b,p,2,little),type=(int)tiff(b,p+2,2,little);long n=tiff(b,p+4,4,little);if(tag==34665){queue.add((int)tiff(b,p+8,4,little));continue;}if(tag!=37510&&tag!=270&&tag!=271&&tag!=272)continue;if(n>LIMIT||n<1)continue;int atData=n<=4?p+8:(int)tiff(b,p+8,4,little);Files.range(atData,n,b.length);byte[] v=Arrays.copyOfRange(b,atData,atData+(int)n);String text;if(tag==37510&&v.length>=8){String encoding=new String(v,0,8,Files.LATIN);if(encoding.startsWith("UNICODE")){byte[] unicode=Arrays.copyOfRange(v,8,v.length);text=new String(unicode,java.nio.charset.Charset.forName(unicode.length>=2&&unicode[0]==(byte)255&&unicode[1]==(byte)254?"UTF-16LE":"UTF-16BE"));}else text=new String(v,8,v.length-8,Files.UTF8);}else text=new String(v,Files.UTF8);text=text.replace("\u0000","").replace("\ufeff","");if(text.startsWith("prompt:")){meta.put("prompt",text.substring(7));continue;}if(text.startsWith("workflow:")){meta.put("workflow",text.substring(9));continue;}if(tag!=37510&&tag!=270)continue;if(text.startsWith("{")){try{JSONObject o=new JSONObject(text);if(o.has("prompt"))meta.put("prompt",o.get("prompt").toString());if(o.has("workflow"))meta.put("workflow",o.get("workflow").toString());if(o.has("parameters"))meta.put("parameters",o.get("parameters").toString());}catch(JSONException e){meta.put("parameters",text);}}else meta.put("parameters",text);}}}
    static Result inspect(File input,Files.Job job)throws Exception{Map<String,String> m=text(input,job);Result r=new Result();if(m.containsKey("parameters")&&!m.get("parameters").trim().isEmpty())web(m.get("parameters"),r.web);r.prompt=m.containsKey("prompt")?m.get("prompt"):"";r.workflow=m.containsKey("workflow")?m.get("workflow"):"";if(!r.prompt.isEmpty()){try{JSONObject graph=new JSONObject(Comfy.precise(r.prompt));JSONObject workflow=null;if(!r.workflow.isEmpty())try{workflow=new JSONObject(Comfy.precise(r.workflow));}catch(JSONException ignored){}comfy(graph,workflow,r);}catch(Exception e){r.note="prompt 解析失败 / Invalid prompt JSON: "+e.getMessage();}}boolean sampler=false;for(Map<String,String> fields:r.comfy)if(fields.containsKey("采样节点 / Sampler node"))sampler=true;if(!sampler&&!r.workflow.isEmpty())try{r.comfy.clear();JSONObject workflow=new JSONObject(Comfy.precise(r.workflow));comfy(workflowGraph(workflow),workflow,r);r.note+="\n来自 workflow 控件；未保存的动态节点输出无法恢复 / Workflow values; unsaved dynamic outputs cannot be recovered.";}catch(Exception e){r.note+="\nworkflow 解析失败 / Invalid workflow: "+e.getMessage();}if(r.comfy.isEmpty()&&(!r.prompt.isEmpty()||!r.workflow.isEmpty())){LinkedHashMap<String,String> raw=new LinkedHashMap<>();if(!r.prompt.isEmpty())raw.put("原始 prompt JSON",r.prompt);if(!r.workflow.isEmpty())raw.put("原始 workflow JSON",r.workflow);r.comfy.add(raw);}return r;}
    static List<String> split(String s){ArrayList<String> a=new ArrayList<>();int start=0,depth=0;boolean quoted=false,escaped=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(escaped){escaped=false;continue;}if(quoted&&c=='\\'){escaped=true;continue;}if(c=='"'){quoted=!quoted;continue;}if(quoted)continue;if(c=='{'||c=='['||c=='(')depth++;if(c=='}'||c==']'||c==')')depth=Math.max(0,depth-1);if(c==','&&depth==0&&s.substring(i+1).matches("(?s)^\\s*[\\w .\\-/]+:.*")){a.add(s.substring(start,i).trim());start=i+1;}}a.add(s.substring(start).trim());return a;}
    static void web(String s,LinkedHashMap<String,String> out){s=s.replace("\r\n","\n");String[] lines=s.split("\n",-1);int last=-1;for(int i=lines.length-1;i>=0;i--)if(lines[i].matches("^(Steps|Sampler|CFG scale|Seed|Size): .*")){last=i;break;}StringBuilder p=new StringBuilder();for(int i=0;i<(last<0?lines.length:last);i++){if(i>0)p.append('\n');p.append(lines[i]);}String prompts=p.toString();Matcher neg=Pattern.compile("(?:^|\\n)Negative prompt:\\s*").matcher(prompts);if(neg.find()){out.put("正面 tag / Positive tag",prompts.substring(0,neg.start()).trim());out.put("负面 tag / Negative tag",prompts.substring(neg.end()));}else{out.put("正面 tag / Positive tag",prompts);out.put("负面 tag / Negative tag","");}if(last>=0){StringBuilder params=new StringBuilder();for(int i=last;i<lines.length;i++){if(i>last)params.append('\n');params.append(lines[i]);}for(String pair:split(params.toString())){int k=pair.indexOf(':');if(k>0){String value=pair.substring(k+1).trim();if(value.startsWith("\"")&&value.endsWith("\""))try{value=String.valueOf(new JSONTokener(value).nextValue());}catch(JSONException ignored){}out.put(pair.substring(0,k).trim(),value);}}}out.put("完整参数 / Full parameters",s);}
    static JSONObject workflowGraph(JSONObject workflow)throws Exception{return Comfy.workflow(workflow);}
    static JSONObject in(JSONObject g,String id){JSONObject n=g.optJSONObject(id);return n==null?new JSONObject():n.optJSONObject("inputs")==null?new JSONObject():n.optJSONObject("inputs");}
    static String join(Collection<String> strings){StringBuilder b=new StringBuilder();for(String s:strings){if(b.length()>0)b.append('\n');b.append(s);}return b.toString();}
    static void comfy(JSONObject graph,JSONObject workflow,Result result)throws Exception{Comfy.parse(graph,workflow,result);}
    static File clean(File input,File dir,Files.Job job)throws Exception{File out=Files.unique(dir,Files.stem(input.getName())+"_清信息"+Files.ext(input.getName())),tmp=Files.temp(dir);int webOrientation=1;boolean webExtended=false;try(RandomAccessFile s=new RandomAccessFile(input,"r");OutputStream o=new BufferedOutputStream(new FileOutputStream(tmp))){byte[] signature=Files.read(s,(int)Math.min(12,s.length()));if(Files.starts(signature,Files.PNG)){s.seek(8);o.write(Files.PNG);Set<String> keep=new HashSet<>(Arrays.asList("IHDR","PLTE","IDAT","IEND","tRNS","iCCP","sRGB","gAMA","cHRM","cICP","mDCv","cLLi","sBIT","pHYs","acTL","fcTL","fdAT"));while(true){job.check();byte[] h=Files.read(s,8);long n=Files.be(h,0,4);String type=new String(h,4,4,Files.LATIN);Files.range(s.getFilePointer(),n+4,s.length());if(type.equals("eXIf")){if(n>LIMIT)throw new IOException("EXIF 过大 / EXIF too large");int orientation=orientation(Files.read(s,(int)n));s.skipBytes(4);if(orientation!=1)Files.chunk(o,"eXIf",orientationExif(orientation));}else if(keep.contains(type)||Character.isUpperCase(type.charAt(0))){o.write(h);transfer(s,o,n+4,job);}else s.seek(s.getFilePointer()+n+4);if(type.equals("IEND"))break;}}
        else if(signature.length>=2&&(signature[0]&255)==255&&(signature[1]&255)==216){s.seek(2);o.write(new byte[]{(byte)255,(byte)216});while(true){job.check();if(s.read()!=255)throw new IOException("JPG 标记无效 / Invalid JPEG marker");int marker;do{marker=s.read();}while(marker==255);if(marker==218){o.write(255);o.write(marker);transfer(s,o,s.length()-s.getFilePointer(),job);break;}if(marker==217){o.write(255);o.write(marker);break;}if(marker==1||marker>=208&&marker<=215){o.write(255);o.write(marker);continue;}int n=s.readUnsignedShort();if(n<2)throw new IOException("JPG 长度无效 / Invalid JPEG length");byte[] b=Files.read(s,n-2);boolean keep=marker<224||marker==224||marker==226&&Files.starts(b,"ICC_PROFILE\u0000".getBytes(Files.LATIN))||marker==238&&Files.starts(b,"Adobe".getBytes(Files.LATIN));if(marker==225&&Files.starts(b,"Exif\u0000\u0000".getBytes(Files.LATIN))){int orientation=orientation(b);if(orientation!=1){b=Files.concat("Exif\u0000\u0000".getBytes(Files.LATIN),orientationExif(orientation));n=b.length+2;keep=true;}}if(marker==254)keep=false;if(keep){o.write(255);o.write(marker);o.write(n>>8);o.write(n);o.write(b);}}}
        else if(signature.length==12&&new String(signature,0,4,Files.LATIN).equals("RIFF")&&new String(signature,8,4,Files.LATIN).equals("WEBP")){long end=Files.le(signature,4,4)+8;Files.range(0,end,s.length());o.write(signature);s.seek(12);while(s.getFilePointer()<end){job.check();byte[] h=Files.read(s,8);long n=Files.le(h,4,4);Files.range(s.getFilePointer(),n+(n&1),end);String type=new String(h,0,4,Files.LATIN);if(type.equals("XMP ")){s.seek(s.getFilePointer()+n+(n&1));}else if(type.equals("EXIF")){if(n>LIMIT)throw new IOException("EXIF 过大 / EXIF too large");webOrientation=orientation(Files.read(s,(int)n));s.seek(s.getFilePointer()+(n&1));}else if(type.equals("VP8X")){webExtended=true;byte[] b=Files.read(s,(int)n);if(n!=10)throw new IOException("VP8X 长度无效 / Invalid VP8X");b[0]&=~12;o.write(h);o.write(b);}else{o.write(h);transfer(s,o,n+(n&1),job);}}if(webOrientation!=1){if(!webExtended)throw new IOException("带方向信息的 WebP 缺少 VP8X / Oriented WebP lacks VP8X");byte[] sanitized=orientationExif(webOrientation),length=new byte[4];Files.le(length,0,sanitized.length,4);o.write("EXIF".getBytes(Files.LATIN));o.write(length);o.write(sanitized);}}
        else if(new String(signature,0,Math.min(signature.length,6),Files.LATIN).startsWith("GIF8")){s.seek(0);byte[] h=Files.read(s,13);o.write(h);if((h[10]&128)!=0)transfer(s,o,3L*(1<<((h[10]&7)+1)),job);while(true){job.check();int type=s.read();if(type<0)throw new EOFException();if(type==59){o.write(type);break;}if(type==44){o.write(type);byte[] descriptor=Files.read(s,9);o.write(descriptor);if((descriptor[8]&128)!=0)transfer(s,o,3L*(1<<((descriptor[8]&7)+1)),job);o.write(s.readUnsignedByte());subblocks(s,o,true,job);}else if(type==33){int label=s.readUnsignedByte();if(label==249){o.write(type);o.write(label);subblocks(s,o,true,job);}else if(label==255){int size=s.readUnsignedByte();byte[] app=Files.read(s,size);String name=new String(app,Files.LATIN);boolean keep=name.equals("NETSCAPE2.0")||name.equals("ANIMEXTS1.0");if(keep){o.write(type);o.write(label);o.write(size);o.write(app);}subblocks(s,o,keep,job);}else{subblocks(s,o,false,job);}}else throw new IOException("GIF 标记无效 / Invalid GIF marker");}}
        else throw new IOException("清信息支持 PNG、JPG、WebP、GIF / PNG, JPG, WebP, GIF supported");
        }catch(Exception e){tmp.delete();throw e;}try{if(Files.ext(input.getName()).equals(".webp"))try(RandomAccessFile f=new RandomAccessFile(tmp,"rw")){byte[] length=new byte[4];Files.le(length,0,f.length()-8,4);f.seek(4);f.write(length);if(webOrientation!=1){f.seek(12);while(f.getFilePointer()<f.length()){long at=f.getFilePointer();byte[] h=Files.read(f,8);long n=Files.le(h,4,4);if(new String(h,0,4,Files.LATIN).equals("VP8X")){int flags=f.readUnsignedByte();f.seek(at+8);f.write(flags|8);break;}f.seek(at+8+n+(n&1));}}}Files.commit(tmp,out,job);return out;}finally{tmp.delete();}}
    static void subblocks(RandomAccessFile s,OutputStream o,boolean keep,Files.Job j)throws Exception{while(true){j.check();int n=s.readUnsignedByte();if(keep)o.write(n);if(n==0)return;if(keep)transfer(s,o,n,j);else{Files.range(s.getFilePointer(),n,s.length());s.seek(s.getFilePointer()+n);}}}
}
