package com.guangyingruoshui.imagetools;

import android.graphics.*;
import java.io.*;
import java.net.URI;
import java.util.*;
import com.google.zxing.*;
import com.google.zxing.common.*;
import com.google.zxing.qrcode.*;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import org.json.JSONObject;

final class QrService {
    static final class Region {String url;int x,y,size,width,height;int margin=4;}
    static String website(String value)throws Exception{URI u=new URI(value==null?"":value.trim());String scheme=u.getScheme();if(!("https".equalsIgnoreCase(scheme)||"http".equalsIgnoreCase(scheme))||u.getHost()==null||u.getUserInfo()!=null)throw new IOException("请输入完整的 HTTP 或 HTTPS 网站链接 / Enter a full HTTP or HTTPS website URL");String s=u.toASCIIString();if(s.getBytes(Files.UTF8).length>1100)throw new IOException("链接过长，请使用较短链接 / Use a shorter URL");return s;}
    static BitMatrix matrix(String value,int side)throws Exception{return matrix(value,side,4);}
    static BitMatrix matrix(String value,int side,int margin)throws Exception{if(margin<0||margin>12)throw new IOException("Invalid QR border");Map<EncodeHintType,Object> hints=new EnumMap<>(EncodeHintType.class);hints.put(EncodeHintType.ERROR_CORRECTION,ErrorCorrectionLevel.H);hints.put(EncodeHintType.CHARACTER_SET,"UTF-8");hints.put(EncodeHintType.MARGIN,margin);return new QRCodeWriter().encode(website(value),BarcodeFormat.QR_CODE,side,side,hints);}
    static Bitmap code(String value,int side)throws Exception{return code(value,side,4);}
    static Bitmap code(String value,int side,int margin)throws Exception{BitMatrix m=matrix(value,side,margin);Bitmap image=Bitmap.createBitmap(m.getWidth(),m.getHeight(),Bitmap.Config.ARGB_8888);int[] row=new int[m.getWidth()];for(int y=0;y<m.getHeight();y++){for(int x=0;x<row.length;x++)row[x]=m.get(x,y)?Color.BLACK:Color.WHITE;image.setPixels(row,0,row.length,0,y,row.length,1);}return image;}
    static String decode(LuminanceSource source){Map<DecodeHintType,Object> hints=new EnumMap<>(DecodeHintType.class);hints.put(DecodeHintType.TRY_HARDER,true);hints.put(DecodeHintType.POSSIBLE_FORMATS,Collections.singletonList(BarcodeFormat.QR_CODE));for(boolean inverse:new boolean[]{false,true})try{return new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(inverse?source.invert():source)),hints).getText();}catch(NotFoundException ignored){try{Result[] values=new com.google.zxing.multi.qrcode.QRCodeMultiReader().decodeMultiple(new BinaryBitmap(new HybridBinarizer(inverse?source.invert():source)),hints);if(values.length>0)return values[0].getText();}catch(NotFoundException none){}}return null;}
    static String scan(Bitmap image,Files.Job job)throws Exception{for(boolean white:new boolean[]{true,false}){job.check();Bitmap flat=Images.fit(image,image.getWidth(),image.getHeight(),white?Color.WHITE:Color.BLACK);try{int[] pixels=new int[flat.getWidth()*flat.getHeight()];flat.getPixels(pixels,0,flat.getWidth(),0,0,flat.getWidth(),flat.getHeight());String text=decode(new RGBLuminanceSource(flat.getWidth(),flat.getHeight(),pixels));if(text!=null)return text;}finally{flat.recycle();}}return null;}
    static Region compose(Bitmap result,String url,int percent,int x,int y,boolean only)throws Exception{return compose(result,url,percent,x,y,only,4);}
    static Region compose(Bitmap result,String url,int percent,int x,int y,boolean only,int margin)throws Exception{url=website(url);int edge=Math.min(result.getWidth(),result.getHeight()),modules=matrix(url,1,margin).getWidth(),requested=edge*Math.max(10,Math.min(90,percent))/100,scale=Math.max(4,requested/modules),side=modules*scale;if(side>edge)throw new IOException("图片太小，请使用更大图片 / Use a larger image");Region r=new Region();r.margin=margin;r.url=url;r.size=side;r.width=result.getWidth();r.height=result.getHeight();r.x=Math.max(0,Math.min(r.width-side,Math.round(r.width*x/100f-side/2f)));r.y=Math.max(0,Math.min(r.height-side,Math.round(r.height*y/100f-side/2f)));Bitmap qr=code(url,side,margin);try{new Canvas(result).drawBitmap(qr,r.x,r.y,new Paint());}finally{qr.recycle();}return r;}
    static int optimizePixel(int cover,boolean ink,BackgroundRevealAuto.Profile profile){double luma=BackgroundRevealAuto.y(cover);int white=Math.max(181,Math.min(255,BackgroundRevealAuto.channel(BackgroundRevealAuto.tone(luma,profile.whiteLow,profile.whiteHigh,profile.whiteFloor,250)))),black=ink?16:112,alpha=BackgroundRevealAuto.channel(255*(1-(white-black)/250.0)),c=alpha==0?0:BackgroundRevealAuto.channel(black*255.0/alpha);return alpha<<24|c<<16|c<<8|c;}
    static Region optimize(Bitmap result,Region input,Bitmap cover,BackgroundRevealAuto.Profile profile,Files.Job job,boolean strict)throws Exception{
        job.check();if(input==null||cover==null||profile==null)throw new IOException("二维码优化需要本工具生成的二维码 PNG / QR optimization requires an app-generated QR PNG");double sx=result.getWidth()/(double)input.width,sy=result.getHeight()/(double)input.height;int modules=matrix(input.url,1,input.margin).getWidth(),scale=(int)Math.round(input.size*Math.min(sx,sy))/modules;if(strict&&scale<4)throw new IOException("导出尺寸太小，请提高二维码分辨率 / Increase output size to keep the QR scannable");scale=Math.max(1,scale);int side=scale*modules;
        Region r=new Region();r.margin=input.margin;r.url=input.url;r.size=Math.max(side,(int)Math.ceil(input.size*Math.max(sx,sy)));r.width=result.getWidth();r.height=result.getHeight();if(r.size>Math.min(r.width,r.height))throw new IOException("QR output too small");r.x=Math.max(0,Math.min(r.width-r.size,(int)Math.floor(input.x*sx)));r.y=Math.max(0,Math.min(r.height-r.size,(int)Math.floor(input.y*sy)));BitMatrix qr=matrix(r.url,side,r.margin);Bitmap fitted=Images.fit(cover,r.width,r.height,Color.WHITE);
        try{int[] line=new int[result.getWidth()];for(int y=0;y<result.getHeight();y++){job.check();result.getPixels(line,0,line.length,0,y,line.length,1);for(int x=0;x<line.length;x++){int v=line[x],a=v>>>24,black=(((v>>>16)&255)*a+127)/255,white=black+255-a,alpha=BackgroundRevealAuto.channel(255*(1-(white-black)/250.0)),c=alpha==0?0:BackgroundRevealAuto.channel(black*255.0/alpha);line[x]=alpha<<24|c<<16|c<<8|c;}result.setPixels(line,0,line.length,0,y,line.length,1);}int[] pixels=new int[r.size],values=new int[r.size];int inset=(r.size-side)/2;for(int y=0;y<r.size;y++){job.check();fitted.getPixels(values,0,r.size,r.x,r.y+y,r.size,1);boolean inside=y>=inset&&y<inset+side;for(int x=0;x<r.size;x++){boolean ink=inside&&x>=inset&&x<inset+side&&qr.get(x-inset,y-inset);pixels[x]=optimizePixel(values[x],ink,profile);}result.setPixels(pixels,0,r.size,r.x,r.y+y,r.size,1);}}finally{fitted.recycle();}
        if(strict&&!website(r.url).equals(scan(result,job)))throw new IOException("二维码优化自检失败，请增加尺寸 / QR optimization self-check failed; increase output size");return r;
    }
    static byte[] data(Region r)throws Exception{return new JSONObject().put("Url",r.url).put("X",r.x).put("Y",r.y).put("Size",r.size).put("Width",r.width).put("Height",r.height).put("Margin",r.margin).toString().getBytes(Files.UTF8);}
    static void tag(File png,Region r,Files.Job job)throws Exception{if(r==null)return;File tmp=Files.temp(png.getParentFile());try(InputStream in=new FileInputStream(png);OutputStream out=new FileOutputStream(tmp)){out.write(Files.read(in,8));while(true){job.check();byte[] head=Files.read(in,8);long length=((long)(head[0]&255)<<24)|((long)(head[1]&255)<<16)|((long)(head[2]&255)<<8)|(head[3]&255);String type=new String(head,4,4,"US-ASCII");if(type.equals("IEND"))Files.chunk(out,"qrLK",data(r));if(type.equals("qrLK")){skip(in,length+4);continue;}out.write(head);copyCount(in,out,length+4,job);if(type.equals("IEND"))break;}}catch(Exception e){tmp.delete();throw e;}try{if(!png.delete()||!tmp.renameTo(png))throw new IOException("Unable to update QR metadata");}finally{tmp.delete();}}
    static void copyCount(InputStream in,OutputStream out,long count,Files.Job job)throws Exception{byte[] b=new byte[65536];while(count>0){job.check();int n=in.read(b,0,(int)Math.min(count,b.length));if(n<0)throw new EOFException();out.write(b,0,n);count-=n;}}
    static void skip(InputStream in,long n)throws IOException{while(n>0){long skipped=in.skip(n);if(skipped<=0){if(in.read()<0)throw new EOFException();skipped=1;}n-=skipped;}}
    static Region read(File png)throws Exception{if(!Files.ext(png.getName()).equals(".png"))return null;try(InputStream in=new FileInputStream(png)){byte[] sig=Files.read(in,8);if(!Arrays.equals(sig,Files.PNG))return null;int width=0,height=0;while(true){byte[] h=Files.read(in,8);long n=((long)(h[0]&255)<<24)|((long)(h[1]&255)<<16)|((long)(h[2]&255)<<8)|(h[3]&255);String type=new String(h,4,4,"US-ASCII");if(type.equals("IHDR")&&n==13){byte[] dimensions=Files.read(in,13);width=((dimensions[0]&255)<<24)|((dimensions[1]&255)<<16)|((dimensions[2]&255)<<8)|(dimensions[3]&255);height=((dimensions[4]&255)<<24)|((dimensions[5]&255)<<16)|((dimensions[6]&255)<<8)|(dimensions[7]&255);skip(in,4);continue;}if(type.equals("qrLK")){if(n>8192)return null;byte[] data=Files.read(in,(int)n);java.util.zip.CRC32 crc=new java.util.zip.CRC32();crc.update(Arrays.copyOfRange(h,4,8));crc.update(data);byte[] checksum=Files.read(in,4);long expected=((long)(checksum[0]&255)<<24)|((long)(checksum[1]&255)<<16)|((long)(checksum[2]&255)<<8)|(checksum[3]&255);if(crc.getValue()!=expected)return null;JSONObject o=new JSONObject(new String(data,Files.UTF8));Region r=new Region();r.url=website(o.getString("Url"));r.x=o.getInt("X");r.y=o.getInt("Y");r.size=o.getInt("Size");r.width=o.getInt("Width");r.height=o.getInt("Height");r.margin=o.optInt("Margin",4);if(r.margin<0||r.margin>12||r.width!=width||r.height!=height||r.width<1||r.height<1||r.width>8192||r.height>8192||r.size<1||r.x<0||r.y<0||(long)r.x+r.size>r.width||(long)r.y+r.size>r.height)return null;return r;}if(type.equals("IEND"))return null;skip(in,n+4);}}catch(Exception e){return null;}}
}
