package com.guangyingruoshui.imagetools;

import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.os.*;
import android.provider.*;
import android.media.MediaScannerConnection;
import java.io.*;
import java.util.*;

final class Storage {
    static String mime(String name){switch(Files.ext(name)){case ".png":return "image/png";case ".jpg":case ".jpeg":return "image/jpeg";case ".gif":return "image/gif";case ".webp":return "image/webp";case ".bmp":return "image/bmp";case ".mp4":return "video/mp4";case ".zip":return "application/zip";case ".rar":return "application/vnd.rar";case ".7z":return "application/x-7z-compressed";case ".txt":return "text/plain";default:return "application/octet-stream";}}
    static String display(Context c,Uri uri){try(Cursor cursor=c.getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())return Files.name(cursor.getString(0));}catch(Exception ignored){}return "导入_"+System.currentTimeMillis()+".png";}
    static File importFile(Context c,Uri uri,Files.Job job)throws Exception{String name=display(c,uri);File dir=new File(c.getCacheDir(),"imports/"+UUID.randomUUID());if(!dir.mkdirs())throw new IOException("无法缓存文件 / Cannot cache file");File out=new File(dir,name),tmp=new File(dir,"input.tmp");try(InputStream in=c.getContentResolver().openInputStream(uri);OutputStream o=new FileOutputStream(tmp)){if(in==null)throw new IOException("文件无法读取 / Cannot read file");byte[] b=new byte[1024*1024];int n;long copied=0,last=0;while((n=in.read(b))!=-1){job.check();if(dir.getUsableSpace()<n+1024*1024)throw new IOException("存储空间不足 / Insufficient storage");o.write(b,0,n);copied+=n;if(job.progress!=null&&System.currentTimeMillis()-last>120){job.progress.update(copied,-1);last=System.currentTimeMillis();}}}catch(Exception e){tmp.delete();dir.delete();throw e;}try{Files.commit(tmp,out,job);return out;}finally{tmp.delete();}}
    static Uri child(ContentResolver cr,Uri parent,String name,String mime,boolean directory)throws Exception{Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(parent,DocumentsContract.getDocumentId(parent));try(Cursor cursor=cr.query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE},null,null,null)){if(cursor!=null)while(cursor.moveToNext()){if(name.equals(cursor.getString(1))){if(directory&&!DocumentsContract.Document.MIME_TYPE_DIR.equals(cursor.getString(2)))throw new IOException("同名文件阻止创建目录 / Folder name occupied");if(directory)return DocumentsContract.buildDocumentUriUsingTree(parent,cursor.getString(0));return null;}}}return DocumentsContract.createDocument(cr,parent,mime,name);}
    static Uri save(Context c,File file,String feature,boolean album,String tree,Files.Job job)throws Exception{ContentResolver cr=c.getContentResolver();String mime=mime(file.getName());Uri result=null;
        if(album){if(!mime.startsWith("image/")&&!mime.startsWith("video/"))throw new IOException("此文件不能保存到相册，请选择自定义文件夹 / Choose a folder for non-media files");
            if(Build.VERSION.SDK_INT>=29){ContentValues values=new ContentValues();values.put(MediaStore.MediaColumns.DISPLAY_NAME,file.getName());values.put(MediaStore.MediaColumns.MIME_TYPE,mime);values.put(MediaStore.MediaColumns.RELATIVE_PATH,(mime.startsWith("video/")?Environment.DIRECTORY_MOVIES:Environment.DIRECTORY_PICTURES)+"/AI图片修改工具集合/"+feature);values.put(MediaStore.MediaColumns.IS_PENDING,1);result=cr.insert(mime.startsWith("video/")?MediaStore.Video.Media.EXTERNAL_CONTENT_URI:MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values);if(result==null)throw new IOException("相册无法创建文件 / Cannot create album item");try{try(InputStream in=new FileInputStream(file);OutputStream o=cr.openOutputStream(result,"w")){if(o==null)throw new IOException("无法写入相册 / Cannot write album");Files.copy(in,o,job);}job.check();ContentValues done=new ContentValues();done.put(MediaStore.MediaColumns.IS_PENDING,0);cr.update(result,done,null,null);return result;}catch(Exception e){cr.delete(result,null,null);throw e;}}
            File root=Environment.getExternalStoragePublicDirectory(mime.startsWith("video/")?Environment.DIRECTORY_MOVIES:Environment.DIRECTORY_PICTURES),dir=new File(root,"AI图片修改工具集合/"+feature),out=Files.unique(dir,file.getName()),tmp=Files.temp(dir);try{Files.space(dir,file.length());try(InputStream in=new FileInputStream(file);OutputStream o=new FileOutputStream(tmp)){Files.copy(in,o,job);}Files.commit(tmp,out,job);MediaScannerConnection.scanFile(c,new String[]{out.getPath()},new String[]{mime},null);return Uri.fromFile(out);}finally{tmp.delete();}}
        if(tree==null||tree.isEmpty())throw new IOException("请先选择文件夹 / Choose a folder first");Uri root=Uri.parse(tree),parent=DocumentsContract.buildDocumentUriUsingTree(root,DocumentsContract.getTreeDocumentId(root));parent=child(cr,parent,feature,DocumentsContract.Document.MIME_TYPE_DIR,true);if(parent==null)throw new IOException("无法创建功能目录 / Cannot create feature folder");String name=file.getName();int suffix=2;Set<String> used=new HashSet<>();Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(parent,DocumentsContract.getDocumentId(parent));try(Cursor cursor=cr.query(children,new String[]{DocumentsContract.Document.COLUMN_DISPLAY_NAME},null,null,null)){if(cursor!=null)while(cursor.moveToNext())used.add(cursor.getString(0));}while(used.contains(name))name=Files.stem(file.getName())+"_"+(suffix++)+Files.ext(file.getName());result=DocumentsContract.createDocument(cr,parent,mime,name);if(result==null)throw new IOException("目录不可写或授权失效，请重新选择 / Folder unavailable; select again");try{try(InputStream in=new FileInputStream(file);OutputStream o=cr.openOutputStream(result,"w")){if(o==null)throw new IOException("文件无法写入 / Cannot write file");Files.copy(in,o,job);}job.check();return result;}catch(Exception e){try{DocumentsContract.deleteDocument(cr,result);}catch(Exception ignored){}throw e;}}
    static Uri shareUri(File f){return new Uri.Builder().scheme("content").authority("com.guangyingruoshui.imagetools.files").appendPath(f.getName()).build();}
}
