using System;
using System.Drawing;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace QQImageSwitch
{
    public sealed class QrPage : ToolPage
    {
        readonly SoftInput url,words;readonly SoftCombo mode,placement,position;readonly NumericUpDown size,x,y,tx,ty,font,border;
        readonly CoverCanvas view;readonly CoverTextOptions text=new CoverTextOptions{Position=3,Y=80};readonly TextLayerSelector layers;readonly Label source,result;readonly Button open;
        Bitmap preview;string imagePath,decoded;bool loading;
        readonly Timer debounce=new Timer{Interval=250};int ticket;bool calculating,again;string completed;
        public QrPage(ExportLocation location,Action<bool> changed):base("二维码制作","填写 Pixiv 等网站的完整链接；软件不上传图片。扫码打开网站，访问权限和原图下载由网站决定。",location,changed)
        {
            url=new SoftInput{Dock=DockStyle.Fill,Multiline=true,MaxLength=1600,Text="https://github.com/pkh2388235687-star/AI-Image-Toolbox"};Ui.Add(Body,Ui.Text("网站链接"));var address=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=2,RowCount=1,AutoSize=true,BackColor=Color.Transparent};address.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));address.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));address.Controls.Add(url,0,0);var paste=Ui.Button("粘贴网址",delegate{try{PasteUrl(Clipboard.ContainsText()?Clipboard.GetText():"");}catch(Exception ex){Status.Text=L.T("无法读取剪贴板：")+ex.Message;}});paste.Anchor=AnchorStyles.Top;paste.Margin=new Padding(10,0,0,0);address.Controls.Add(paste,1,0);Ui.Add(Body,address);
            view=new CoverCanvas{Dock=DockStyle.Top,Height=300,Checker=false,TextPlacement=true,Margin=new Padding(0,0,0,10)};Ui.Add(Body,view);
            mode=Combo(260,"直接生成二维码","图片附上二维码");placement=Combo(220,"拖动二维码","拖动当前文字");Ui.Add(Body,Ui.Flow(Ui.Text("生成方式"),mode,Ui.Text("拖动对象"),placement));
            source=Ui.Text("尚未选择图片",9);Ui.Add(Body,Ui.Flow(Ui.Button("选择底图…",delegate{using(var d=new OpenFileDialog{Filter="图片|*.png;*.jpg;*.jpeg;*.bmp;*.gif"})if(L.Show(d,FindForm())==DialogResult.OK){imagePath=d.FileName;source.Text=Path.GetFileName(imagePath);mode.SelectedIndex=1;Schedule();}}),source));
            size=FileToolPage.Number(10,90,75);x=FileToolPage.Number(0,100,50);y=FileToolPage.Number(0,100,50);Ui.Add(Body,Ui.Flow(Ui.Text("二维码大小（短边 %）"),size,Ui.Text("横向（%）"),x,Ui.Text("纵向（%）"),y));
            border=FileToolPage.Number(0,12,4);Ui.Add(Body,Ui.Flow(Ui.Text("二维码白边（格）"),border));Ui.Add(Body,Ui.Text("白边可调为 0–12 格，推荐至少 4 格。小于 4 格可能导致手机无法扫描；直接生成模式不会添加额外画布留白。",9));
            words=new SoftInput{Width=330,MaxLength=200};position=Combo(180,"自由拖动","上左","上右","上中","中左","正中","中右","下左","下中","下右");font=FileToolPage.Number(2,18,7);tx=FileToolPage.Number(0,100,50);ty=FileToolPage.Number(0,100,80);
            layers=new TextLayerSelector(()=>text,LoadLayer,Schedule);Ui.Add(Body,layers);Ui.Add(Body,Ui.Flow(Ui.Text("文字内容"),words,Ui.Text("放置位置"),position));Ui.Add(Body,Ui.Flow(Ui.Text("文字大小（%）"),font,Ui.Text("横向（%）"),tx,Ui.Text("纵向（%）"),ty,Ui.Button("文字颜色…",delegate{using(var d=new ColorDialog{Color=layers.Active.Color,FullOpen=true})if(L.Show(d,FindForm())==DialogResult.OK){layers.Active.Color=d.Color;Schedule();}})));
            Ui.Add(Body,Ui.Text("二维码始终在文字上方。背景显图可选“二维码优化”：白底保留封面，黑底显示二维码。导入扫描会自动尝试白底和黑底；缩小、遮挡或网站重编码仍可能影响扫描。",9));
            Ui.Add(Body,Ui.Text("扫描二维码",16,true));Ui.Add(Body,Ui.Text("导入透明 PNG 后自动尝试白底与黑底识别，无需手动转换黑底图片。",9));Ui.Add(Body,Ui.Flow(Ui.Button("导入图片扫描…",async delegate{using(var d=new OpenFileDialog{Filter="图片|*.png;*.jpg;*.jpeg;*.bmp;*.gif"})if(L.Show(d,FindForm())==DialogResult.OK)await Scan(d.FileName);}),Ui.Button("相机扫描…",delegate{using(var camera=new QrCamera())if(L.Show(camera,FindForm())==DialogResult.OK)SetResult(camera.Result);})));result=Ui.Text("尚未扫描",10);Ui.Add(Body,result);open=Ui.Button("打开扫描的网站",delegate{try{Process.Start(QrService.Website(decoded));}catch(Exception ex){Status.Text=L.T("无法打开网站：")+ex.Message;}});open.Enabled=false;Ui.Add(Body,Ui.Flow(open,Ui.Button("复制扫描结果",delegate{if(!string.IsNullOrEmpty(decoded))try{Clipboard.SetText(decoded);}catch(Exception ex){Status.Text=L.T("复制失败：")+ex.Message;}})));ActionButton("导出二维码 PNG",async delegate{await Export();});
            foreach(var c in new SoftCombo[]{mode,placement,position})c.SelectedIndexChanged+=delegate{ChangeText();};foreach(var n in new[]{size,x,y,tx,ty,font,border})n.ValueChanged+=delegate{ChangeText();};words.TextChanged+=delegate{ChangeText();};url.TextChanged+=delegate{Schedule();};
            view.PositionChanged+=delegate(object s,TextPositionEventArgs e){loading=true;try{if(placement.SelectedIndex==0){x.Value=e.X;y.Value=e.Y;}else{position.SelectedIndex=0;tx.Value=e.X;ty.Value=e.Y;layers.Active.Position=3;layers.Active.X=e.X;layers.Active.Y=e.Y;}}finally{loading=false;}debounce.Interval=e.Finished?1:40;Schedule();};debounce.Tick+=async delegate{debounce.Stop();await Preview();};FinishLayout();ChangeText();Schedule();
        }
        static readonly int[] Positions={3,4,6,5,7,0,8,9,2,1};
        static SoftCombo Combo(int width,params string[] values){var c=new SoftCombo{Width=width,VisibleRows=3};c.Items.AddRange(values);c.SelectedIndex=0;return c;}
        void LoadLayer(CoverTextOptions t){loading=true;try{words.Text=t.Text;position.SelectedIndex=Array.IndexOf(Positions,t.Position);font.Value=t.SizePercent;tx.Value=t.X;ty.Value=t.Y;}finally{loading=false;}Schedule();}
        void ChangeText(){if(loading)return;bool overlay=mode.SelectedIndex==1;size.Enabled=x.Enabled=y.Enabled=placement.Enabled=words.Enabled=position.Enabled=font.Enabled=layers.Enabled=overlay;view.TextPlacement=overlay;var t=layers.Active;t.Text=words.Text;layers.RefreshNames();t.Position=Positions[position.SelectedIndex];t.SizePercent=(int)font.Value;t.X=(int)tx.Value;t.Y=(int)ty.Value;tx.Enabled=ty.Enabled=overlay&&t.Position==3;Schedule();}
        void Schedule(){ticket++;if(!IsDisposed){if(view.PlacementDragging){debounce.Interval=25;if(!debounce.Enabled)debounce.Start();}else{debounce.Stop();debounce.Start();}}}
        Bitmap Generate(string path,string link,int percent,int px,int py,int margin,CoverTextOptions options,out QrRegion region,int bound=0){using(var image=path==null?null:Codec.Load(path)){if(image==null||bound==0)return QrService.Compose(image,link,1024,percent,px,py,options,out region,margin);var dims=Codec.OutputSize(image,bound);using(var small=Codec.Fit(image,dims.Width,dims.Height,Color.White))return QrService.Compose(small,link,1024,percent,px,py,options,out region,margin);}}
        string PreviewKey(){return mode.SelectedIndex+"|"+imagePath+"|"+(imagePath!=null&&File.Exists(imagePath)?File.GetLastWriteTimeUtc(imagePath).Ticks.ToString():"")+"|"+url.Text+"|"+border.Value+"|"+size.Value+"|"+x.Value+"|"+y.Value+"|"+Inspection.Json().Serialize(text);}
        async Task Preview(){if(Busy)return;if(calculating){again=true;return;}string key=PreviewKey();if(preview!=null&&key==completed)return;calculating=true;int version=ticket;string path=mode.SelectedIndex==0?null:imagePath,link=url.Text;int percent=(int)size.Value,px=(int)x.Value,py=(int)y.Value,margin=(int)border.Value;var options=text.Copy();Bitmap next=null;try{if(mode.SelectedIndex==1&&path==null)throw new ArgumentException("请先选择底图。");next=await Task.Run(()=>{QrRegion r;using(var full=Generate(path,link,percent,px,py,margin,options,out r,1200))return Codec.Fit(full,Math.Max(1,(int)(full.Width*Math.Min(1,900.0/Math.Max(full.Width,full.Height)))),Math.Max(1,(int)(full.Height*Math.Min(1,900.0/Math.Max(full.Width,full.Height)))),Color.White);});if(version!=ticket||IsDisposed)return;view.Image=next;if(preview!=null)preview.Dispose();preview=next;next=null;completed=key;Status.Text=L.T("拖动预览可调整二维码或当前文字的位置。");}catch(Exception e){if(version==ticket&&!IsDisposed)Status.Text=L.T(e.Message);}finally{if(next!=null)next.Dispose();calculating=false;if(again&&!IsDisposed){again=false;Schedule();}}}
        async Task Export(bool show=true){if(Busy||!OutputFolder.Ready())return;string path=mode.SelectedIndex==0?null:imagePath,link=url.Text,destination=OutputFolder.Destination;bool overlay=mode.SelectedIndex==1;int percent=(int)size.Value,px=(int)x.Value,py=(int)y.Value,margin=(int)border.Value;var options=text.Copy();await Run(token=>Task.Run(()=>{if(overlay&&path==null)throw new ArgumentException("请先选择底图。");token.ThrowIfCancellationRequested();QrRegion r;using(var b=Generate(path,link,percent,px,py,margin,options,out r)){if(QrService.Scan(b)!=r.Url)throw new InvalidOperationException("二维码自检失败，请增加二维码大小。");string output=ImageTools.Unique(destination,path??"website.png","_qr",".png");token.ThrowIfCancellationRequested();Codec.SaveAtomic(output,QrService.Tag(Codec.StaticPng(b),r));return L.T("图片已保存。")+"\n"+output;} }),show);}
        async Task Scan(string path){await Run(async token=>{string found=await Task.Run(()=>{using(var b=Codec.Load(path))using(var fitted=Codec.Fit(b,Math.Max(1,(int)(b.Width*Math.Min(1,3200.0/Math.Max(b.Width,b.Height)))),Math.Max(1,(int)(b.Height*Math.Min(1,3200.0/Math.Max(b.Width,b.Height)))),Color.Transparent))return QrService.Scan(fitted);});token.ThrowIfCancellationRequested();SetResult(found);return found==null?L.T("未发现二维码，请导入清晰原图。"):L.T("扫描完成，请核对网站后打开。");},false);}
        void PasteUrl(string value){value=(value??"").Trim();if(value.Length==0){Status.Text=L.T("剪贴板中没有文字网址。");return;}if(value.Length>url.MaxLength){Status.Text=L.T("剪贴板内容过长，请粘贴单个网址。");return;}url.Text=value;url.FocusText();}
        void SetResult(string value){decoded=value;result.Text=value??L.T("未发现二维码，请导入清晰原图。");open.Enabled=false;try{string target=QrService.Website(value);result.Text=new Uri(target).Host+"\n"+value;open.Enabled=true;}catch(ArgumentException){} }
        public override void OnLeavePage(){ticket++;debounce.Stop();}
        public override void OnEnterPage(){base.OnEnterPage();Schedule();}
        protected override void Dispose(bool disposing){if(disposing){ticket++;debounce.Stop();debounce.Dispose();view.Image=null;if(preview!=null)preview.Dispose();}base.Dispose(disposing);}
#if SELF_TEST
        internal async Task CheckBehavior(string folder)
        {
            Directory.CreateDirectory(folder);PasteUrl("  https://www.pixiv.net/artworks/123456789?test=full-url  ");if(url.Text!="https://www.pixiv.net/artworks/123456789?test=full-url"||!url.Multiline)throw new Exception("URL paste/wrap failed");string input=Path.Combine(folder,"base.png");using(var b=SelfTest.Art(900,700,true))Codec.SaveAtomic(input,Codec.StaticPng(b));imagePath=input;source.Text=Path.GetFileName(input);url.Text="https://www.pixiv.net/artworks/123456789";mode.TestChoice(1);size.Value=55;words.Text="First";layers.TestAdd();words.Text="Second";tx.Value=80;ty.Value=15;layers.TestChoose(0);if(text.Text!="First"||text.Extra[0].Text!="Second")throw new Exception("QR layer switch lost content");placement.TestChoice(0);await Preview();view.TestDrag(new Point(view.Width/2,view.Height/2),new Point(view.Width*3/4,view.Height*3/4));await Preview();if(x.Value<55||y.Value<55)throw new Exception("QR drag failed");placement.TestChoice(1);view.TestDrag(new Point(view.Width/2,view.Height/2),new Point(view.Width/3,view.Height/3));if(text.X>45||text.Y>45)throw new Exception("QR text drag failed");
            string prior=OutputFolder.Folder;OutputFolder.TestSetFolder(folder);try{if(OutputFolder.Destination!=Path.Combine(folder,"二维码制作"))throw new Exception("QR subfolder missing");await Export(false);string[] files=Directory.GetFiles(OutputFolder.Destination,"*_qr.png");if(files.Length!=1)throw new Exception("QR page export failed");await Scan(files[0]);if(decoded!=url.Text||!open.Enabled)throw new Exception("QR import scan failed");using(var original=Codec.Load(files[0]))using(var cover=BackgroundRevealAuto.CreateCover(original,0,-1,System.Threading.CancellationToken.None)){BackgroundRevealAuto.Profile profile;using(var hidden=BackgroundRevealAuto.Compose(cover,original,0,false,85,System.Threading.CancellationToken.None,out profile)){var region=QrService.Optimize(hidden,QrService.Read(files[0]),cover,profile,System.Threading.CancellationToken.None);string hiddenPath=Path.Combine(folder,"hidden-import.png");Codec.SaveAtomic(hiddenPath,QrService.Tag(BackgroundRevealAuto.Encode(hidden,false,profile,System.Threading.CancellationToken.None),region));await Scan(hiddenPath);if(decoded!=url.Text||!open.Enabled)throw new Exception("QR page flattened transparency before scanning");}}mode.TestChoice(0);await Preview();while(calculating)await Task.Delay(25);await Preview();await Export(false);SetResult("javascript:alert(1)");if(open.Enabled)throw new Exception("Unsafe scanned scheme opens browser");SetResult(url.Text);}finally{OutputFolder.TestSetFolder(prior);}
            var form=(MainForm)FindForm();var oldSize=form.ClientSize;bool language=L.English;try{foreach(bool en in new[]{false,true}){L.Set(en?"en":"zh");foreach(var dims in new[]{new Size(900,700),new Size(1500,950)}){form.ClientSize=dims;Application.DoEvents();form.ValidateLayout();using(var b=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(b,new Rectangle(0,0,b.Width,b.Height));b.Save(Path.Combine(folder,"qr-ui-"+(en?"en":"zh")+"-"+dims.Width+".png"));}}}}finally{form.ClientSize=oldSize;L.Set(language?"en":"zh");}debounce.Stop();
        }
#endif
    }
}
